### ISSUE TITLE
More documentation...

### ISSUE THREAD

**Issue by dimumurray** [HeapsIO/heaps#101]
Currently the [ref.html](https://github.com/ncannasse/heaps/tree/master/doc) doc is incomplete. I took the liberty of copying the document in its current state to a number of wiki pages [here](https://github.com/ncannasse/heaps/wiki).

Since @ncannasse is busy writing the engine itself other interested parties can chip in and fill in the gaps in the documentation.

**Comment by nadako** [comment]
It would be nice to have haxe source highlighted on that wiki. Use ```haxe for code blocks (see https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting)

**Comment by dimumurray** [comment]
Wasn't aware I could do that. Thanks. (And @nadako I'm still waiting for you to make your Ash port more haxey :smile: )

**Comment by nadako** [comment]
sorry for OT, but I'd really check out https://github.com/fponticelli/edge for a "more haxey ash". i'm not really motivated to work on ash, especially when there's such a nice library already out there.

**Comment by dimumurray** [comment]
Ok...the [wiki](https://github.com/ncannasse/heaps/wiki) now fully mirrors the structure of the ref.html doc. All we need now is more content!

**Comment by sonygod** [comment]
hi,I just use your wiki tutorial  try to finish example 1,but no luck,the compile throw error 

haxe version 3.1.3 

https://github.com/ncannasse/heaps/wiki/H2D-Concepts

will you check that example can be really compile?

**Comment by dimumurray** [comment]
@sonygod Do you have the latest version of heaps installed?

**Comment by dimumurray** [comment]
@sonygod Try installing the latest version using this command:
`haxelib git https://github.com/ncannasse/heaps.git`

**Comment by TiZ-EX1** [comment]
Documentation hasn't been touched since May 20. Is there a plan for this? Is it encouraged to fork this, poke the engine and learn the hard way, update wiki docs, and then send pull requests?

**Comment by dimumurray** [comment]
The wiki isn't bound to the repo so you don't need to fork the project or send pull requests to edit it. Just go to a page of interest and hack away at it. You'll need to be familiar with github's flavor of MarkDown but it just be easy to pick up.

**Comment by ncannasse** [comment]
This is in progress, see https://community.heaps.io/t/best-way-to-grow-community/43/3?u=ncannasse for contributing.
