### ISSUE TITLE
HxBit?

### ISSUE THREAD

**Issue by melMass** [HeapsIO/heaps#1033]
Hello,

I'm reiterating on a program I wrote a few years ago using heaps, I managed to update most of it, but I was relying on a few aspect of its hxbit implementation.
I looked through the commits and PRs and I could locate where it was fully removed, but not why or if there was an alternative.

Thanks

**Comment by ncannasse** [comment]
Hxbit was moved there :
https://github.com/HeapsIO/hxbit
Or do you mean the ability to serialize scene objects ? In which case it
was replaced by Hide prefab system https://github.com/heapsio/hide

Le jeu. 30 déc. 2021 à 01:41, Mel Massadian ***@***.***> a
écrit :

**Comment by melMass** [comment]
Thanks Nicolas! I was looking for the later, I'll dive into Hide!
I'm not sure of where is the best place to look for changes in the codebase, but I'm usually checking, release notes and commits, and I could not find a reference to this move, I guess this issue will be one ;)

Thanks again
