### ISSUE TITLE
Sound `Channel` position is shifted after un-pausing it for the second and subsequent times

### ISSUE THREAD

**Issue by miriti** [HeapsIO/heaps#1034]
Here's a working example of what I'm talking about: https://s3.eu-central-1.amazonaws.com/michael-miriti.com/heaps-pause/index.html

Clicking the green rectangle toggles `channel.pause` property. Text on the right displays the current `channel.position` value.

**Expected behavior:** 
After setting `channel.pause` to `false` it continues to play from the position at which `channel.pause` was set to `true`. The value of `channel.position` reflects the actual position of the playback

**Actual behavior:**
After setting `channel.pause` to `false` when previously it was set to `true` once the sound continues to play as expected but `channel.position` value resets to `0`. After that when the value of `channel.pause` is set to `true` and then back to `false` the sound continues to play from seemingly random position while `channel.position` always resets to `0`

Reproduces on both Hashlink (Linux) and HTML5 targets.

Heaps version: `git` (commit ab2ce16d2b280a4681b56852b37c7d3aef789682)

I tried to dig a little bit to get a clue of what's going on. Looks like `driver.getPlayedSampleCount()` returns wrong amount of played samples after pausing while I believe the value should remain the same while channel is paused? Not sure how to proceed with it.  https://github.com/HeapsIO/heaps/blob/master/hxd/snd/Manager.hx#L357

Code ([zip archive](https://s3.eu-central-1.amazonaws.com/michael-miriti.com/heaps-pause/heaps-pause.zip)):

```haxe
import h2d.Graphics;
import h2d.Interactive;
import h2d.Text;
import hxd.App;
import hxd.Res;
import hxd.res.DefaultFont;
import hxd.snd.Channel;

class Main extends App {
	var channel:Channel = null;
	var posText:Text;

	override function init() {
		final btn = new Graphics(s2d);
		btn.beginFill(0x00ff00);
		btn.drawRect(0, 0, 200, 200);
		btn.endFill();

		final interactive = new Interactive(200, 200, btn);

		interactive.onPush = (e) -> {
			if (null == channel) {
				channel = Res.catch_me.play(true);
			} else {
				channel.pause = !channel.pause;
			}
		};

		posText = new Text(DefaultFont.get(), s2d);
		posText.x = 205;
		posText.scale(4);
	}

	override function update(dt:Float) {
		if (channel != null)
			posText.text = '${channel.position}';
	}

	static function main() {
		Res.initEmbed();
		new Main();
	}
}
```

**Comment by ncannasse** [comment]
I've little time to investigate this, but setting the channel to pause
should set it as isVirtual=true then release the hardware channel, not
calling getPlayedSampleCount anymore
