### ISSUE TITLE
WebGL sampler2D precision required

### ISSUE THREAD

**Issue by rcstuber** [HeapsIO/heaps#1035]
WebGL on Chrome now seems to require a specified default `precision` for `sampler2DArray` or else shader compilation will fail. 
Adding `precision mediump sampler2DArray;` to the shader header fixes this. Not sure which of low/medium/high is the best choice. Should be added below this line:

https://github.com/HeapsIO/heaps/blob/ab2ce16d2b280a4681b56852b37c7d3aef789682/hxsl/GlslOut.hx#L663

**Comment by ncannasse** [comment]
Please submit a PR linking this issue, thanks :)
