### ISSUE TITLE
Heaps screen shader works fine in SDL but throws compilation error at runtime in DX

### ISSUE THREAD

**Issue by Cleod9** [HeapsIO/heaps#1044]
Created a minimally reproducible test case here: (Tested in Haxe 4.2.3, Hashlink 1.12.0)

https://github.com/Cleod9/heaps-outline-shader-hldx-bug

The shader is supposed to render a stroke outline surrounding the visible pixels of a bitmap with the desired thickness and color.

Here's the expected output working fine in SDL:
![image](https://user-images.githubusercontent.com/3649914/152425911-60b04233-f262-43cf-991a-61590c321af3.png)

But in DX I get the following stack trace:
```
Shader compilation error 
<< out >>: error X3000: syntax error: unexpected token 'out'

<< tex.GetDimensions(tex, (uint)lod, out w, out h) >>: error X3013: 'GetDimensions': no matching 0 parameter intrinsic method

<< tex.GetDimensions(tex, (uint)lod, out w, out h) >>: error X3013: Possible intrinsic methods are:

<< tex.GetDimensions(tex, (uint)lod, out w, out h) >>: error X3013:     Texture2D<float4>.GetDimensions(uint, out uint width, out uint height, out uint levels)

<< tex.GetDimensions(tex, (uint)lod, out w, out h) >>: error X3013:     Texture2D<float4>.GetDimensions(uint, out float|half|min10float|min16float width, out float|half|min10float|min16float height, out float|half|min10float|min16float levels)

<< tex.GetDimensions(tex, (uint)lod, out w, out h) >>: error X3013:     Texture2D<float4>.GetDimensions(out uint width, out uint height)
...etc.
```
I tried another attempt to make a similar shader with Outline2D (commented out in the source code), although it seems to only generate a really thin outline that is consistent both in SDL and DX:
![image](https://user-images.githubusercontent.com/3649914/152426065-e912a4f6-2e58-426b-939f-eaa5dbb61486.png)
Would greatly appreciate any assistance on this matter, whether it be a workaround or potential bugfix.

**Comment by ncannasse** [comment]
Interesting, looks like a bug in HxSL output to HLSL : an extra out parameter "mipLevels" is required.
look if it gets fixed by replacing the first define in HlslOut.hx (line ~344) by:

			decl("float2 textureSize(Texture2D tex, int lod) { float w; float h; float levels; tex.GetDimensions(tex, (uint)lod, out w, out h, out levels); return float2(w, h); }");

**Comment by Cleod9** [comment]
Thank you @ncannasse for taking a look at this. I updated that line of code but it seems like the same error occurs (i confirmed my modification to the code was applied with a trace statement in HlslOut.hx to be certain)

I pasted the full stack trace here if that helps:
https://gist.github.com/Cleod9/ad88e02c6d16f23781f26569a2995fe2

**Comment by ncannasse** [comment]
Uhm yeah it seems it shouldn't be tex.GetDimensions(tex, ...) as the "tex" parameter is not necessary.

**Comment by ncannasse** [comment]
Uhm wait this seems to be have fixed already on master here https://github.com/HeapsIO/heaps/commit/8caf26d78bc13b0fe892fde3de0a2d779b379d06
