### ISSUE TITLE
Unreachable exception thrown by SocketHost

### ISSUE THREAD

**Issue by DesidiaDev** [HeapsIO/heaps#1051]
Upon the server becoming unreachable, the socket throws an error using the socket.onError function set when calling socketHost.connect which in the context of the connect function is ok as you can catch it, but when this onError function is called due to a problem with the connection it then gets thrown up outside of the game loop.

I solved this on my side by extending SocketHost and overriding connect as such
```
override function connect( host : String, port : Int, ?onConnect : Bool -> Void ) {`
	super.connect(host, port, onConnect);
	socket.onError = function(msg) {
		close();
	}
}
```
I haven't fully tested how robust it is but it's definitely worth doing something to prevent a pesky exception from slipping past the game loop

EDIT: My solution didn't hold up

**Comment by ncannasse** [comment]
The SocketHost is just a small example of using hxbit.NetworkHost. You can eventually add an error handler to it and call this instead of "throw".
