### ISSUE TITLE
Not available on HaxeLib?

### ISSUE THREAD

**Issue by zauberparacelsus** [HeapsIO/heaps#106]
Not 100% sure if this is the best place to post this...

The wiki instructs you to install heaps via haxelib, either just by "haxelib install heaps", or by installing from git.  However, when running the first install command, I get an error saying "No such Project : heaps".  Running a search command for heaps reveals only one match, a library called dheap.

**Comment by dimumurray** [comment]
I think @ncannasse decided to pull heaps from haxelib until it was more mature. The wiki is more or less a community effort (not maintained by any one person) so you can update it to reflect the change if you want to. In the meantime you can to pull the library from github using the following command:
```
haxe git heaps https://github.com/ncannasse/heaps.git
```

**Comment by ncannasse** [comment]
Heaps is now on haxelib !
