### ISSUE TITLE
[hl] Sound stops after ca. 1s (Haxe v4.2.4 or later)

### ISSUE THREAD

**Issue by fal-works** [HeapsIO/heaps#1069]
When played any sound with `hxd.res.Sound.play()`, the sound will stop after ca. 1 second.

Env:
- Haxe: v4.2.4 / v4.2.5 / nightly 307c024
- HashLink: v1.11.0 / [latest](https://github.com/HaxeFoundation/hashlink/releases/tag/latest)
- heaps: v1.9.1 / current master

Repro:
- https://github.com/fal-works/repro-heaps-sound-stops
- Seems to be the same with `heaps/samples/Sound.hx`
- Does not reproduce if one of the below applies:
    - JS target
    - Haxe v4.2.3 or less

**Comment by Simn** [comment]
See #1068, and https://github.com/HaxeFoundation/haxe/issues/10682

**Comment by fal-works** [comment]
Ah sorry, missed checking the closed issues.
