### ISSUE TITLE
Point lights broken

### ISSUE THREAD

**Issue by Misiur** [HeapsIO/heaps#1075]
https://heaps.io/samples/lights.html - the lights are broken.

I thought maybe https://github.com/HeapsIO/heaps/commit/ab2ce16d2b280a4681b56852b37c7d3aef789682 fixed it, but it's not the case.

Locally checked with today's git version, broken as well. No difference between browsers.

**Comment by edwood-grant** [comment]
Hey @Misiur, If you are using PBR lights, a quick workaorund for now would be to set for every ligth you create a value for the Light.occlusionFactor (0 is the default), as this value is undefined by the time it gets to the browser and the shader fails catastorfically (and thus black lights).

Something like this will do the trick:
```
var l = new DirLight(parent);
l.occlusionFactor = 0.0;
```

The PBr should set this (an other values) to a defualt value so it doesn't happen, the specific values are:
* SpotLight.fallOff
* PointLight.size
* Light.occlusionFactor  

You might want to set those values as well for ther light types as well.
