### ISSUE TITLE
Questions about the wiki and docs

### ISSUE THREAD

**Issue by marcelEuchnerMartinez** [HeapsIO/heaps#1078]
Hi there!
- Recently I added more things to the [Wiki](https://github.com/HeapsIO/heaps/wiki). There was no barrier or anything it seems everyone can just make edits.
Is that okay? I wondered if there might emerge conflicts with these [**docs files**](https://github.com/HeapsIO/heaps-doc). Well it says it is just a "mirror" but I feel a little unsure here. It's also possible to re-structure the whole wiki sidebar and any article/section name (I mean no griefing/trolling protection, but I think that's okay, was for me at least). Only found this tiny link in the footer that points from wiki to docs. (So do you prefer **wiki edits via git pull requests** instead?)
- Also the wiki pages are **really hidden**. I would like to know if there'll be a point in time when they might be updated for the [official site](https://heaps.io/documentation/home.html), in case beginners can't find them. (If programmers use the wiki at all I mean...)
- I was also wondering about **guidelines when editing the wiki**: By that I mean since Heaps is MIT licensed may I make a site to point towards for instance the [site of deepnight](https://deepnight.net/tutorials/)? (Also @deepnight here). And making a small section about sub-engines built on Heaps? I will also ask @Beeblerox if I may copy some of the [samples he made](https://github.com/Beeblerox/Simplest-Heaps-Examples). For instance about [`h2d.Flow`](https://github.com/Beeblerox/Simplest-Heaps-Examples/tree/master/20_heaps_flow)

I wanted to explain how to use the `h2d` side of Heaps as straight forward as possible so that's all the new content is about. Currently the sidebar structure is a mixture of step-by-step guide and API. So this is about what I added:
  - I made changes beginning at [First outlook](https://github.com/HeapsIO/heaps/wiki/First-outlook) (what to do after installing Heaps)
  - then made changes to the [H2D Introduction](https://github.com/HeapsIO/heaps/wiki/H2D-Introduction), [Objects](https://github.com/HeapsIO/heaps/wiki/Objects), [Object trees](https://github.com/HeapsIO/heaps/wiki/Object-trees), [Scenes](https://github.com/HeapsIO/heaps/wiki/Scenes) (maybe should rename it "H2D Scenes"?), [Layers](https://github.com/HeapsIO/heaps/wiki/Layers), [2D Camera](https://github.com/HeapsIO/heaps/wiki/2D-Camera), [Drawable](https://github.com/HeapsIO/heaps/wiki/Drawable) and [Flow](https://github.com/HeapsIO/heaps/wiki/Flow) (by the way all sample code snippets there are now "copy&paste&compile" because these sections didn't require resource files to explain the API)
  - a new section for [sample games](https://github.com/HeapsIO/heaps/wiki/Sample-games-for-learning) (not jam games), I mean really samples/templates

Thank you.
Marcel Euchner-Martinez

PS: hm...for some obscure reason I cannot mention him by @ sign but https://github.com/olichose123: your phrasings are still there between the lines in case you wonder...

**Comment by yuxiaomao** [comment]
I don't know what is the preferred way, but given that PRs are not review and merge very quickly, edit wiki directly is still possible now. Please keep the wiki simple and easy to understand.
The current wiki content is sync to the website now (we probably need some more review).
Thank you for your contributions!
