### ISSUE TITLE
How to dynamically load resources on Android or IOS instead of embedding them.

### ISSUE THREAD

**Issue by rainyt** [HeapsIO/heaps#1080]

**Comment by ncannasse** [comment]
See https://github.com/HeapsIO/heaps/wiki/Resource-Management
( Use localFS or pakFS)

**Comment by rainyt** [comment]
https://github.com/rainyt/zyheaps/commit/a335a9d25aaeaa8cee802ebeae6c90b70603f15e

Android cannot load assets resources through the path. I implemented it.
