### ISSUE TITLE
play does not work correctly for some content

### ISSUE THREAD

**Issue by octplane** [HeapsIO/heaps#1100]
When using Hashlink, it seems very difficult to have the engine `play` something that should play for some time, such as a background music. It starts and stops after 200-300ms, something like that.

```haxe
import hxd.snd.SoundGroup;
import hxd.res.Sound;

class Soundz extends hxd.App {
	var musicResource:Sound = null;

	override function init() {
		hxd.Res.initEmbed();
		startMusic();
	}

	function startMusic() {
		if(hxd.res.Sound.supportedFormat(OggVorbis)){
			musicResource = hxd.Res.sound.mutecity;
			if(musicResource != null){
				var sg: SoundGroup = new SoundGroup("hop");
				sg.mono = true;
				musicResource.play(true, sg);
			}
		}
	}

	override function update(dt:Float) {
	}

	static function main() {
		new Soundz();
	}

}
```

```shell
oct@Hokusai bin % haxe --version
4.2.5
oct@Hokusai bin % hl --version
1.12.0
```

compile.hxml:
```
-cp src
-D windowSize=640x480
-hl hello.hl
-lib heaps
-lib hlsdl
-main Soundz
--resource res/sound/mutecity.ogg@mutecity
```

**Comment by octplane** [comment]
For some reason, trying to build the html output for the same sample code fails earlier during the Resource resolution:

```
-cp src
-D windowSize=640x480
-lib heaps
-js bin/game.js
-main Soundz
--resource res/sound/mutecity.ogg@mutecity
```

```
oct@Hokusai hello % haxe js.hxml
src/Soundz.hx:14: characters 20-42 : hxd._res._Sound has no field mutecity
```

**Comment by MSGhero** [comment]
It sounds like this, from ZwodahS in discord:

Sound bug in heaps, See
https://github.com/HeapsIO/heaps/issues/1068
https://github.com/HaxeFoundation/haxe/issues/10682

A simple fix is to put this line in your App.init
`@:privateAccess haxe.MainLoop.add(() -> {});`

**Comment by octplane** [comment]
> A simple fix is to put this line in your App.init
> `@:privateAccess haxe.MainLoop.add(() -> {});`

Thanks!

**Comment by octplane** [comment]
Duplicate of #1068
