### ISSUE TITLE
Indexing Scalar arrays in shader

### ISSUE THREAD

**Issue by onehundredfeet** [HeapsIO/heaps#1120]
I'd like to be able to provide scalar arrays to my shaders, but the flattener only supports arrays that are multiples of vectors (4 components). 

What would be the best approach to add this support?

1) Break out scalar arrays into their own variable away from the packed vectors in the automatic global generation?
i.e. if the array is referenced at all, it pulls the whole array in as a block with its own variable in GLSL.

This to me seems like the best approach, but it's significant work.

2) Consume a whole vector row per scalar, use the existing indexing

This seems ridiculously wasteful.

3) Build a new feature that allows for arbitrary arrays (buffers) to be added to hxsl. 

This is similar to #1 but a little more expansive.  It would allow for arrays of any kind to be represented on a separate path from globals or parameters, these would allow for referenced buffers (like skin matrices) to be indirectly referenced instead.  This would also provides an implementation that would be closer to how compute shaders would access it.

This is by far the most work and would require a fairly invasive change to some of the core of heaps.

#4 - Any other ides?

**Comment by onehundredfeet** [comment]
I've found the Buffer type in HXSL, I'll see if that does what I need.

**Comment by ncannasse** [comment]
Yes buffers should work. I think we should add documentation for these.

**Comment by onehundredfeet** [comment]
They certainly get a lot closer.  Right now they are specified with packing std140 which still pads to vectors.


> std140: This layout alleviates the need to query the offsets for definitions. The rules of std140 layout explicitly state the layout arrangement of any interface block declared with this layout. This also means that such an interface block can be shared across programs, much like shared. The only downside to this layout type is that the rules for packing elements into arrays/structs can introduce a lot of unnecessary padding.
> The rules for std140 layout are covered quite well in the OpenGL specification ([OpenGL 4.5, Section 7.6.2.2, page 137](http://www.opengl.org/registry/doc/glspec45.core.pdf#page=159)). Among the most important is the fact that arrays of types are not necessarily tightly packed. An array of floats in such a block will not be the equivalent to an array of floats in C/C++. The array stride (the bytes between array elements) is always rounded up to the size of a vec4 (ie: 16-bytes). So arrays will only match their C/C++ definitions if the type is a multiple of 16 bytes

I'll see if I can figure out a proposal for allowing different packing specifications.

**Comment by ncannasse** [comment]
That seems normal given the way the GPU works. If it's constant data, why not using a texture ?

**Comment by onehundredfeet** [comment]
The data doesn't need to be filtered and is only 1024 floats, and consuming a texture / sampler slot isn't really needed. 

However, you're right, it could be totally done using a texture.  If going the buffer route takes too much work I may just switch to a texture, like you say. Ideally, I would like to test both paths for performance.

I was also looking into the arbitrary buffer path to see how I might be able to incorporate compute shaders into heaps.
