### ISSUE TITLE
Some samples don't compile (Bounds)

### ISSUE THREAD

**Issue by JohnEmhoff** [HeapsIO/heaps#1130]
Some samples fail to compile. The errors below are for the "Bounds" sample: it looks like a missing field `customFont` and an error in the resource module?

```
$ cat compile.hxml
-cp src
-lib heaps
-lib hlsdl
-main Main

$ haxe compile.hxml  --hl out.hl -D resourcesPath=...
src/Main.hx:32: characters 35-45 : Class<hxd.Res> has no field customFont
.../haxe/lib/heaps/1,9,1/hxd/Res.hx:15: characters 52-96 : Type not found : Bounds
.../haxe/lib/heaps/1,9,1/hxd/Res.hx:15: characters 52-96 : ... For function argument 'fs'
.../haxe/lib/heaps/1,9,1/hxd/Res.hx:15: characters 52-96 : ... For function argument 'l'
src/Main.hx:1: lines 1-65 : ... Defined in this class
```

It looks like there's a `defaultFont` in the heaps distribution, so changing `customFont` -> `defaultFont` fixes that error, which just leaves the `Type not found` error.

This is with `src/Main.hx` containing the source from https://heaps.io/samples/bounds.html.

**Comment by ncannasse** [comment]
You need -D resourcesPath=.. (not ...)

**Comment by JohnEmhoff** [comment]
Sorry, that was an ellipses not a literal 3 dots. The path I had was correct, the issue is that the code tries to find the wrong font. There's also the type error remaining.

**Comment by ncannasse** [comment]
Could you try with heaps git ?
