### ISSUE TITLE
Special Keys Sent Twice

### ISSUE THREAD

**Issue by nevergarden** [HeapsIO/heaps#1158]
I don't know if this is intended or a bug but special keycodes are being sent twice

https://github.com/HeapsIO/heaps/blob/6528ebc07adb3e13dd2aa8ebe12a7a592538b8fd/hxd/Window.hl.hx#L400

There should be a `return` after `onEvent`

**Comment by ncannasse** [comment]
This is not a bug but a feature : the key is both sent with its full
keycode (with left / right variant) et with its unlocated variant.
For instance pressing Shift will trigger both  EDown LeftRight + EDown
Shift, allowing the application to either handle one or the other depending
if location is required.

**Comment by nevergarden** [comment]
Got it so you can both check key sent with `Key.Shift` and/or `Key.LShift`, `Key.RShift`
