### ISSUE TITLE
Samples break in JS

### ISSUE THREAD

**Issue by zhylmzr** [HeapsIO/heaps#1159]
1. Remove old heaps version using haxelib.
2. Clone the master 1936c9c41f3dbaed35f15cc124f27f6bfe65db08 to haxe libs directory and rename `1,10,0`.
3. Copy `samples` directory to `~/samples`.
4. In `~/samples`, run `haxe gen.hxml && cd build/base2D && haxe base2D_js.hxml`.
5. Open the `index.html`, the page is blank with many webgl warning:
`[.WebGL-0x138004bdc00] GL_INVALID_OPERATION: Vertex buffer is not big enough for the draw call`
 
The version of hashlink work fine.

Other info: 
1. macOS 13.4.1 (M1)
2. haxe version: 5.0.0-alpha.1+3a5140e

The compile outputs: 
[base2D.zip](https://github.com/HeapsIO/heaps/files/12299931/base2D.zip)

**Comment by qlambert-pro** [comment]
b78173ed1a57d04683ca966cdf503c120577f2dd breaks a lot
970473de introduces the webgl warning messages mentioned above
