### ISSUE TITLE
Samples .js files missing after running "haxe gen.hxml"

### ISSUE THREAD

**Issue by min-pascal** [HeapsIO/heaps#1184]

**Comment by ncannasse** [comment]
gen.hxml is only doing the projects generation in samples/build. You can then either simply compile each project or run all.hxml

**Comment by min-pascal** [comment]
I've tried to build the base3D example but encounter a couple of "has no field" errors when running "haxe samples/build/base3D/base3D_js.hxml" mainly related to Text.hx, Image.hx, DirLight.hx and SignedDistanceField.hx

**Comment by min-pascal** [comment]
I reinstalling heaps fixed the issue
