### ISSUE TITLE
getDeterminant() returns 1 

### ISSUE THREAD

**Issue by NicholasHasAwoken** [HeapsIO/heaps#1227]
I was trying to get the default library function to get me inverses of the matrix, but eventually through debugging I realized that the matrices I ger aren't the ones I want. So I've stumbled on this weird piece of behaviour, where for some reason the **invDet** local variable is evalueted to be 1. On the left are values that, I think should be used to calculate this number.
![image](https://github.com/user-attachments/assets/1ee00f71-1e27-4b59-a955-960d5e47cb1f)
On the next screenshot are .toString() values of matrix I want to have inversed AND result of inverse() function.
![image](https://github.com/user-attachments/assets/d06d59f8-5018-463a-8ea5-b6e710d33eb5)

I would like to know if I'm getting something wrong here, but I really think **invDet** variable should be somewhere close to _0,3849_ rather than _1_.

**Comment by NicholasHasAwoken** [comment]
Now, I know what actually is happening is here. What we can see here is just an example of weird behaviour, but it's simply related  to the **inline** nature of the most of **Matrix** _class_ functions.

Docs say n.inverse(m:Matrix) returns inverse of Matrix m and stores result in n. It is _partially true_. While functions inverse() uses a, b c, d of Matrix **m** provided to calcualte new basis values, it actually uses values stored in **n** to calculate determinant so the result of this function is determined by **both** **m** and **n**. 

So, one workaround I found is using code like this:
`var hx=hexTotal.clone();
hx.inverse(hexTotal);`
Instead of this code I used previously:
`var hx=new Matrix();
hx.inverse(hexTotal);`
What was wrong with this expression is that this code initializes **hx**'s values  [a c x] [b d y] to [1 0 0] [0 1 0] and determinant() of these values is 1. With updated code I now get the matrices I want.

**Comment by TothBenoit** [comment]
Nice catch !

In the function inverse :
`var invDet = 1 / getDeterminant();`
should be :
`var invDet = 1 / m.getDeterminant();`

I sent the fix. Thanks for the investigation :)
