### ISSUE TITLE
Incorrect implementation of Object.move()

### ISSUE THREAD

**Issue by daimahou** [HeapsIO/heaps#1246]
The current implementation of the method h2d.Object.move() is the following.

```
/**
    Move the object by the specified amount along its current direction (`Object.rotation` angle).
**/
public function move( dx : Float, dy : Float ) {
    x += dx * Math.cos(rotation);
    y += dy * Math.sin(rotation);
}
```

However, this will not more the object as intended, it will move the object in the absolute x and y, moreover, if the rotation is 0, it will simply ignore the y movement altogether.

The correct implementation is : 

```
/**
    Move the object by the specified amount along its current direction (`Object.rotation` angle).
**/
public function move(dx: Float, dy: Float) {
    x += dx * Math.cos(rotation) - dy * Math.sin(rotation);
    y += dx * Math.sin(rotation) + dy * Math.cos(rotation);
}
```

**Comment by ncannasse** [comment]
Please submit a patch

Le lun. 2 déc. 2024, 01:35, Nicolas Gerard ***@***.***> a
écrit :

**Comment by daimahou** [comment]
I create a pull request with the change.
