### ISSUE TITLE
textWidth with align

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#168]
h2d.Text.textWidth is wrongly reported when align is not left. It should use `calcWidth - min(xLine)`

**Comment by trethaller** [comment]
As far as I can tell `getBoundsRec` is also incorrect since it always returns 0 for x. Shouldn't x be negative for Center and Right alignments?

	override function getBoundsRec( relativeTo : Sprite, out : h2d.col.Bounds, forSize : Bool ) {
		...
		} else {
			x = 0;
			y = calcYMin;
			w = calcWidth;
			h = calcHeight - calcYMin;
		}

**Comment by trethaller** [comment]
There seems to be multiple bugs with text fields right now. I've made a new sample that shows both `getSize` (blue background) `getBounds` (green lines) and `textWidth` and `textHeight` (red lines)

![text-bugs](https://user-images.githubusercontent.com/1499344/30510216-6b1215be-9ab7-11e7-9820-995706622f5c.png)

1. Width seems to be half the size and zero for Center and Right alignment (respectively) for single-line text with no `maxWidth`
2. For multiline text, the first line is ignored in the calculation when alignment is not Left
3. Inconsistency in how `getBounds` and `getSize` give different results based on alignment (here I'm not sure what the proper behavior is)
4. When `maxWidth` is not set, bounds and sizes will always start from x=0, even though the displayed text starts from a negative x (not sure if this is a bug or as designed?)

Still WIP, but this is the sample I've used to reproduce the bugs:
https://gist.github.com/trethaller/b5692a812177f48ab0cacae062af68df

**Comment by trethaller** [comment]
Right, I have fixed a few things, but I'm still not sure how `getBounds` and `getSize` are supposed to be different. But as far as I can tell all non-fixed-width textfields now have proper size and bounds:
![text-fixes1](https://user-images.githubusercontent.com/1499344/30519287-2ed5b37a-9b8a-11e7-9883-59f357ebdc2d.gif)

**Comment by trethaller** [comment]
One more thing: `Font.baseLine` seems to be null for ttf fonts, so `calcSizeHeight` is 0, and `getSize` is returning 0 height

**Comment by ncannasse** [comment]
getSize() was introduced recently with `h2d.Flow` for UI building. While getBounds() should be strictly equal to the graphics being displayed (not a single pixel out), getSize() is used to align elements on the font baseLine

**Comment by ncannasse** [comment]
One thing I haven't much looked at is the actual meaning of having getSize() xMin/yMin being different than 0, and the consequences that goes with it.

You can visually test this by mixing texts and Bitmap inside a h2d.Flow (both vertical and horizontal). The Flow maxWidth/Height can constraint the text size if there is no constraint already set.

**Comment by trethaller** [comment]
Thanks for the explanation. I'll use h2d.Flow in my Text sample and see how it goes. I've also found that `setScale` complicates the matter on Text. Any opinion on how this should affect bounds and textWidth/textHeight?

**Comment by ncannasse** [comment]
textWidth/textHeight should always be in the local coordinates, so not
affected by scaling.
getBounds should be affected if you don't pass the textfield itself as the
"relativeTo" target
getSize should be affected since it's always relative to the parent.

**Comment by trethaller** [comment]
Here is what I have so far:
https://github.com/trethaller/heaps/commit/73df7d366239c3e7b87fdbdd7533139832d025c2

Here is my Text sample, which illustrate various problems and how my changes fix them:
https://github.com/trethaller/heaps/commit/49fc80674ba7987176095ee540f06639d6bba54a

Testable version here:
https://trethaller.github.io/misc/heaps/text-fixes/index.html

I confirm that horizontal Flow is not working properly with alignment other than Left, even with my changes.

**Comment by ncannasse** [comment]
Looks good so far. And yes, I don't think it makes much sense to support
not left aligned texts in flow, given you should be using the flow
properties to align instead.

**Comment by trethaller** [comment]
I tested with a bitmap font that clearly goes under the baseline and it doesn't look at good (but not much worse than with the original version of Text):

![image](https://user-images.githubusercontent.com/1499344/30761367-e3424c52-9fd5-11e7-8fae-5095497d22c7.png)

I'm going to look into this. Is it okay to add a OFT license font to samples/res? It's this one: http://www.dafont.com/eligible.font

**Comment by ncannasse** [comment]
Sure. Looks like there is some kind of wrong pivot here, given the offset
at the top.

**Comment by ncannasse** [comment]
PS: we mostly use bitmap fonts exported with FontBuilder
https://github.com/andryblack/fontbuilder/downloads . Runtime font support
is not supported on all targets and render quality can vary so I don't
think that's the best option in general.

**Comment by trethaller** [comment]
There was actually something wrong with the font I was using. I switched to Gravity.
I was able to also fix Flow to support non-Left alignments:

https://trethaller.github.io/misc/heaps/text-fixes/index.html

For reference, without the fixes this is how the sample looks like:

https://trethaller.github.io/misc/heaps/text-fixes/original/index.html
