### ISSUE TITLE
hxd.Pad improvements

### ISSUE THREAD

**Issue by delahee** [HeapsIO/heaps#172]
Hi Dudes !

If that is of any interest to you, I improved hxd.Pad a tiny bit : https://github.com/delahee/h3d/blob/master/hxd/Pad.hx

I added polling, naming, auto configuration matching, previous frame retaining and removal support.

This allow to perform much advanced control with less dynamic allocations and better quality controls.
Did it because the event listeners were causing GC hits.

++

**Comment by ncannasse** [comment]
I'll look into it another time when I rework on Pad support.
