### ISSUE TITLE
HtmlText Align doesn't work

### ISSUE THREAD

**Issue by LouisSong** [HeapsIO/heaps#183]
when I use the htmlText,set textAlign to center,then set the text which contains a "<br />",It is not center align.my code:
`var label = new HtmlText(font,s2d);
label.textAlign = Align.Center;
label.text = "你好<\ br>中国";`

**Comment by ncannasse** [comment]
Yes I'm aware of the issue. In the meanwhile you can use the new `h2d.Flow` which allows stream of elements.

**Comment by ncannasse** [comment]
TextAlign should now correctly be supported on HtmlText.
