### ISSUE TITLE
GLSL version 130 not supported on Mac

### ISSUE THREAD

**Issue by jacekszymanski** [HeapsIO/heaps#190]
Demos when compiled on Mac native with lime/openfl fail with this error:

```
Error : An error occurred compiling the shaders: ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: 'precision' : syntax error: syntax error
```

I'm running El Capitan.

**Comment by zauberparacelsus** [comment]
http://stackoverflow.com/questions/20264814/glsl-version-130-on-mac-os-x-causes-error

**Comment by kiroukou** [comment]
We had a working fix on motiontwin/heaps repository which use the runtime
gl version.
The pull request hasn't been done...

Le 15 oct. 2016 18:24, "Zauber Paracelsus" <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
ping @pperidont

**Comment by ncannasse** [comment]
I think we have it fixed now.
