### ISSUE TITLE
Over interactive stacking

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#209]
It should be possible to have several currently "overed" elements when propagateEvents=true

**Comment by Yanrishatum** [comment]
* Should propagation work via Object tree (e.g. parent Interactive gets propagated events) or on factual contact (Interactive that are under mouse get propagated events)? Or both?
* Should Interactive from s2d propagate to s3d Interactives?
* Should `InteractiveScene.dispatchEvent` propagate? (It most likely should, as it used for `EReleaseOutside` event)
* Can there be multiple focused/pressed Interactives? If no, which Interactive gets the state (topmost/bottommost)?

**Comment by ncannasse** [comment]
- stacking should be factual contact only
- it should propagate among the different "scenes" registered
- I think so...
- Only one focused. Not sure yet about pressed but I think one is enough for now.

**Comment by Yanrishatum** [comment]
Actually, at least for s2d, event propagation already works. Outdated issue? From observed:
- Found a small bug with clicks (easy fix)
- Mainly need to change `currentOver` in `SceneEvents` from one instance to List/Array so `onOver` would properly report true for propagated Interactives.
Now that I think on it, I probably misunderstood issue meaning, and it meant that propagation works, but `currentOver` reports only the topmost Interactive?

**Comment by ncannasse** [comment]
Yes atm there can be only one over Interactive.

Le sam. 26 janv. 2019 19:34, Pavel Alexandrov <notifications@github.com> a
écrit :
