### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by Jumblemuddle** [HeapsIO/heaps#225]
Apparently GitHub doesn't support pull requests for wiki repo's.

Here's a git patch of the change:
[diff.txt](https://github.com/HeapsIO/heaps/files/753460/diff.txt)

**Comment by dimumurray** [comment]
You can edit the wiki directly as long as you have a github account.  So have at it!

**Comment by Jumblemuddle** [comment]
@dimumurray Cool, I didn't realize that. :smile:
