### ISSUE TITLE
HTML UI Missing Percentages

### ISSUE THREAD

**Issue by Jumblemuddle** [HeapsIO/heaps#226]
I'm looking through the html parser. It looks like percentages can't be used?
I guess it's expected users will use a static resolution?
Perhaps there's a way to scale a static resolutioin to fill the screen? (Keeping aspect ratio)

This may not be the best place to ask this.

**Comment by ncannasse** [comment]
I have deprecated all work on h2d.comp/css, I will eventually move it outside of heaps only to maintain backward compatiblity with some old apps I have which are using it.

**Comment by Jumblemuddle** [comment]
Ah, that makes sense. Are you migrating to a new ui system, or is that being implemented individually per game?

**Comment by ncannasse** [comment]
We have h2d.Flow that can be used for layout and as a base various UI elements, the game then can have its own UI components
