### ISSUE TITLE
Why pivot is a member of Tile instead of Sprite?

### ISSUE THREAD

**Issue by b005t3r** [HeapsIO/heaps#228]
It's a rather strange design choice to have pivots on textures instead of sprites. How would I now adjust things like the point of rotation with more complex objects or objects which don't use textures? Keeping this as a member of all sprites seems like a much better choice (Starling does it this way and it's awesome: https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/DisplayObject.as#L126-L127).

**Comment by ncannasse** [comment]
That's a matter of habit.

For simply displaying a Bitmap, you would specify the pivot in the tile instead of the Sprite, this allows to create "libraries" of tiles that can be used by different Bitmaps without having to always redefine the pivot. It also allows for changing pivot during frame based animation on a per tile basis.

In order to do complex things such as rotation of compounded objects around a specific center, you would usually add an intermediate Sprite that does the take care of it. It's a lot more rare scenario.

**Comment by b005t3r** [comment]
Come on, it's hardly a matter of habit. Currently there's no common way for this task, like you said, I have to differentiate between textured sprites and not textured ones. I'm not saying that pivot should be removed from Tile, but I can't see why you wouldn't want to add it to Sprite - it just makes so many things so much easier. There even was a similar request: #61 

I think that all frameworks I worked with had it, there's hardly any point in not having something like that.

**Comment by ncannasse** [comment]
What I'm saying is that changing the pivot of complex sprites (i.e. not simple bitmaps) is quite rare, and you can easily do it by doing the following:

```
var mySpr = new Sprite();
var pivot = new Sprite(mySpr);
pivot.x = ...
pivot.y = ...
// add into pivot instead of mySpr
```

And yes, this simplify quite a lot the source code of heaps in many different places dealing with transformations.

**Comment by b005t3r** [comment]
> What I'm saying is that changing the pivot of complex sprites (i.e. not simple bitmaps) is quite rare

What I'm saying is that it is not :) Seriously, I shipped a 2D game last year, made with Starling and AIR and this was something I had to use on a regular basic. I'm not making this up.

> And yes, this simplify quite a lot the source code of heaps in many different places dealing with transformations.

I hardly simplifies anything, look, this is how obtaining a transformation matrix for a given object works with pivot added:

```
                    if(rotation == 0f) {
                        return field.setTo(scaleX, 0f, 0f, scaleY, x - pivotX * scaleX, y - pivotY * scaleY)
                    }
                    else {
                        val cos = MathUtils.cos(rotation)
                        val sin = MathUtils.sin(rotation)
                        val a   = scaleX * cos
                        val b   = scaleX * sin
                        val c   = scaleY * -sin
                        val d   = scaleY * cos
                        val tx  = x - pivotX * a - pivotY * c
                        val ty  = y - pivotX * b - pivotY * d

                        return field.setTo(a, b, c, d, tx, ty)
                    }
``` 

We're talking about a subtraction and a multiplication - how is this a lot? You're even doing a similar thing in your code, but instead of pivot you use tile.dx/tile.dy instead.

What do I have to do to convince you? :)
