### ISSUE TITLE
Docs for new HXSL

### ISSUE THREAD

**Issue by b005t3r** [HeapsIO/heaps#233]
Are there any docs for the heaps version of hxsl? I found something for the old version, but it looks like most of the things has been changed in the current version and they are really not that easy to figure out from the sources.

**Comment by ncannasse** [comment]
HxSL is integrated in Heaps and follows GLSL semantics, but with Haxe syntax.
I'll write some doc about it later, keeping this open until then :)

**Comment by b005t3r** [comment]
Cool, but at least give me some pointers :)

With the previousl hxsl version everything was clear and simple, you'd just call ```bind()``` and everything was set up. How do I do it now?

**Comment by ncannasse** [comment]
If you want to use HxSL independantly from Heaps it's possible but a lot harder.
If you want to use it as part of heaps, you simply have to write your shader which extends hxsl.Shader, then you can add your shader to your material (3D) or Drawable (2D) with addShader.

HxSL3 shaders are "modifiers" than gets linked together at runtime

**Comment by b005t3r** [comment]
I want to use it independently.

Where do I start? I see there's a Driver class (with subclasses for each supported platform), but there's also an Engine class which wraps the Driver?

Could you paste in example code which simply renders some geometry to the screen?

Like in the Stage3D fragment I selected here: https://gist.github.com/noonat/847106#file-cube-as-L133-L201

**Comment by ncannasse** [comment]
It's quite complex then. You will need a list of hxsl.Shader and send them to hxsl.Cache.link(shaders,allocOutputVars(["output.position","ouput.color]))
This will give you a hxsl.Runtimeshader that you can pass to AgalOut as done in h3d/impl/Stage3dDriver

**Comment by b005t3r** [comment]
Can't I just use the Driver implementation to do all of this? I see it's very similar to Context3D. And it looks like I don't need the rest of the Heaps classes except Driver.

**Comment by ncannasse** [comment]
No, one good part is done in the material handling, which then send things
to the driver. That's because we need to sort the materials per shader
before sending them.

**Comment by b005t3r** [comment]
And how about Engine? I need a really basic functionality, no fancy materials :)

Do I need anything more than a shader, Engine instance plus vertex and index buffers? I can't figure out what's the right way of creating buffers.

**Comment by b005t3r** [comment]
OK, I managed to port a minimal Stage3D app to Heaps and it works :)

Would you mind giving it a look and checking if my thinking is right?

https://gist.github.com/b005t3r/0e78699f86da089e81c083333ba33d79

**Comment by ncannasse** [comment]
I have recenlty written a small documentation here https://github.com/HeapsIO/heaps/wiki/HXSL-Introduction
