### ISSUE TITLE
Unable to instantiate LocalFileSystem

### ISSUE THREAD

**Issue by b005t3r** [HeapsIO/heaps#236]
I can't figure it out on my own - how do I create a FileSystem instance? I tried simply calling the constructor for hxd.fs.LocalFileSystem() but because of conditional compilation it creates a dummy instance which crashes with "Please compile with -lib air3". But air3, really? I does sound a bit outdated - am I doing something else wrong?

**Comment by ncannasse** [comment]
If you are on Flash target you need AIR to access the local filesystem. The library which allows AIR API is called "air3".

**Comment by ncannasse** [comment]
Usually you would do  hxd.Res.initLocal() which is a macro that does the necessary setup.

**Comment by b005t3r** [comment]
OK, I added air3 and can confirm it works as expected.
