### ISSUE TITLE
AA is always on for JS builds and can't be turned on in SWF builds

### ISSUE THREAD

**Issue by b005t3r** [HeapsIO/heaps#237]
There's no way to turn off AA for JS builds (which make it unrunnable on mobiles) and there's no way to turn it on for SWF builds.

**Comment by ncannasse** [comment]
According to http://stackoverflow.com/questions/23501703/can-i-programmatically-enable-webgl-antialiasing-on-firefox it's not possible to change WebGL AA settings.
In general, it's better to use software AA such has FXAA, since MSAA cause various problems with modern rendering.

**Comment by b005t3r** [comment]
It should be possible for JS to turn it off: https://developer.mozilla.org/en/docs/Web/API/HTMLCanvasElement/getContext

And it is possible for SWF to turn it on, which also doesn't work, so I don't understand why did you close this issue.

**Comment by b005t3r** [comment]
BTW, even with AA on, why is the JS version so sluggish? Unity WebGL builds work really well on my phone, no problems getting 60 fps, but with Heaps/Haxe I barely get a couple fps with a single rotating cube on the screen. How is this possible?

**Comment by b005t3r** [comment]
I tested on a couple other mobile devices today, Android and iOS. It looks like the JS builds work on iOS with no problems (in Safari), but they work with noticeably worse performance on some Android devices and don't work at all on other Android devices.

Do you want me to create a separate issue for it or can you reopen this one?

**Comment by ncannasse** [comment]
BTW I have fixed AA handling except for HL, I forgot I had support for it in Engine.

**Comment by ncannasse** [comment]
Please open another issue for Android performances issues

**Comment by b005t3r** [comment]
I opened another issue for JS problems. I'll test the AA later this week, thanks for fixing it!
