### ISSUE TITLE
Fonts are not showed correctly in samples when targeting hl

### ISSUE THREAD

**Issue by dkolyesnik** [HeapsIO/heaps#240]
I tried to build samples for hl target, and the fonts are not displaying rightly. 
Here is a screenshot of base2D sample http://prnt.sc/ec6uju
Last version of the heaps, Haxe 3.4.0 
Windows 8.1 64 Intel HD Graphics 4400

**Comment by dkolyesnik** [comment]
Same issue is in Northgard game on same laptop, but it works well on PC.

**Comment by ncannasse** [comment]
Thanks for the report !
Could you try adding in init function  engine.backgroundColor = 0xFF804020;
And change heaps/h3d/mat/Texture.hx NativeFormat to ARGB ? Thanks

Le 23 févr. 2017 06:58, "Dmitriy Kolesnik" <notifications@github.com> a
écrit :

**Comment by dkolyesnik** [comment]
I was building this samples almost two weeks ago, did't reported about it because it was a quick view so I thought that maybe I was doing something wrong, I wanted to try again later. But then I saw same issue in Northgard. Here are screenshots, by the way http://prntscr.com/ecpy0o http://prntscr.com/ecpya0 

I tryed to build base2d again, but it looks like something is changed since the last time. I was either using Haxe 3.4.0.rc2 or updated Heaps after that (using git version), because now when I'm trying to run base2d.hl or any other newly created .hl file from the samples there is an error  (fresh install on PC gives me the same error)
src\module.c(274) : FATAL ERROR : Failed to load function std@sys_locale
But I have an old base2d.hl and I can run it. And it shows the same inconsistent behavior as in case of the game. Some base2d samples  http://prntscr.com/ecq1pa http://prntscr.com/ecq1si http://prntscr.com/ecq1yr

I will test the changes you wrote about, but I don't know what to do with std@sys_locale  error.

**Comment by ncannasse** [comment]
You can comment out hxd.System.get_lang (requires hl GIT)

Le 24 févr. 2017 08:45, "Dmitriy Kolesnik" <notifications@github.com> a
écrit :

**Comment by dkolyesnik** [comment]
Can you give more information, please, I see hxd.System.get_lang in heaps sources but why do I need hl git?

**Comment by dkolyesnik** [comment]
Ok, I downloaded hl from git and installed visual studio so I can rebuild hl now, but I have no idea where to comment

**Comment by ncannasse** [comment]
Sorry, I was not clear, you will find this file in  heaps/hxd/System.hx , you need to comment the @:hlNative declaration. Please note that there are two occurrences of it in the file, replace both to be sure.

The blocks to comment are:

``` haxe
// @:hlNative("std","sys_locale") static function getLocale() : hl.Bytes { return null; }
	static var _lang : String;
	static function get_lang() {
//		if( _lang == null ) {
//			var str = @:privateAccess String.fromUCS2(getLocale());
//			_lang = ~/[.@_-]/g.split(str)[0];
//		}
//		return _lang;
                return "en";
	}
```

**Comment by dkolyesnik** [comment]
Commented these lines, set background color and changed NativeFromat to ARGB in Texture
Got an exception because there are no case for this format in GLDriver.
```
Unsupported texture format ARGB

Called from h3d.impl.GlDriver.allocTexture (h3d/impl/GlDriver.hx line 607)
Called from h3d.impl.MemoryManager.allocTexture (h3d/impl/MemoryManager.hx line 254)
Called from h3d.mat.Texture.alloc (h3d/mat/Texture.hx line 102)
Called from module fun$3189(hxd/res/Image.hx:207)
Called from hxd.res.Image.loadTexture (hxd/res/Image.hx line 217)
Called from hxd.res.Image.toTexture (hxd/res/Image.hx line 259)
Called from hxd.res.Image.toTile (hxd/res/Image.hx line 265)
Called from Base2D.init (Base2D.hx line 15)
Called from module fun$1495(hxd/App.hx:68)
Called from hxd.App.loadAssets (hxd/App.hx line 84)
Called from hxd.App.setup (hxd/App.hx line 66)
Called from h3d.Engine.onCreate (h3d/Engine.hx line 220)
Called from module fun$2440(h3d/impl/GlDriver.hx:1042)
Called from module fun$2686(C:\HaxeToolkit\haxe\std/haxe/Timer.hx:140)
Called from module fun$2687(C:\HaxeToolkit\haxe\std/haxe/Timer.hx:74)
Called from haxe.$MainLoop.tick (C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx line 156)
Called from haxe.$EntryPoint.processEvents (haxe/EntryPoint.hx line 70)
Called from module fun$2682(haxe/EntryPoint.hx:74)
Called from sdl.$Sdl.loop (sdl/Sdl.hx line 57)
Called from sdl.$Sdl.loop (sdl/Sdl.hx line 56)
Called from haxe.$EntryPoint.run (haxe/EntryPoint.hx line 74)
```
Added empty ARGB case to GIDriver and after that fonts are displayed rightly, but there are still issues with colors and inconsistent behavior. Sometime it doesn't show text at all, sometimes only text.
http://prntscr.com/ecrziz  http://prntscr.com/ecrzo4

**Comment by ncannasse** [comment]
Yes something is very strange here. Seems related to texture mode. In this screen for instance:
http://prnt.sc/ecrziz

The font should be white and have a drop shadow, but the alpha channel and red channels are swapped

Our current GL driver uses RGBA so it seems either your intel backbuffer or the texture mode is initialized as BGRA (?) instead.

Let me look into it I'll try to give you some things to check

**Comment by ncannasse** [comment]
Ok, could you try with the following:

In GlDriver.hx, in the case BGRA, add the following:


case BGRA:
   tt.internalFmt = 0x8058/*GL.RGBA8*/;


and in getChannels (the function a bit before that):

case 0x8058: 0x80E1/*GL.BGRA*/;

Tell how that works

**Comment by dkolyesnik** [comment]
Just in case, is this a comment or what /GL.RGBA8/  ?
added
 tt.internalFmt = 0x8058; 
and so on
Changed nativeFormat to BGRA
result is the same as in the first case http://prntscr.com/ectuwu
Fonts are not readable again.
For now they where readable only in case of ARGB nativeFormat 
my skype is ulfserk http://prntscr.com/ectxgm 
I think it would be easier to show you the screen and do this experiments in real time. So feel free to write me.

**Comment by ncannasse** [comment]
Followup : Intel HD graphics have many issues with OpenGL, we have switched to using DirectX (-lib hldx) which works a lot better there.
