### ISSUE TITLE
hxd.impl.PathFind error on JS

### ISSUE THREAD

**Issue by R32** [HeapsIO/heaps#246]
The following code works on flash and hl
```haxe
class App {
  static function main() {
    var p = new hxd.impl.PathFind(5, 5);
    p.build(2, 2, function(x, y) { return false; } );
    trace(@:privateAccess p.t); // js output: [, , , , , ...]
  }
}
```
then i found this issue is cause by [hxd/impl/PathFind.hx#L35](https://github.com/HeapsIO/heaps/blob/master/hxd/impl/PathFind.hx#L35)

```haxe
var p = t[a];                // on js, p value may be undefined
if( p != 0 ) return false;   // undefined != 0 is true
```
and  i can't find the most appropriate way to fix it

**Comment by ncannasse** [comment]
I think that having the following should work: 
```haxe
static inline var DEF_INT : Int = #if js null #else 0 #end;
```
Then use DEF_INT instead of 0 in all checks in PathFind.hx
Could you submit a PR ?

**Comment by R32** [comment]
If so, what to do with `PathFind::clear`

```haxe
public function clear() {
	for( i in 0...width * height )
		t[i] = 0;
}
```

**Comment by ncannasse** [comment]
Ah, maybe then a simpler version would be #if js clear() #end in PathFind.new
