### ISSUE TITLE
Android Back Button

### ISSUE THREAD

**Issue by Jumblemuddle** [HeapsIO/heaps#248]
Trying to find a way to capture the Android back button for moving through pages in my game. (And exiting if on the first page)

I've tried implementing the solution here: http://www.openfl.org/archive/community/bugs/openfl-android-back-button/ without any luck.

I'll hopefully have time in the future to reassess this.

**Comment by ncannasse** [comment]
Lime is not officially supported, please submit a PR if you wish to see it fixed.
