### ISSUE TITLE
Openfl 4.9.0 and Lime 4.0.0

### ISSUE THREAD

**Issue by Jumblemuddle** [HeapsIO/heaps#249]
Openfl (and Lime) have been updated: https://github.com/openfl/openfl/blob/develop/CHANGELOG.md

Here's the output of a simple build:

    haxelib/lime/4,0,0/lime/_backend/native/NativeGLRenderContext.hx:1901: characters 124-145 : Warning : This pattern is unused
    haxelib/lime/4,0,0/lime/_backend/native/NativeGLRenderContext.hx:1901: characters 124-145 : Warning : This pattern is unused
    heaps/h3d/impl/GlDriver.hx:344: characters 29-30 : lime.utils.Float32Array should be Int
    heaps/h3d/impl/GlDriver.hx:344: characters 29-30 : For function argument 'count'
    heaps/h3d/impl/GlDriver.hx:355: characters 28-29 : lime.utils.Float32Array should be Int
    heaps/h3d/impl/GlDriver.hx:355: characters 28-29 : For function argument 'count'
    heaps/h3d/impl/GlDriver.hx:543: characters 3-16 : Class<lime.graphics.opengl.GL> has no field clearDepth (Suggestion: clearDepthf)
    heaps/h3d/impl/GlDriver.hx:663: characters 106-110 : On static platforms, null can't be used as basic type lime.utils.DataPointer
    heaps/h3d/impl/GlDriver.hx:670: characters 96-100 : On static platforms, null can't be used as basic type lime.utils.DataPointer
    heaps/h3d/impl/GlDriver.hx:718: characters 33-36 : lime.utils.UInt8Array should be Int
    heaps/h3d/impl/GlDriver.hx:718: characters 33-36 : For function argument 'size'
    heaps/h3d/impl/GlDriver.hx:738: characters 41-44 : lime.utils.UInt16Array should be Int
    heaps/h3d/impl/GlDriver.hx:738: characters 41-44 : For function argument 'size'
    heaps/h3d/impl/GlDriver.hx:881: characters 62-65 : lime.utils.Float32Array should be Int
    heaps/h3d/impl/GlDriver.hx:881: characters 62-65 : For function argument 'size'
    heaps/h3d/impl/GlDriver.hx:894: characters 62-65 : lime.utils.UInt8Array should be Int
    heaps/h3d/impl/GlDriver.hx:894: characters 62-65 : For function argument 'size'
    heaps/h3d/impl/GlDriver.hx:907: characters 61-64 : lime.utils.UInt16Array should be Int
    heaps/h3d/impl/GlDriver.hx:907: characters 61-64 : For function argument 'size'
    heaps/h3d/impl/GlDriver.hx:920: characters 61-64 : lime.utils.UInt8Array should be Int
    heaps/h3d/impl/GlDriver.hx:920: characters 61-64 : For function argument 'size'
    heaps/hxd/impl/LimeStage.hx:297: characters 3-27 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:298: characters 3-33 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:299: characters 3-25 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:301: characters 3-29 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:302: characters 3-27 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:303: characters 3-27 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:304: characters 3-23 : Warning : This case is unused
    heaps/hxd/impl/LimeStage.hx:320: characters 3-35 : Warning : This case is unused

This was build with the temporary fix described in #243: https://github.com/Jumblemuddle/heaps/commit/f8d3913ccd4a44d7b56a5aee0707835ee968c317.
The changes described here and the changes required to update to 4.0.0 will likely overlap and result in a single update.

This should be helpful in updating: http://www.openfl.org/blog/2017/03/15/using-the-improved-opengl-bindings-in-lime-4/.

**Comment by fidgetwidget** [comment]
why not create a pull request if you've come up with a fix?

**Comment by Jumblemuddle** [comment]
I had little to no familiarity with the problem when I made this fix. It seemed to work, though I was fairly sure it wasn't actually done in the way it should be done.

**Comment by ncannasse** [comment]
Lime is not officially supported, please submit a PR if you wish to see it fixed.
