### ISSUE TITLE
Building App For HashLink

### ISSUE THREAD

**Issue by Jumblemuddle** [HeapsIO/heaps#255]
Error:
`File "src/generators/genhl.ml", line 557, characters 30-36: Assertion failed`

hl.hxml:
```
-hl out/main.hl
-cp src
-lib hlsdl
-lib heaps
-main game.Main
-D windowSize=1024x768
```

Any ideas?

**Comment by ncannasse** [comment]
Wich haxe/hl versions are you using?

**Comment by Jumblemuddle** [comment]
`haxe -version`
`3.4.2`
`hl -v`
```
HL/JIT 1.2.0 (c)2015-2017 Haxe Foundation
  Usage : hl [--debug <port>] <file>
```

Haxe was build from the latest release of haxe, and hl was build from the latest git.

**Comment by ncannasse** [comment]
That's normal, they are not compatible. If you want to use latest HL GIT you need latest Haxe GIT as well.
