### ISSUE TITLE
Does it support fallback to canvas if webGL not available ?

### ISSUE THREAD

**Issue by cuongngosa** [HeapsIO/heaps#264]

**Comment by ncannasse** [comment]
Heaps is shader based so it does not support canvas.

**Comment by cuongngosa** [comment]
Thanks, would u pls suggest or ref link that I need to make supporting fallback html5 canvas?

**Comment by ncannasse** [comment]
there's no ref link, you would have to reimplement the whole GPU API to work it work, I don't think anyone have done this
