### ISSUE TITLE
Sample how to use BigPrimitive

### ISSUE THREAD

**Issue by Grabli66** [HeapsIO/heaps#268]
I tried to do it myself but failed. I want to create a grid from cubes. 
I started from this simple code. But nothing shows on screen.
And i dont understand how to add normals and uvs.

import h3d.prim.Cube;
import h3d.prim.BigPrimitive;
import h3d.scene.Mesh;

class TestApp extends hxd.App {

    override function init() {
        var big = new BigPrimitive(3);
        var cube = new Cube (1, 1, 1);        
        
        big.begin (cube.vertexCount (), cube.idx.length);
        var buff = new hxd.FloatBuffer ();
        for (p in cube.points) {
            buff.push (p.x);
            buff.push (p.y);
            buff.push (p.z);
        }

        big.add (buff, cube.idx);
        big.add (buff, cube.idx, 1, 0);
        big.add (buff, cube.idx, 2, 0);

        var mesh = new h3d.scene.Mesh (big, s3d);        

        mesh.material.color.setColor (0xFF3300);
        var dir = new h3d.scene.DirLight(new h3d.Vector(0.2, 0.3, -1), s3d);        
        dir.color.set(0.15, 0.15, 0.15);

        s3d.camera.zNear = 6;
        s3d.camera.zFar = 30;
        s3d.camera.pos.set (4.0, 8.0, 20);
        s3d.camera.target.set (4.0, 3, 0);
       
        new h3d.scene.CameraController (s3d).loadFromCamera ();
    }
}

class Main {

    static function main() {
        new TestApp ();
    }
}

**Comment by ncannasse** [comment]
Most likely you're missing normals. You should get an error in the console if you're running in WebGL.
