### ISSUE TITLE
Interactive ray execute two times modelspace transform

### ISSUE THREAD

**Issue by EverySteps** [HeapsIO/heaps#269]
hello ncannasse:
 look at the Interactive samples, if i change the interactive object parent m instead of s3d, i can't get correct pick.
i found the modelspace transform execute two times.
first at: h3d/scene/Scene.hx 110 line   r.transform(minv);
second at: h3d/col/ObjectCollider.hx 16 line r.transform(obj.getInvPos());
other Collider class has same transform.

**Comment by ncannasse** [comment]
That's actually an interesting API design consideration.

We currently have two types of collider: ObjectCollider is an "absolute"
collider, which requires a world space ray
But you cab also initialize an Interactive with a relative collider such as
h3d.col.Bounds or Sphere, which is then relative to the interactive
position and hierarchy.
I guess it might be necessary to distinguish between these two collider
types if we want both of them to work together.

**Comment by ncannasse** [comment]
The new collider API allows to query both local and global colliders, and you will soon be able to set ignoreParentTransform=true on the Interactive so it's position is world space instead of local space while still being a children of the object.
