### ISSUE TITLE
Does not work skin example (js target)

### ISSUE THREAD

**Issue by Grabli66** [HeapsIO/heaps#272]
Tested on latest heaps and hxbit from git. 
I get an error in browser log: "uncaught exception: Error: Unknown property #156"
I think this error raised in hxd.fmt.hmd.Reader.hx in readProperty function. But don't know why.

**Comment by ncannasse** [comment]
Just tested again on Chrome/Windows and I don't have such issue.  On which browser are you testing ?

**Comment by Grabli66** [comment]
Windows
Firefox 54.0.1
Chrome 59.0.3071.115

Error from chrome:
Uncaught js__$Boot_HaxeErrormessage: "Unknown property #156"val: "Unknown property #156"stack: "Error: Unknown property #156↵    at hxd_fmt_hmd_Reader.readProperty (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:43450:10)↵    at hxd_fmt_hmd_Reader.readProps (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:43466:17)↵    at hxd_fmt_hmd_Reader.readHeader (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:43635:20)↵    at hxd_res_Model.toHmd (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:45448:70)↵    at h3d_prim_ModelCache.loadLibrary (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:28204:14)↵    at h3d_prim_ModelCache.loadModel (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:28220:19)↵    at Skin.init (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:510:24)↵    at file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:340:11↵    at Skin.loadAssets (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:354:3)↵    at Skin.setup (file:///C:/HaxeToolkit/haxe/lib/heaps/git/samples/build/skin/skin.js:338:8)"__proto__: Error

**Comment by ncannasse** [comment]
I have no idea what's going wrong here, seems like your HMD file cannot be correctly read in JS. Maybe a problem with default html page encoding.

**Comment by Grabli66** [comment]
I tried to change charset of html file, and hmd file, and skin.js file. But no change.
Ok. I'll try to investigate that problem by myself.

**Comment by Grabli66** [comment]
The problem does not appear on the current version of heaps
