### ISSUE TITLE
Error while compile skin_js.hxml

### ISSUE THREAD

**Issue by Grabli66** [HeapsIO/heaps#273]
I use latest haxe (2017-07-18 build) and latest heaps on Windows.

C:\HaxeToolkit\haxe\lib\heaps/git/hxd/Res.hx:15: characters 52-96 : Uncaught exception Unexpected value VNull(null), expected string
c:\haxetoolkit\haxe\lib\heaps\git\hxd\fs\localfilesystem.hx:379: characters 4-14 : Called from here
c:\haxetoolkit\haxe\lib\heaps\git\hxd\fs\localfilesystem.hx:392: characters 11-21 : Called from here
c:\haxetoolkit\haxe\lib\heaps\git\hxd\res\filetree.hx:124: characters 11-36 : Called from here
c:\haxetoolkit\haxe\lib\heaps\git\hxd\res\filetree.hx:106: characters 9-55 : Called from here
c:\haxetoolkit\haxe\lib\heaps\git\hxd\res\filetree.hx:84: characters 19-34 : Called from here
c:\haxetoolkit\haxe\lib\heaps\git\hxd\fs\embedfilesystem.hx:268: characters 14-30 : Called from here
For function argument 'fs'
../../Skin.hx:37: characters 3-22 : Called from macro here

When use haxe 3.4.2 release, there is other error:

C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/LocalFileSystem.hx:318: characters 16-45 : Invalid field access : split
<builtin>:1: character 0 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/LocalFileSystem.hx:297: lines 297-327 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/res/FileTree.hx:77: characters 11-48 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/EmbedFileSystem.hx:268: characters 13-29 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/Res.hx:15: characters 51-95 : Called from
Aborted

**Comment by Grabli66** [comment]
I found that if use latest heaps and haxe 3.4.2, the code in LocalFileSystem constructor:
var exePath = Sys.programPath().split("\\").join("/").split("/");
not works, cause Sys.programPath() returns null.

Also code in "convert" function, in LocalFileSystem:
for( p in new haxe.io.Path(path).dir.split("/") )
not works, cause path variable is a file name and dir field returns null

**Comment by codebee-fr** [comment]
Hi,

I start with haxe 3.4.2 (last build) and heaps (last git) and I also have the same error.

C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/LocalFileSystem.hx:318: characters 16-45 : Invalid field access : split
<builtin>:1: character 0 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/LocalFileSystem.hx:297: lines 297-307 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/res/FileTree.hx:77: characters 11-48 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/fs/EmbedFileSystem.hx:268: characters 13-29 : Called from
C:\HaxeToolkit\haxe\lib\heaps/git/hxd/Res.hx:15: characters 51-95 : Called from
Aborted
Build halted with errors (haxe.exe).
