### ISSUE TITLE
Feature request. Better blender support

### ISSUE THREAD

**Issue by Grabli66** [HeapsIO/heaps#274]
Now if you want export model and animation from blender, you need export data from blender in fbx binary format, and then convert it to fbx ascii format. Then praying, that all are exported as you want. Very often skeletal animation is broken, if you export that way.
I think it's need addon for blender, that exports model and animation to heaps HMD format in right way.

**Comment by ncannasse** [comment]
While it's a good thing I don't have plans to work on this for now so i'm closing until someone submit an actual pull request :)
