### ISSUE TITLE
How can I have a "tight" 320x240 resolution that stretches with the browser window?

### ISSUE THREAD

**Issue by topitsky** [HeapsIO/heaps#275]
I've tried setting the scene fixed size but with that the aspect ratio doesn't work. Things end up looking fat. Any cool trick to achieve this effect?

**Comment by ncannasse** [comment]
You need to resize the canvas manually using Javascript API + use setFixedSize(320,240). If you are using pixel art make sure your canvas size is a multiple of 320x240 not to blur your pixels.
