### ISSUE TITLE
Class<flash.ui.Keyboard> has no field BACK

### ISSUE THREAD

**Issue by leocavalcante** [HeapsIO/heaps#278]
`C:/HaxeToolkit/haxe/lib/heaps/0,9,0/hxd/Stage.hx:299: characters 19-41 : Class<flash.ui.Keyboard> has no field BACK`

| S | V |
| --- | --- |
| Lime | 5.4.0 |
| OpenFl | 6.1.0 |
| Heaps | 0.9.0 |

**Comment by ncannasse** [comment]
Lime is not officially supported, please submit a PR if you wish to see it fixed.
