### ISSUE TITLE
hashlink compilation in a bad state

### ISSUE THREAD

**Issue by FireSlash** [HeapsIO/heaps#282]
Under 4.0 preview (with the 4.0 compatible hashlink), SDL doesn't compile. If compilation errors are stubbed out, it will compile but the provided lib in the hlsdl library appears to be out of sync and fails to run with `src\module.c(280) : FATAL ERROR : Invalid signature for function sdl@win_create : PBii_Xsdl_window_ required but Pii_Xsdl_window_ found in hdll`

As far as I can tell, there is no hldx library available.

I also had no luck on 3.4 with the appropriate hashlink version, which produced a longer list of compile errors than under 4.0; however I didn't attempt to repair these to test whether the build would have ran.

**Comment by starburst997** [comment]
Seems fine here, haxe 4 (although I'm only playing with the basic samples atm). Have you try grabbing all latest lib version from github and for hlsdl / hldx to use the folder include inside the hashlink project, `haxelib dev hlsdl hashlink/libs/sdl` ?

**Comment by FireSlash** [comment]
Ah, I missed those, since they weren't in the dist (and there weren't any installation directions that I could see.)

Closing this as operator error.
