### ISSUE TITLE
Alpha reset on sprite with Blur filter created out of screen

### ISSUE THREAD

**Issue by benjaminsoule** [HeapsIO/heaps#288]
for ( i in 0...9 ){
	var a = new EL();
	a.x = 2000 + (i % 3) * 80;
	a.y = 2000 + Std.int(i / 3) * 80;
	a.tile = h2d.Tile.fromColor(0xFF0000,64,64);
	a.alpha = .5;
	a.filters = [ new h2d.filter.Blur(1, 32, 1) ];
	s2d.add(a, 10);
	function f(){
		a.x -= 2000;
		a.y -= 2000;
	}
	haxe.Timer.delay(f, 200);
}

**Comment by ncannasse** [comment]
I think this has been fixed for some time now :)
