### ISSUE TITLE
Drawing 2d Meshes

### ISSUE THREAD

**Issue by jeremyfa** [HeapsIO/heaps#294]
This is not really an issue but more a question (please tell me if this is not the right place to ask).

What is the recommended way in Heaps to draw 2d meshes, given that we have a set of vertex array, indices and uvs to draw at each frame?

(the use case about is drawing mesh-based Spine animations, with data provided by a Spine runtime at each frame)

My current guess is that I should just draw and update a 3d mesh (with h3d.Mesh) with z values set to 0, but maybe there is another option?

**Comment by ncannasse** [comment]
You can use h2d.Graphics with beginTileFill, but you cannot deform the UVs
unless you subclass it to allow to directly inject your own.

**Comment by jeremyfa** [comment]
Being able to deform the uv is a requirement, so I a Graphics subclass is an option. Thanks for the hints!
