### ISSUE TITLE
App.init called twice when creating custom engine

### ISSUE THREAD

**Issue by elnabo** [HeapsIO/heaps#295]
Creating a custom engine in the constructor, will results in App.init to be called twice.

```haxe
class Test extends hxd.App {
	
	public function new () {
		new h3d.Engine(true, 1).init();
		super();
	}

	override function init() {
		trace("init");
	}

	static function main() {
		new Test();
	}
}
```

Edit:

Commenting the timer in App constructor (https://github.com/HeapsIO/heaps/blob/master/hxd/App.hx#L18) seems to fix the problem.

**Comment by ncannasse** [comment]
If you want to do that, you might just wait for your custom Engine to trigger onReady, then create your Test App which will use the current engine.
