### ISSUE TITLE
Getting events out of hxd.Pad

### ISSUE THREAD

**Issue by Simn** [HeapsIO/heaps#296]
There doesn't seem to be a way to get button press/release out of hxd.Pad, which I find a bit limiting. Do you think we could add some callback functions which are invoked by _setButton/_setAxis? Or am I missing a more obvious way to use this class altogether?

**Comment by ncannasse** [comment]
You can use `pad.isPressed(button)` to detect if the button has been pressed this frame. (while `isDown` check if the button is currently pushed). I have just pushed `isReleased`
