### ISSUE TITLE
Cannot compile samples with HashLink

### ISSUE THREAD

**Issue by riseremi** [HeapsIO/heaps#310]
Hello, thank you for the project. I'm completely new to haxe and heaps.

I can successfully compile any sample to JavaScript and run it in my browser. However, compilation with HashLink target fails.

I'm trying to compile `base2D` sample here. Build logs:

```shell
$ haxe -lib hlsdl base2D_hl.hxml
C:\HaxeToolkit\haxe\lib\hlsdl/1,2,0/sdl/Sdl.hx:39: characters 2-16 : hl.Sentinel has no field pause (Suggestion: _pause)
C:\HaxeToolkit\haxe\lib\heaps/1,0,0/hxd/System.hl.hx:223: characters 10-32 : hl.Sentinel has no field pause (Suggestion: _pause)
C:\HaxeToolkit\haxe\lib\heaps/1,0,0/hxd/System.hl.hx:233: characters 9-31 : hl.Sentinel has no field pause (Suggestion: _pause)
```

**Versions**
OS: Windows 10 (also reproduces on macOS 10.11)
Heaps: 1.0.0 (latest from `haxelib install heaps`)
Haxe: 3.4.4 (latest binary from haxe.org)
HashLink: 1.3.0 (latest binary from [github releases](https://github.com/HaxeFoundation/hashlink/releases/tag/1.3))
Haxelib: 3.3.0 (comes with Haxe)

**`haxelib list` output**
```
$ haxelib list
format: [3.3.0]
heaps: [1.0.0]
hlopenal: [1.0.0]
hlsdl: [1.2.0]
hscript: [2.1.1]
```

**Comment by ncannasse** [comment]
Yes it's a bit hard to maintain both 3.x and Haxe 4.0+ versions. In the meanwhile, you can simply the following to haxe/std/hl/UI.hx (in abstract Sentinel declaration):

```haxe
	public var pause(get,set) : Bool;
	function get_pause() {
		return false;
	}
	function set_pause( p : Bool ) {
		return false;
	}
```

**Comment by riseremi** [comment]
Thank you!
I do not have any projects yet so I can use the most recent version. Which haxe version is supposed to work with heaps out of the box?

Tried with Haxe 4.0.0-preview.2, but it fails too:
```shell
$ haxe -lib hlsdl world_hl.hxml
C:\HaxeToolkit\haxe\lib\heaps/1,0,0/hxsl/Eval.hx:115: characters 36-41 : Unexpected final
```

**Comment by riseremi** [comment]
I've found an answer, closing.
Working setup is `heaps 1.0.0` + `haxe 4.0.0-preview.1` and `hashlink 1.2`.
