### ISSUE TITLE
sceneobj 2 render   any possibility drawcall  ? 

### ISSUE THREAD

**Issue by longde123** [HeapsIO/heaps#329]
sceneobj  dont  has draw()  separate / render pipeline
 architecture   like this
       
render  addobj(sceneobj)
   createorget groudpass by sceneobj.mtl
    for(pass in groudpass )
      create_drawcall_and_binddata (sceneobj .data)
      
render  draw()
for pass in groudpass 
    for drawcall in pass
 drawcall.apply(ctx)  //no sceneobj.draw()

render       create_drawcall_and_binddata (sceneobj .data)

drawcall bind
  geo 
 tex
 shader
 att
 ....

**Comment by ncannasse** [comment]
I am not sure exactly what you mean here. Yes, the actual draw() is performed by the object itself, after it has emit one or several passes. So you can entirely control the passes ordering and setup by using a custom h3d.scene.Renderer, but you can't change the way it's drawn, I'm not sure how this would be useful?

**Comment by longde123** [comment]
i wan  Multi-threaded rendering
actual draw() is performed by the object itself, cant do this, no separate / render pipeline

**Comment by longde123** [comment]
1PassGroup ,
2Pass  , 
3DrawCallObj[bind <->
                  sceneobj.geo[indexBuffer,vertexBuffer]
                 sceneobj.tex[]
                 sceneobj.shader
                 sceneobj.shader_att[vsConstants[came,light ,ani .....],fsConstants]
]

**Comment by longde123** [comment]
scene_obj is tree update i want DrawCallObj list update

**Comment by longde123** [comment]
package h3d.pass;

class Object {
	public var pass : h3d.mat.Pass;
	public var obj : h3d.scene.Object;  -->this can bind and repalce DrawCallObj 
	public var index : Int;
	public var next : Object;
	public var nextAlloc : Object;

	// cache
	public var shaders : hxsl.ShaderList;
	public var shader : hxsl.RuntimeShader;
	public var depth : Float;
	public var texture : Int = 0;

	public function new() {
	}
}

**Comment by longde123** [comment]
I am sorry my poor  English

**Comment by longde123** [comment]
DrawCallObj is sceneobj  Ctx Performed and Data Consumer

**Comment by longde123** [comment]
do this will a result of a lot of api change
I can't change it

**Comment by ncannasse** [comment]
I get the idea but that would be a complex change to do, for now I prefer to keep it as it.
