### ISSUE TITLE
Travis bug

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#334]
I don't understand the Travis errors, looks like it's mixing an older version of h3d.scene.Renderer with a new version of h3d.scene.DefaultRenderer

ping @markknol @andyli

**Comment by azrafe7** [comment]
Maybe I know why that's happening, Travis is installing heaps 1.1.0 with `haxelib install all.hxml` and then launching a compilation within the current branch folder, thus mixing up the declarations.

**Comment by ncannasse** [comment]
@markknol @andyli ?

**Comment by andyli** [comment]
Where is the log? This repo's TravisCI isn't enabled at all...

**Comment by ncannasse** [comment]
https://travis-ci.org/HeapsIO/heaps/builds/334949785?utm_source=email&utm_medium=notification

**Comment by ncannasse** [comment]
It's good now.
