### ISSUE TITLE
SampleApp is broken due to Scene Serialization changes.

### ISSUE THREAD

**Issue by nanjizal** [HeapsIO/heaps#337]
Type not found : h3d.impl.Serializable
line 15 is SampleApp.hx
```haxe
			var bytes = new h3d.impl.Serializable.SceneSerializer().saveHSD(s3d,false);
			hxd.File.saveBytes("scene.hsd", bytes);
```
I think it probably needs to be changed to something like 
```haxe
scene.serializeScene();
```
but the sample will probably need some further changes to run.

**Comment by ncannasse** [comment]
Uhm this was fixed some time ago already https://github.com/HeapsIO/heaps/commit/0e3daeef1821da21c8030bbab95a085a3fd9023a
