### ISSUE TITLE
Font glyphs vertical alignment

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#367]
NG Title fonts are slightly offset in Y compared to their top-left corner, maybe because we should align the glyphs based on the lower letters (gj etc.). This is something that needs study/fix.

**Comment by Yanrishatum** [comment]
Is it still relevant? Since Heaps now supports better BMF format that provides font baseline among other things. There's not much point in improving clearly inferior format, especially since manual already extensively covers font file generation and advises against using Divo.

**Comment by ncannasse** [comment]
I think it is relevant. Your font tool still has the same baseline guess wrong I think ? Correct me if I'm wrong.

**Comment by Yanrishatum** [comment]
No, it does not.
For fonts in BMF format, baseline is already provided by the generator, and code that does guessing kicks in only if `baseLine == 0`, which happens only on Divo format or fonts that for whatever reason have baseline configured incorrectly.
See `common.base` in bmf spec: https://www.angelcode.com/products/bmfont/doc/file_format.html
Same goes for fontgen - it uses baseline value provided by the font file and stores it in the bmf:
https://github.com/Yanrishatum/fontgen/blob/master/native/msdfgen_lib.cpp#L92

**Comment by ncannasse** [comment]
Thanks for the precision, closing.
