### ISSUE TITLE
You cannot access the flash package while in a macro (for flash.display.BitmapData)

### ISSUE THREAD

**Issue by YongGame** [HeapsIO/heaps#368]
hello 
i use haxedevelop create openfl project  and set target flash, i just add hxd.Res.initEmbed(); in the Main.hx construction method. when i compier the program, output message:

libs/heaps/hxd/fs/LoadedBitmap.hx:4: characters 28-52 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
libs/heaps/hxd/fs/FileEntry.hx:29: characters 41-53 :     referenced here

i check the source code,  i found  hxd.Res.initEmbed(); 
call  FileTree.hx var fs = new hxd.fs.LocalFileSystem(this.path);
LocalFileSystem.hx has  FileEntry.hx statement  and FileEntry.hx  has LoadedBitmap.hx statement  .

my develop environment:
openfl 3.3.6
lime 2.6.6
format 3.4.0
heaps latest version

is heaps no longer supported flash platform hxd.Res.initEmbed() resources ?

**Comment by ncannasse** [comment]
Lime is not officially supported for Heaps.
