### ISSUE TITLE
String comparison issue in SharedShader

### ISSUE THREAD

**Issue by hoseyjoe** [HeapsIO/heaps#379]
While attempting to test HL GIT (1.6) I keep getting "Invalid char  at position 0"

Turns out that occurs because in SharedShader.hx line 49ish
if( src == "" )
is not working. For it to work I had to change it to
if( src == "" || src.length==0 )

I would assume the former would work so his suggests to me a deeper issue?

**Comment by ncannasse** [comment]
That's very weird indeed, never had this issue.
Could you trace the following ?

```haxe
trace(src, src.length, "#"+src+"#", untyped src.bytes.getUI16(0));
var empty = "";
trace(empty, empty.length, "#"+empty+"#", untyped empty.bytes.getUI16(0));
```

**Comment by ncannasse** [comment]
Ok, next step is to manually call `trace(untyped src.__compare(""))` , then if false, look at what the String.__compare function is doing and why it's failing.

**Comment by hoseyjoe** [comment]
trace(untyped src.__compare(""))
returned
hxsl/SharedShader.hx:54: 0

So I adjusted compare like
@:keep function __compare( s : String ) : Int {
		trace(s);
		trace(s.bytes +","+ (length < s.length ) +"="+ length +" or "+s.length +" equals "+((length < s.length ? length : s.length) << 1))
		var v = bytes.compare(0, s.bytes, 0, (length < s.length ? length : s.length) << 1);
		trace(v);
		trace(v == 0 ? length - s.length : v);
		return v == 0 ? length - s.length : v;
}
and got

String.hx:186: 
String.hx:187: ,false=0 or 0 equals 0
String.hx:189: 0
String.hx:190: 0

**Comment by ncannasse** [comment]
Ok, problem solved. You're using HL 1.6 but not Haxe GIT, replace the __compare function with the following:

```haxe
	@:keep function __compare( v : Dynamic ) : Int {
		var s = Std.instance(v, String);
		if( s == null )
			return hl.Api.comparePointer(this, v);
		var v = bytes.compare(0, s.bytes, 0, (length < s.length ? length : s.length) << 1);
		return v == 0 ? length - s.length : v;
	}
```

Since the signature has changed, the previous one is not detected as valid.

**Comment by hoseyjoe** [comment]
Thanks Nicolas.  I was using a nightly (3018ab109) but perhaps not new enough. Anyways confirmed with b3a6dc182
