### ISSUE TITLE
h3d.mat.Texture resize calls dispose?

### ISSUE THREAD

**Issue by hoseyjoe** [HeapsIO/heaps#380]
I was attempting to resize a texture and was getting nothing displayed.  I commented out dispose to make ti work.  Not sure if this is needed?
public function resize(width, height) {
		//dispose();

		var tw = 1, th = 1;
		while( tw < width ) tw <<= 1;
		while( th < height ) th <<= 1;
		if( tw != width || th != height )
			this.flags.set(IsNPOT);
		else
			this.flags.unset(IsNPOT);

		this.width = width;
		this.height = height;

		if( !flags.has(NoAlloc) )
			alloc();
	}

**Comment by ncannasse** [comment]
Hi, yes it is necessary to dispose the texture before allocating a new one. However this function will increase the texture size, it will not scale the existing content that will require to be uploaded again.
