### ISSUE TITLE
Apple Metal Support

### ISSUE THREAD

**Issue by thejustinwalsh** [HeapsIO/heaps#384]
OpenGL is officially deprecated in macOS 10.14 (Mojave)

**Comment by starburst997** [comment]
And iOS

**Comment by ncannasse** [comment]
It's "just" deprecated, in the sense you'll still be able to use OpenGL on these platforms, just that Apple doesn't have long term plan to keep supporting it.

Regarding Heaps, OpenGL Driver should keep working for the next few years. We will had support for Vulkan support at some point which will also enable Metal and DX12 support thanks to MoltenVK (https://github.com/KhronosGroup/MoltenVK)
