### ISSUE TITLE
HashLink 1.6.0 and Haxe 4.0.0 preview.4 Upgrade Errors

### ISSUE THREAD

**Issue by Doppp** [HeapsIO/heaps#393]
Upgraded HashLink to 1.6.0 and Haxe to 4.0.0 preview.4. My app was working prior to the upgrade but now I get this error.

![code_2018-06-29_01-56-06](https://user-images.githubusercontent.com/627410/42051807-99d7e8a6-7b3f-11e8-96f5-b5d023bdbff1.png)

Tried to run the Base2D basic sample from Heaps folder. I can run `haxe gen.hxml` but when run the compiled `base2D.hl` file I get this error.

![2018-06-29_01-57-50](https://user-images.githubusercontent.com/627410/42051981-1cc0c6fc-7b40-11e8-8f79-cdb4ed258f79.png)

**Comment by ncannasse** [comment]
@Doppp you need to update Heaps to latest GIT if you are using Haxe 4.0-preview
Maybe that will help with the other error as well, as I have no idea where it comes from.
