### ISSUE TITLE
HashLink Unsupported bytecode version 1

### ISSUE THREAD

**Issue by Hevedy** [HeapsIO/heaps#397]
Every time I try to final create the files for the HashLink VM from the samples included it returns this error "Unsupported bytecode version" and says is the version VER=1

Using bat files on different folders to generate the files and content as checked in the docs don't work or missed something:

To build all the samples
"haxe gen.hxml"
then go to build folder and choose for example the pbr example
"haxe -lib hlsdl pbr_hl.hxml"
all is fine until here, now the problem is at all the hl
"hl-1.6.0-win\hl pbr.hl"
this one return the problem, got the hl in that folder as say nowhere how to setup it on windows, so just downloaded it and placed the folder in there for a quick test.

I'm missing something ?

Note using the HL 1.6.0 with Haxe 3.4.7 on Windows 7 64

**Comment by ncannasse** [comment]
You are compiling with an old haxe. HL 1.6 require Haxe 4.0-preview 4

**Comment by Hevedy** [comment]
Can you tell me then what version is supported with 3.4 then ?

Cause tried 1.6 / 1.5 / 1.4 / 1.3 / 1.2 and no one works

**Comment by ncannasse** [comment]
As written here: 
https://github.com/HaxeFoundation/hashlink/releases
HashLink 1.1 is compatible with Haxe 3.4
But I'm not sure if it works well with Heaps 1.2.0, tell me if you get some error.
HL has been evolving a lot in past months. Now it's more stable so I'm planning to keep full backward compatibility from now.
