### ISSUE TITLE
Compile error when compiling example

### ISSUE THREAD

**Issue by sixFingers** [HeapsIO/heaps#401]
I get this error:

```
/heaps/1,2,0/h2d/Sprite.hx:436: characters 19-41 : Cannot access private constructor of h2d.Drawable
```

when trying to compile the [example application](https://heapsio.github.io/heaps.io/documentation/getting-started/2.hello-world-heaps.html).

**Comment by ncannasse** [comment]
Yes, I will release an update very soon.

**Comment by ncannasse** [comment]
Heaps 1.3 has been released, should fix the issue.
