### ISSUE TITLE
Haxe compile error when targeting js

### ISSUE THREAD

**Issue by qwertykg** [HeapsIO/heaps#404]
I'm on Haxe version 3.4.7 and on the latest release of heaps, when compiling I'm getting the following error: 

...\.haxelib\heaps/1,3,0/hxd/fs/LocalFileSystem.hx:17: characters 13-29 : You cannot access the sys package while targeting js (for sys.io.FileInput)

**Comment by ncannasse** [comment]
Are you referencing hxd.ds.LocalFileSystem in some way ? It's not available in JS.

**Comment by ncannasse** [comment]
In particular you can't use hxd.Res.initLocal() in JS.

**Comment by qwertykg** [comment]
So I got to the bottom of this - The problem was that I was using node to spawn a child process to transpile the haxe code to javascript. Thus #if node was true and this caused the problem
