### ISSUE TITLE
Seems like Flash target don't work at all

### ISSUE THREAD

**Issue by xdeadmonkx** [HeapsIO/heaps#416]
When i try to build any of examples by running "haxe ....._swf.hxml" it yields swf that has only white background on opening and nothing from example.
Haxe 4.0.0 preview 4

**Comment by ncannasse** [comment]
It works well here, try to install a flashplayer debug version to see what kind of exception you get.

**Comment by xdeadmonkx** [comment]
Yep, it works from flash player.
But embed to browser and android AIR builds still white, can't get why
