### ISSUE TITLE
Prevent window resize

### ISSUE THREAD

**Issue by bojjenclon** [HeapsIO/heaps#417]
I don't see the SDL resizeable flag exposed anywhere, is it possible to restrict window resizing?

**Comment by bojjenclon** [comment]
I also realized the window's position can't be changed, so manually resizing it and then centering isn't really an option.

**Comment by ncannasse** [comment]
Yes atm we don't offer much customization of the sdl window but that can be easily changed by adding additional APIs in HashLink/SDL here: https://github.com/HaxeFoundation/hashlink/tree/master/libs/sdl
Then accessing the sdl window with @:privateAccess hxd.Stage.getInstance().window

**Comment by ncannasse** [comment]
It's now possible to do both using SDL/DX (HL 1.9)
