### ISSUE TITLE
json missing from samples

### ISSUE THREAD

**Issue by lewislepton** [HeapsIO/heaps#428]
just to say that from the 'drawing tiles' in the wiki. the examples do not have a json file in the res folder to view or play around with the example

https://github.com/HeapsIO/heaps/wiki/Drawing-Tiles

**Comment by markknol** [comment]
(Also no PNG)

**Comment by Yanrishatum** [comment]
This is no longer relevant to a degree, since I updated that page with more samples as well as added a note that those files are not provided.

@ncannasse Should be either closed, or I can make a new sample that covers this page. Alternatively I can modify the `Tiled` sample.
