### ISSUE TITLE
Relax FBX import error throw policy

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#430]
Right now, if during import it encounts unknown curve values, it will crash, see: [here](
https://github.com/HeapsIO/heaps/blob/master/hxd/fmt/fbx/BaseLibrary.hx#L876) and [here](
https://github.com/HeapsIO/heaps/blob/master/hxd/fmt/fbx/BaseLibrary.hx#L903)
Proposal: Relax import policy to either `trace` a warning, or raise a `Context.warning` in macro context. 
Justification:
Some editors (Maya) automatically add some curves, even if they are not used. In our case during LD42, it added multiple unused curves, alongside with `d|Visibility` curve key, and it would be a pain to get rid of. I can dig up exact models on which we had this issue (due to LD time restraints, I did exactly what proposed - relaxed policy and moved on).

**Comment by ncannasse** [comment]
No problem is just ignoring these, I developed the FBX reader with the intention of adding features as we found them in FBX we generate at Shiro, but yes for more various sources of FBX we could just skip on unsupported keys/curves.
