### ISSUE TITLE
GL error 1282 when using Samsung Internet browser

### ISSUE THREAD

**Issue by lbergman** [HeapsIO/heaps#436]
Our games stopped working in recent versions of Samsung Internet browser, and we get ```Uncaught Error: Failed to alloc texture RGBA(error 1282)```

Seems like issue appeared in this commit which added the check for gl errors:
https://github.com/HeapsIO/heaps/commit/4213a237784c03c450f807767deff426234e826c#diff-fcdc894debec41a3aa73c83a53011bda

If I modify check error to not throw and error, game loads and displays fine, so this particular error seems non-critical.

Not sure what to do to best handle the issue. Ideally I would of course like to avoid the GL error completely, but if that is not possible, question is if one should accept this error without throwing since it doesn't seem fatal?

**Comment by ncannasse** [comment]
Hi, I think you might have some prior error that is captured in this getError() check. Try running with the fix I just commited.

**Comment by lbergman** [comment]
Thanks, will try it out and report back!

**Comment by lbergman** [comment]
Everything running fine on Samsung Internet now, many thanks!
