### ISSUE TITLE
Heaps does not compile

### ISSUE THREAD

**Issue by yannickhutter** [HeapsIO/heaps#438]
Hello everyone
I am currently in the process of trying out the heaps library. I am following [this tutorial](https://haxe.org/videos/conferences/haxe-summit-us-2018/making-games-with-heaps-io-nicolas-cannasse.html).

I have the following things installed:

- Haxe Compiler 4.0.0
- Newest Heaps Library installed from github

The source code itself is very minimalistic:
`class Game extends hxd.App {

    static function main() {
        new Game();
    }
    
}`

The problem occurs when I want to build things. There seems to be various errors inside source files of the heaps library:

![build_errors_heaps](https://user-images.githubusercontent.com/2662599/46579915-a3bf8c00-ca1a-11e8-9929-0ca6ee508691.png)

At this point I am not 100% sure if this is an error in the library itself or if I am missing any dependency.

I am running on the following setup:

- Windows 10 x64
- Visual Studio Code
- Haxe Plugins

I hope this is clear enough, if any more information is needed I will provide them gladly.

**Comment by ncannasse** [comment]
Try using Haxe compiler 4.0-preview 4

**Comment by yannickhutter** [comment]
Hello
Thanks a lot for your help I really appreciate it.
Now almost all errors are gone except one which says the Type haxe.xml.Access cannot be found which is quite odd because according to the [documentation](https://api.haxe.org/v/development/haxe/xml/Access.html) it should exist. 

![haxe_xml_not_found](https://user-images.githubusercontent.com/2662599/46580465-88a64980-ca25-11e8-84f4-211613a02266.png)


If you could help me with this last step I would be really grateful.

**Comment by ncannasse** [comment]
Yes you need Haxe GIT to use Heaps GIT, or you can get Heaps 1.4.0 which was released just a few days ago.

**Comment by yannickhutter** [comment]
Perfect you are a life saver :).
Thank you so much. Doing a haxelib install heaps (installing version 1.4.0) did the trick. Between great work on Evoland II it is what got me into the heaps framework.
