### ISSUE TITLE
Heaps HL/C windows cross compilation problem on Linux

### ISSUE THREAD

**Issue by YRTV** [HeapsIO/heaps#439]
After fixing headers https://github.com/HaxeFoundation/hashlink/issues/187 and compiling Hello World successfully. I attempted to compile this. It compiles but crashes with  Uncaught exception: Access violation. 

build.hxml 
`-cp src
-D analyzer-optimize
-main SpineTest
-lib heaps
-lib hlsdl
--each
-hl ./hlbc/hlboot.hl
--next
-hl ./hlc/main.c`

SpineTest.hx
`import h2d.Anim;
import hxd.Res;

class SpineTest extends hxd.App {
	var anim:h2d.Anim;
	override function init() {
		super.init();
		var runatlas = Res.spineboy_pro_run;
		this.anim = new Anim(runatlas.getAnim(), 15, s2d);
	}
	override function update(dt:Float) {
		super.update(dt);

	}
	static function main() {
		Res.initEmbed();
		new SpineTest();

	}

}`

`i686-w64-mingw32-gcc main.c -std=c11 -v -o main.exe -O3 -I./ -I./hl170win/include -L./hl170win -ldbghelp -llibhl -lui -lsdl -lopenal -lfmt -municode`
Where `hl170win` is hashlink from release page.

**Comment by ncannasse** [comment]
You would need a debugger to pinpoint the stack trace. Also try to remove as much code as possible to pinpoint the problem.

**Comment by YRTV** [comment]
Callstack
```

fields (Unknown Source:0)
fun$4257() (d:\yurii\Documents\HaxeThings\SpineTest\hlc\hl\functions.c:8918)
hl_entry_point() (d:\yurii\Documents\HaxeThings\SpineTest\hlc\main.c:436)
hlc_static_call(void * fun, hl_type * t, void ** args, vdynamic * out) (d:\yurii\Documents\HaxeThings\SpineTest\hlc\hl\reflect.c:15)
libhl!hl_call_method (Unknown Source:0)
libhl!hl_dyn_call (Unknown Source:0)
libhl!hl_dyn_call_safe (Unknown Source:0)
wmain(int argc, uchar ** argv) (d:\yurii\Documents\HaxeThings\SpineTest\hlc\hashlink\src\hlc_main.c:130)
__tmainCRTStartup (Unknown Source:0)
KERNEL32!BaseThreadInitThunk (Unknown Source:0)
ntdll!RtlValidSecurityDescriptor (Unknown Source:0)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
ntdll!RtlValidSecurityDescriptor (Unknown Source:0)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
ntdll!RtlCaptureContext (Unknown Source:0)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)

```

Exception
![code_2018-10-21_09-44-22](https://user-images.githubusercontent.com/18060413/47264083-a5f41100-d517-11e8-8ce8-b4585465a4c4.png)

I hope this will help.

**Comment by YRTV** [comment]
Works fine, when compiled with msvc compiler on windows: `cl main.c libhl.lib ui.lib openal.lib fmt.lib sdl.lib /O2 /I . /I ./hashlink/src /link /LIBPATH:./hl170win /OUT:main.exe`

**Comment by ncannasse** [comment]
I have no knowledge in cross compilation but ui_ui_init is declared here:
https://github.com/HaxeFoundation/hashlink/tree/master/libs/ui

**Comment by YRTV** [comment]
Tried to compile mingw native .a because .lib support may be broken and got this:


```
./hashlink/libs/ui/ui_win.c:233:6: error: lvalue required as decrement operand
     *--(int_val*)regs.Esp = regs.Eip;
      ^~
```


```
./hashlink/libs/ui/ui_win.c:234:6: error: lvalue required as decrement operand
     *--(int_val*)regs.Esp = regs.Esp;
      ^~
```

**Comment by YRTV** [comment]
Yes it is mingw .lib linker bug.

Resulting exe will work if openal installed on system: ``` i686-w64-mingw32-gcc main.c ./hl170win/ui.hdll ./hl170win/openal.hdll ./hl170win/fmt.hdll ./hl170win/directx.hdll -v -o main.exe -std=c11 -O3 -I . -I ./hashlink/src -L./hl170win -ldbghelp -llibhl -municode ```
