### ISSUE TITLE
PBR sample showing black sphere

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#449]
The PBR sample is not working correctly and is showing no reflection on the single sphere, while it works good for many spheres (Grid). Something seems to be wrong in rendering as the sample code does not do any specific thing.

**Comment by ncannasse** [comment]
Ping @ShiroSmith

**Comment by guruas3** [comment]
Can this be fixed please? Both latest release and git version have the same weird behavior.
The PBR sample is a more upgraded version of the tutorial from the docs. https://heaps.io/documentation/pbr-materials.html
which also doesn't work for both js and HL.

**Comment by guruas3** [comment]
Thank you Nicolas! It's just was a typo then.
