### ISSUE TITLE
Cube Texture Sample and SAO Sample display only render black

### ISSUE THREAD

**Issue by Wavewash** [HeapsIO/heaps#454]
[https://heaps.io/samples/sao.html](https://heaps.io/samples/sao.html)
[https://heaps.io/samples/cubetexture.html](https://heaps.io/samples/cubetexture.html)

In the chrome dev tools - I don't see any errors to point at resources not being loaded or errors in code. 
Tested on Windows 10,  Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Graphics card: Geforce 1070 gtx

**Comment by ncannasse** [comment]
Duplicate of #450
