### ISSUE TITLE
Blender 3D Models, FBX 6.1.0

### ISSUE THREAD

**Issue by leitebettania** [HeapsIO/heaps#456]
Hello! I'm new to Heaps and i was testing some models made in Blender. Blender only exports to FBX 6.1.0, while Heaps only supports FBX 7.1.0. Is there a way to load FBX 6.1.0 models into Heaps? And if not, can you create some kind of support for it?

**Comment by ncannasse** [comment]
Latest Heaps supports binary FBX, so there should be no problem importing these models from Blender.

**Comment by trethaller** [comment]
Just tested with a simple sphere exported from Blender to binary FBX 7 and got `RangeError: Invalid code point 3612423`

	getString (Bytes.hx:155)
	readBinaryProperty (Parser.hx:305)
	parseBinaryNode (Parser.hx:199)
	parseBytes (Parser.hx:64)
	hxd.fmt.fbx.Parser.parse (Parser.hx:497)
	convert (Convert.hx:47)
	convert (LocalFileSystem.hx:540)
	open (LocalFileSystem.hx:409)
	get (LocalFileSystem.hx:422)
	load (Loader.hx:36)
	loadHMD (Scene.hx:384)
	loadModel (Scene.hx:290)
	loadModel (ContextShared.hx:29)
	loadModel (Context.hx:43)

**Comment by Yanrishatum** [comment]
Can you provide an FBX file?

**Comment by trethaller** [comment]
Sure, sorry [sphere.zip](https://github.com/HeapsIO/heaps/files/2554179/sphere.zip)

**Comment by Yanrishatum** [comment]
Hm. I managed to load it with no issues.
What Haxe version are you using? What Heaps version are you using? (Binary FBX support was introduced since 1.4.0) Are you targeting HL, Flash or JS? (If multiple, do you have same error on all or only specific target?)
