### ISSUE TITLE
Vertex colors do not function in JS target

### ISSUE THREAD

**Issue by dooderino** [HeapsIO/heaps#457]
Example project here:
https://github.com/dooderino/heaps_game

vertex colors work in HL but not JS

**Comment by ncannasse** [comment]
I would need a small reproducible sample that does not link any third party library in order to reproduce and fix.

**Comment by dooderino** [comment]
https://github.com/dooderino/jam_test

I was able to get the output to look the same in HL and Chrome if I turn off hardware acceleration in Chrome. Without turning off that option, the model does not render in Chrome.

**Comment by ncannasse** [comment]
Did you try with Heaps GIT version?

Le ven. 1 nov. 2019 à 07:17, Joe Spataro <notifications@github.com> a
écrit :
