### ISSUE TITLE
Type not found : js.jquery.JQuery

### ISSUE THREAD

**Issue by xiaoshuangLi** [HeapsIO/heaps#460]
Hi,i tried to compile to js and got fllowing error.  **Type not found : js.jquery.JQuery**.
And i tried to compile with **Haxe Compiler 3.4.7**,just work fine.

heaps 1.4.0
Haxe Compiler 4.0.0-preview.5+7eb789f
HL/JIT 1.8.0
HashLink Debugger 0.4.4
VSCode 1.28.2 x64
macOS Mojave

```bash
/usr/local/lib/haxe/lib/heaps/1,4,0/h3d/mat/Material.hx:287: characters 14-30 : Type not found : js.jquery.JQuery
/usr/local/lib/haxe/lib/heaps/1,4,0/hxd/impl/AnyProps.hx:26: characters 14-30 : Type not found : js.jquery.JQuery
```

**compile_js.hxml**
```hxml
-lib heaps
-js main.js
-main Main
-debug
```

**Comment by markknol** [comment]
Thats correct, `js.jquery.JQuery` has been moved out of the standard library and is moved to [hx3compat](https://lib.haxe.org/p/hx3compat/) library.

**Comment by xiaoshuangLi** [comment]
@markknol Thanks, now just work perfect.
