### ISSUE TITLE
Failed to load library fmt.hdll

### ISSUE THREAD

**Issue by Mikeb85** [HeapsIO/heaps#467]
Got this error when trying to compile the HelloWorld example for Heaps on Hashlink target.  

`src/module.c(268) : FATAL ERROR : Failed to load library fmt.hdll
`

Hashlink does work and I compiled both Haxe and Hashlink from source today so I have the latest versions of both.  fmt.hdll is in /usr/local/lib, it should be recognized (libhl.so is there as well and is recognized by hl)  On Fedora 29 if it matters.

**Comment by josuigoa** [comment]
I had something similar [here](https://github.com/HaxeFoundation/hashlink/issues/160). I ended up solving my problem installing those missing libraries.

**Comment by Mikeb85** [comment]
It's so strange.  It worked after I make links with all the .hdll files from /usr/local/lib to /usr/lib64, even though previously I made sure /usr/local/lib was in the library path.

**Comment by Misiur** [comment]
Happens on ubuntu 20, have to move all `hdll`'s from `/usr/local/lib` to `/usr/lib`

**Comment by SuperSandro2000** [comment]
> Happens on ubuntu 20, had to move all `hdll`'s from `/usr/local/lib` to `/usr/lib`

You should create a symlink instead to not potentially confuse your package manager.

**Comment by jcward** [comment]
Note: I had a working hl install, but started getting this error. I realized I had upgraded / re-installed Ubuntu to 22.04 since it was working, so I figured out I needed to:

1) install the [suggested dependencies](https://github.com/HaxeFoundation/hashlink/#building-on-linuxosx)

```
sudo apt-get install libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev libsqlite3-dev
```

2) rebuild hashlink with a clean build:
```
cd /path/to/hashlink
make clean
make
```
Working again! :white_check_mark:
