### ISSUE TITLE
HL touch handling

### ISSUE THREAD

**Issue by josuigoa** [HeapsIO/heaps#482]
I'm facing some issues with the recent changes of HashLink/SDL touches.

When I touch the screen, SDL fires two events: MouseDown and TouchDown. And from those events Heaps creates two EPush events that don't make any difference.

This should be handled by the user or would Heaps return a single event?

**Comment by ncannasse** [comment]
It should return a single event

**Comment by josuigoa** [comment]
A fix that comes to my mind is to ignore mouse events `if (Sys.systemName() == 'Android')` in the haxe side, but it doesn't seem very elegant to me. Maybe there is a more convenient way to do it in SDL? What do you think?

**Comment by ncannasse** [comment]
in `hxd/Window.flash.hx`, we did use `hxd.System.getValue(IsMobile)`  but it's not yet implemented correctly in `System.hl.hx`, so I guess you could submit a PR for both fixes.

**Comment by ncannasse** [comment]
Close by #485
