### ISSUE TITLE
Make Engine's resCache accessible

### ISSUE THREAD

**Issue by AustinEast** [HeapsIO/heaps#484]
I'd like to see the `resCache` field in the `Engine` class be accessible in someway, whether through wrapper functions or just by setting it to public.

https://github.com/HeapsIO/heaps/blob/94d73d17c0aae5edf42cf8a3adb2acd094df2389/h3d/Engine.hx#L53

My use case: I'm writing a framework on top of Heaps, and I would like to store some default assets with the library (just like Heaps' `DefaultFont`). Having access to that cache would be nice, so all assets of their nature can live in the same place, and so I don't have to implement something into my framework that already exists in heaps ;).

If there aren't any issues with this, I'd gladly write up a PR with the changes necessary.

**Comment by ncannasse** [comment]
Haxe allows this using explicit access without modifying the original library sources. Simply do:
`@:privateAccess engine.resCache` to access it.
