### ISSUE TITLE
Could not process the argument

### ISSUE THREAD

**Issue by Jaygem** [HeapsIO/heaps#500]
I'm following the tutorial on how to get started with heaps and visual studio code.

the very steps i did :
* Installed the latest stable version, Haxe compiler version = 3.4.7
* Installed Heaps from github : ``` haxelib git heaps https://github.com/ncannasse/heaps.git```
* Created new folder
* Created new file "compile.hxml
* Wrote :
```
-lib heaps
-js hello.js
-main Main
-debug
```

* Created the Main.hx file and copy-pasted the content asked to be copy pasted
* Created the build config of VScode as asked
* Run

here is the error i got :  
```
> Executing task: C:\HaxeToolkit\haxe\haxe.exe --connect 6001 compile.hxml <

Error: Could not process argument ´┐¢´┐¢- l i b   h e a p s
invalid character: ´┐¢
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Edit : I run everything on a windows 10

**Comment by Yanrishatum** [comment]
It seems that something messed up in hxml file encoding, as it have invalid characters in the beginning. Can you recheck that hxml does not contain any extra characters?

**Comment by Jaygem** [comment]
Thanks for your help! 
The encoding was indeed the problem, cannot understand why i haven't thought of checking it
