### ISSUE TITLE
H2d Interactive OnRelease bug

### ISSUE THREAD

**Issue by linkrocks** [HeapsIO/heaps#502]
I have an app I'm making with heaps and I have multiple bitmaps with unique functions attached to them that are triggered with an OnRelease.

Picture like a 2x2 array of bitmaps where each number is a unique bitmap

[Func1] [Func2] [Func3] [Func4]
[Func5] [Func6] [Func7] [Func8]

I find if I push down on one bitmap and then drag and release, both the first initial bitmap's event is triggered and the one where the function was released in but none of the ones in between.

Ie, If I click on Func1, then drag through Func2 and release in Func7, both OnRelease events are triggered for Func1 and Func7

**Comment by Yanrishatum** [comment]
I looked into it, and see where this coming from. While I think that `ERelease` should not be fired on second Interactive, I suspect you misused `onRelease` function. It fires regardless if mouse is over the Interactive or not. If you want it to react when user actually clicks on Interactive - use `onClick`.
While said that, I still think that `onRelease` work slightly misleading, as it uses `ERelease` event kind in both cases, disguising `EReleaseOutside` as `ERelease`.
