### ISSUE TITLE
Alpha 0.0 on white Text with filters is still visible

### ISSUE THREAD

**Issue by Sechgulo** [HeapsIO/heaps#506]
Seems to be something strange going on with what I would guess is BlendMode+Alpha on Object with  white color and Filters applied.

Steps to reproduce:

1. Have a an Object (ex Bitmap) which you add a Text as child to.

2. Set textColor to white (important, bug doesnt occur with black). 

3. Apply Filters to the child Text (ex a yellow Outline which will make the issue clear).

4. Set alpha for the Text Object to 0.0

You should see that the Text is still visible with what looks like some strange blend mode applied.
If you however add a Filter (any filter will do, can be an invisible DropShadow), setting alpha for Text to 0.0 will now properly work and the Text disappears.

**Comment by ncannasse** [comment]
Does it reproduces with git version ?

**Comment by Sechgulo** [comment]
Sorry I was using a slightly outdated version but tested with latest Object and Drawable. But updated our fork now with latest master and the issue is gone. Closing this.
