### ISSUE TITLE
h2d.Scene rotation/events

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#51]
Scaling the h2d.Scene is not properly supported atm. This needs to be handled (requires fixing event handling and mouseX/Y as well)

**Comment by ncannasse** [comment]
#144 might be related

**Comment by trethaller** [comment]
Using Interactive.globalToLocal (from Sprite) in Scene.handleEvent/dispatchEvent/getInteractive seems to fix it, like:

		for( idx in index...interactive.length ) {
			var i = interactive[idx];
			if( i == null ) break;

			var local = i.globalToLocal(new Point(rx, ry));
			if (local.x < 0 || local.x > i.width || local.y < 0 || local.y > i.height)
				continue;

Is that good to go?
