### ISSUE TITLE
Segmentation fault on tiling manager

### ISSUE THREAD

**Issue by flamendless** [HeapsIO/heaps#531]
Hi, after a lot of debugging on why a simple heaps test project segment fault on my Linux manjaro i3wm, with the help of other discord users found out that when extending from hxd.app, during initialize when i3wm (tiling window manager) resizes the created heaps window to fit the setup is the root of the issue.

I use hashlink btw

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ncannasse** [comment]
"when i3wm (tiling window manager) resizes the created heaps window"
This is not supposed to be able to create a segfault, could you debug with gdb and send a stack trace?
If possible recompile hashlink with -g to get good file/line info

**Comment by flamendless** [comment]
Heres the output of [strace](https://www.dropbox.com/s/btqhfnpwcs1x73o/output.txt?dl=0)

According to the convo at discord:
> E.g. window created, Heaps adds resize hooks, but don't have enough time to actually initialize properly before window get resized, hence the crash?
> it crashes with SIGWINCH

**Comment by ncannasse** [comment]
SIGWINCH should be handled by SDL since it handles the whole windows, but I haven't found much information about it. Maybe ask on SDL forums?

**Comment by flamendless** [comment]
What sdl version does heap/hashlink (hlsdl) use?

**Comment by ncannasse** [comment]
On linux, it uses the one installed on your system as we don't link statically.

**Comment by ncannasse** [comment]
Seems a bug outside of Heaps range, mostly SDL/GL related.
