### ISSUE TITLE
App.loadAssets is not asynchronous as described/window freeze during workload

### ISSUE THREAD

**Issue by Furfel** [HeapsIO/heaps#533]
Or I don't know how to use it.
I tried creating a loader which will switch the `Scene` after loading is complete but failed miserably.
Tried overriding `setup()`, calling `s2d.render()` every load line and it always freezes (target hl).
Example:
```
    override function loadAssets(onLoaded: Void -> Void) {
        setScene2D(new LoadingScene());
        onLoaded(); //To start at least rendering
        for(i in 1...99999999) {
            var f = Math.sin(i);
        }
        setScene2D(new MainScene());
    }
```

My long struggles trying to make this work:
https://youtu.be/9e_cZ771h9o?t=3376

**Comment by Furfel** [comment]
I see now that it is somehow _doable_ as with `hxd.fmt.pak.Loader` however it's getting on a very low level.

**Comment by Furfel** [comment]
In App.hx
https://github.com/HeapsIO/heaps/blob/8a33837973e7207b00edd47fc2ac76475efc2d20/hxd/App.hx#L114
```
	function setup() {
                _[...]_
		loadAssets(function() { //Some _new Thread_ here?
			initDone = true;
			init();
			hxd.Timer.skip();
			mainLoop();
			hxd.System.setLoop(mainLoop);
			hxd.Key.initialize();
		});
	}
```

**Comment by ncannasse** [comment]
loadAssets is meant to delay the update, so there is no rendering occuring.
If you want to load assets while rendering, you can use another hxd.App that first load the assets and display a progress bar, then create your main hxd.App when done.

This can be done by adding a hxd.fmt.pak.Loader to your 2D scene.
