### ISSUE TITLE
MP3 variable bitrate isn't supported on JS target

### ISSUE THREAD

**Issue by deepnight** [HeapsIO/heaps#535]
This isn't a critical issue, I could just make an Average-Bitrate MP3, but there's no error, warning, throw, whatever. The JS runs fine, except no music plays AT ALL.

Adding a proper warning/error message on build would be great.

**Comment by Yanrishatum** [comment]
Could you provide an example MP3 file?

**Comment by deepnight** [comment]
That could be related to this issue, as I only tested it on Firefox 64 🤔 Unfortunately, I didn't keep the VBR MP3 file, it was overwritten when I tested CBR MP3. If this happens again and on another browser, I will simply reopen this issue.
