### ISSUE TITLE
Cannot set window title

### ISSUE THREAD

**Issue by samw3** [HeapsIO/heaps#542]
I can't see a way to set the title of the window via Heaps when using hlsdl.

**Comment by Yanrishatum** [comment]
Currently title can be set only at compile time with a `-D windowTitle=mytitle` define. (From public API. With access to internals it is possible to access SDL Window instance and set title manually at runtime)

**Comment by ncannasse** [comment]
Maybe that's something @RobertBorghese would be interested contributing (at least on the hlsdl/hldx level)

**Comment by RobertBorghese** [comment]
Huh, surprised I didn't throw this in sooner. Should be a piece of cake and would be nice to have. 

I'll add it on the HashLink-side of things and get back to you in a bit. 👌

**Comment by trethaller** [comment]
For reference, as Pavel said it's currently possible using privateAccess, this will work for SDL and DX:

```@:privateAccess hxd.Window.getInstance().window.title = title;```

**Comment by ncannasse** [comment]
Close by #732
