### ISSUE TITLE
Odd glyphs alignment using SDF fonts

### ISSUE THREAD

**Issue by trethaller** [HeapsIO/heaps#550]
This is using the new SDF fonts support contributed by @Yanrishatum (thanks!). Haven't looked into it much yet, but I see some misalignment on the Y axis, looks like a rounding error. I've been following [this tutorial ](https://github.com/libgdx/libgdx/wiki/Hiero)to export our font using Hiero, and I don't know yet if the problem is in the rendering or the exporting of the font (Londinia).

![image](https://user-images.githubusercontent.com/1499344/52965674-ac9b7380-33a5-11e9-8147-961dfbbca084.png)

**Comment by Yanrishatum** [comment]
Please check if issue reproduce on #521 ?
I noticed it too, and looks like issue with Tile and other s2d elements being Integer-based.

**Comment by trethaller** [comment]
#521 fixes it, yes! I've tried the PR against the Northgard codebase, and apart from all the tedious Float-Int cast errors to fix, it all worked great. I've dicussed it with @ncannasse, we'll merge right after the next Northgard milestone has passed. Thanks!
