### ISSUE TITLE
Compiling to C++ is not working

### ISSUE THREAD

**Issue by exigow** [HeapsIO/heaps#551]
Hi,

the most basic [Hello World Example](https://heaps.io/documentation/hello-world.html) from official Heaps documentation works well on JavaScript target but I also wanted to check native C++ equivalent. Unfortunately something goes wrong during compilation:

```
> haxe -main Main.hx -lib heaps -cpp Hello.cpp
/home/exigo/.haxelibs/heaps/1,5,0/h3d/impl/GlDriver.hx:157: characters 16-27 : Type not found : Framebuffer
/home/exigo/.haxelibs/heaps/1,5,0/h3d/Engine.hx:17: lines 17-415 : Defined in this class
/home/exigo/.haxelibs/heaps/1,5,0/h3d/impl/GlDriver.hx:130: characters 16-23 : Type not found : Program
```

File `Main.hx`:
```haxe
class Main extends hxd.App {
    override function init() {
        var tf = new h2d.Text(hxd.res.DefaultFont.get(), s2d);
        tf.text = "Hello World !";
    }
    static function main() {
        new Main();
    }
}
```

Haxe version: `3.4.7`
Heaps version: `1.5.0`

Please advise.

**Comment by ncannasse** [comment]
HxCPP is not supported in Heaps. You can use  Hashlink/C output with Haxe 4.0-RC1 and latest Heaps.

**Comment by exigow** [comment]
Thanks!
