### ISSUE TITLE
Solution for h2d.filter.Mask()

### ISSUE THREAD

**Issue by lusius** [HeapsIO/heaps#552]
> h2d.filter.AbstractMask.bindCount

 isn't defaulted  to 0 for some reason and breaks logic needed to this filter to work.

solution was to default in declaration.
`	var bindCount : Int = 0;`

then set_mask() will trigger correctly and set filters.

I'm guessing the style of default values has changed over time? Before fixing it would be nice to get some kind of closure in this.

**Comment by ncannasse** [comment]
An overlook, JS does not initialize properties to 0
