### ISSUE TITLE
1.6.0 fails to compile on JS target

### ISSUE THREAD

**Issue by ratkingsminion** [HeapsIO/heaps#559]
With the new release (1.6.0) I get the following errors:

C:\HaxeToolkit\haxe\lib\heaps/1,6,0/h3d/impl/GlDriver.hx:895: characters 24-26 : Identifier 'BC' is not part of hxd.PixelFormat
C:\HaxeToolkit\haxe\lib\heaps/1,6,0/h3d/impl/GlDriver.hx:895: characters 24-29 : Unrecognized pattern: BC(_)

I use Haxe 4.0.0RC1. Target is JS.

**Comment by ncannasse** [comment]
Yes, I made some changes just before release... :'(

**Comment by ncannasse** [comment]
Fixed in 1.6.1
