### ISSUE TITLE
Corrupted VAOs between frames on Mali GPU

### ISSUE THREAD

**Issue by lbergman** [HeapsIO/heaps#562]
Rendering started breaking occasionally on Samsung phones, only showing text and graphics objects in black and nothing else. Seems to be related to this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=934823

Happens with latest git as well as older versions.
Adding the following to our render function after render calls solves the issue:
```
var canvas:js.html.CanvasElement = cast js.Browser.document.getElementById('webgl');
var gl = canvas.getContext('webgl2');
if (gl != null) {
	gl.bindVertexArray(null);
}
```

**Comment by ncannasse** [comment]
Thanks for the report, but I'm not sure if I want to fix driver-specific bugs in Heaps directly, especially if a fix is on the way.

**Comment by lbergman** [comment]
Sure, I figured I make an issue since it is such a widespread problem (affecting most Samsung phones in EU). We can live with working around it in our code though.

**Comment by lbergman** [comment]
Actually the workaround is not completely removing the issue. Before when things got corrupted it would remain so until changing tab or reloading. Now it will usually pick up rendering again, but one can still end up in a state where game becomes unusable. 

For urgent fix for our games in production we made a version which just sticks to using WebGL1. Would you mind a MR which makes it configurable to disable WebGL2?

Ideally I would be able to set the flag at runtime to be able to allow webgl2 depending on device, but looking at how GlDriver is constructed, it seems messy to pass along a webgl specific flag from App. Unless you have any idea how to do that in a nice way, we would at least need a conditional compilation flag to force webgl1.

**Comment by ncannasse** [comment]
What I propose you is making a PR that does add a static h3d.impl.GlDriver.ALLOW_WEBGL2 = true (and check it in driver new() )
