### ISSUE TITLE
Letter/pillarboxing with h2d?

### ISSUE THREAD

**Issue by shingle-bells** [HeapsIO/heaps#563]
I'm trying to maintain a constant aspect ratio regardless of the window size, and I've been scratching my head trying to figure it out. s2d.setFixedSize(x,y) stretches the image to fit the screen; is there a way to automatically scale the scene so it maintains the aspect ratio and stays centered in the window?

**Comment by Yanrishatum** [comment]
Related: #524 
Currently apart from hacky usage of h2d.Mask, custom positioning and `setFixedSize` calls there is no way to set up aspect ratio of the s2d.
