### ISSUE TITLE
Leak

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#564]
Using drawTo() on a h2d.Graphics that is not part of a scene will leak the vertex buffer after the Graphics is GC'ed. 

This is related to dispose/onRemove discussion in #558

**Comment by Yanrishatum** [comment]
I would add that `h2d.TileGroup` most likely will leak buffers as well, since it utilizes custom primitive.
Possible solution:
`drawTo` will either call `dispose()` or `onRemove()` on object if object not present on the scene (`needDispose == true`).

**Comment by ncannasse** [comment]
It calls dispose () on the scene so that is supposed to work already. But
doesn't.

Le mer. 13 mars 2019 13:01, Pavel Alexandrov <notifications@github.com> a
écrit :

**Comment by Yanrishatum** [comment]
Well, duh, because object never actually added to that temporary scene? ;)

**Comment by ncannasse** [comment]
Most likely :D
