### ISSUE TITLE
Setting anti aliasing/provide engine to app

### ISSUE THREAD

**Issue by lbergman** [HeapsIO/heaps#567]
Want to be able to set anti aliasing. Looking att App.hx it seems like the idea is that you can instantiate Engine yourself, and then App will try to get engine through Engine.getCurrent.
However, when I try to do that, setup will be called before scene is ready, resulting in an error.

I have a class that extends hxd.App, which creates the engine before super call:
```
public function new() {
   var engine = new h3d.Engine(true, 1);
   engine.init();
   super();
}
```

Currently, App constructor looks like this: 
```
public function new() {
	var engine = h3d.Engine.getCurrent();
	if( engine != null ) {
		this.engine = engine;
		engine.onReady = setup;
		haxe.Timer.delay(setup, 0);
	} else {
		hxd.System.start(function() {
			this.engine = engine = new h3d.Engine();
			engine.onReady = setup;
			engine.init();
		});
	}
}
```
If I remove ```haxe.Timer.delay(setup, 0);``` it works ok and setup is called when engine is ready. 
Am I doing something wrong, or should perhaps App.hx only run setup when engine.onReady is triggered?

**Comment by ncannasse** [comment]
Let's instead change AA settings by a static variable in hxd.Engine maybe? since we actually create a single instance of it, it would more correct (same of hardware flag).
Can you submit a PR?

**Comment by lbergman** [comment]
Sure. I'm still a bit confused why the delayed call to setup is needed though, and how one would be able to construct app with an Engine. Are you should that needs to stay and that you prefer a PR with a static aa setting on Engine?

**Comment by ncannasse** [comment]
Yes I prefer this way.
