### ISSUE TITLE
Error while try load a bitmap

### ISSUE THREAD

**Issue by Thanh9356** [HeapsIO/heaps#569]
These are the errors I get (screenshot included):
`src/Main.hx:15: characters 23-49 : hxd.BitmapData should be Null<h2d.Tile>
`
`
src/Main.hx:15: characters 23-49 : For optional function argument 'tile'
`
![Capture](https://user-images.githubusercontent.com/36446935/54439769-08baa300-476c-11e9-9dc9-152ca2a34454.PNG)

**Comment by Yanrishatum** [comment]
`h2d.Bitmap` takes an `h2d.Tile` as source. `toBitmap` method creates a RAM instance of the image, what you are looking for is `toTile` method which loads image as GPU texture and creates an instance of the Tile representing this texture.

**Comment by Thanh9356** [comment]
That means I should use `toTile` not `toBitmap` ?

**Comment by Ghouly-The-Ghost** [comment]
@Thanh9356 Yes. If you check out the constructor for Bitmap you can see the kind of data type it's expecting. (Here: https://github.com/HeapsIO/heaps/blob/master/h2d/Bitmap.hx#L17). You'll notice it wants a texture, so that's why `toBitmap` is the wrong data type to provide it.

**Comment by Thanh9356** [comment]
> @Thanh9356 Yes. If you check out the constructor for Bitmap you can see the kind of data type it's expecting. (Here: https://github.com/HeapsIO/heaps/blob/master/h2d/Bitmap.hx#L17). You'll notice it wants a texture, so that's why `toBitmap` is the wrong data type to provide it.



> `h2d.Bitmap` takes an `h2d.Tile` as source. `toBitmap` method creates a RAM instance of the image, what you are looking for is `toTile` method which loads image as GPU texture and creates an instance of the Tile representing this texture.

Thanks a lot! Now I can compile it

**Comment by Thanh9356** [comment]
@Ghouly-The-Ghost @Yanrishatum Thanks! :)
