### ISSUE TITLE
Steam overlay on linux not working

### ISSUE THREAD

**Issue by ZhulanovAA** [HeapsIO/heaps#570]
Steam overlay not working in linux versions of Dead Cells and Evoland. It's only two games in my steam library where I have this problem and they both use heaps so maybe there is some problem in the engine?

I have this problem on two machines with nvidia and intel graphics. OS was Ubuntu with Gnome.

As I understand this problems usually happen when steam can't understand what this is already the game and not some sort of launcher.

**Comment by ncannasse** [comment]
Yes we manually disabled the overlay in our scripts since for a reason unknown to us it was crashing the game at startup on a significant amount of computers.

**Comment by ZhulanovAA** [comment]
Oh, well but it also results in my actual problem with steam controller (and whole steam input which could be used for other gamepads too). Steam thinks i'm not in the game and uses desktop config instead of one for this game so i have to change desktop config to something that can be used in game.

But well, there is not too much linux gamers and not too much steam controller users and this bug seems to be tricky to fix
