### ISSUE TITLE
Sound: inconsistent use of gain/volume

### ISSUE THREAD

**Issue by trethaller** [HeapsIO/heaps#571]
We currently use the term "gain" (see `audibleGain`, `calcAudibleGain` in hxd.snd.Channel) to represent what seems to be volume multipliers. In audio terminology, gain/attenuation should use dB units. It doesn't seem like there is any notion of non-linear gain/attenuation in the engine currently.

The confusion probably comes from OpenAL which also uses the term "gain" to represent amplitude multipliers:

> AL_GAIN defines a scalar amplitude multiplier. As a source attribute, it applies to thatparticular source only. As a listener attribute, it effectively applies to all sources in thecurrent context. The default 1.0 means that the sound is unattenuated. An AL_GAINvalue of 0.5 is equivalent to an attenuation of 6 dB.

I suggest we stick to "volume" to avoid this confusion.

**Comment by ncannasse** [comment]
good for me, PR welcome :)
