### ISSUE TITLE
Render target depths buffers don't work on hl/sdl

### ISSUE THREAD

**Issue by FireSlash** [HeapsIO/heaps#574]
I originally asked about this on the forums, but after digging deeper and trying some other targets, I think this may actually be a bug.

push/popTarget will render to a texture, but cannot properly use depth buffers on sdl/dx targets. If you pass a depth buffer, they simply render nothing. As expected, omitting the buffer produces undesirable results.

I wrote up a quick sample app. Keys are as follows:
1 - Render to texture with depth
2 - Render to texture without depth
3 - Render normally.

JS target will render with depth info, but requires a new buffer every frame (Unclear if this is expected behavior or not, there doesn't appear to be a way to clear depth buffers). However, I wasn't able to confirm correct behavior as it doesn't seem to want to render the model texture.

Sample code below, or [download here](http://comeonandsl.am/dev/bugrepro/heaps_574.zip) if you want assets+build.hxml

```
import haxe.Json;
import hxd.Key;
import h3d.mat.DepthBuffer;
import h3d.mat.Texture;
import h2d.Bitmap;

class Main extends hxd.App 
{
	var texSceneRT: Texture;
	var depthSceneRT: DepthBuffer;
	var cache = new h3d.prim.ModelCache();
	var cc : h3d.scene.CameraController;
	var bUseRenderTarget = true;
	var bUseDepthTexture = true;

	override function init() 
	{
		engine.backgroundColor = 0x0;

		texSceneRT = new Texture(engine.width,engine.height, [Target] );

		new Bitmap( h2d.Tile.fromTexture( texSceneRT ), s2d );
		s3d.addChild( cache.loadModel( hxd.Res.mdl.test2 ) );

		cc = new h3d.scene.CameraController(s3d);
		cc.loadFromCamera();
	}
    
	override function update(dt:Float) 
	{
		#if sys
		if( Key.isPressed( Key.ESCAPE  ) )
			Sys.exit(0);
		#end
		// Render to target with depth texture
		if( Key.isPressed( Key.NUMBER_1  ) )
		{
			bUseRenderTarget = true;
			bUseDepthTexture = true;
		}
		// Render to target with null depth
		if( Key.isPressed( Key.NUMBER_2  ) )
		{
			bUseRenderTarget = true;
			bUseDepthTexture = false;
		}
		// render normally
		if( Key.isPressed( Key.NUMBER_3  ) )
		{
			bUseRenderTarget = false;
			bUseDepthTexture = false;
		}
	}

	override function render(e:h3d.Engine) 
	{
		// Prep
		texSceneRT.clear( 0, 0 );
		// Note: This is probably overkill, but JS doesn't seem to clear the
		// depth buffer, and it's the only even semi-working target, so
		// might as well eliminate the variable.
		if( texSceneRT.depthBuffer != null )
		{
			texSceneRT.depthBuffer.dispose();
			texSceneRT.depthBuffer = null;
		}

		if( bUseDepthTexture )
			texSceneRT.depthBuffer = new DepthBuffer( engine.width, engine.height );

		// Render 3d scene
		if( bUseRenderTarget )
		{
			engine.pushTarget( texSceneRT );
			s3d.render(e);
			engine.popTarget();
		}
		else
		{
			s3d.render(e);
		}

		// Render 2d scene		
		s2d.render(e);   
	}
    
	static function main() 
	{ 
		hxd.res.Resource.LIVE_UPDATE = true;
		#if js
		hxd.Res.initEmbed();
		#else
		hxd.Res.initLocal();
		#end
		new Main();
	}
}
```

**Comment by ncannasse** [comment]
You need to clear the depth every frame.
Call pushTarget then call engine.clear (0,1) instead of calling texBG.clear

**Comment by FireSlash** [comment]
Ah! I dug around for days trying to find a way to actually clear the depth buffer, must be buried inside native code. The "bug" here seems to be more that JS initialized depth buffers differently than native targets, which probably isn't worth worrying about realistically.

It'd probably be worth documenting this somewhere; as there doesn't seem to be any documentation or example (that I could find at least) on how to use render textures. The few threads on the subject are using wildly out of date APIs that no longer exist.

Cheers!

**Comment by ncannasse** [comment]
You're welcome contributing to documentation by submitting a PR here:
https://github.com/HeapsIO/heaps-doc

**Comment by FireSlash** [comment]
opened a PR for render target docs. I'll do one for VolumeDecal as well once that gets figured out. I'm also happy to write a sample for either of these features if you think they'd be valuable.
