### ISSUE TITLE
JS Sound issues when device uses non-44.1kHz sample rate

### ISSUE THREAD

**Issue by RollinBarrel** [HeapsIO/heaps#580]
When system-wide device's sample rate is changed to anything other than 44.1kHz, it breaks on loop in Chrome, and in Firefox it just offsets loop slightly (i think). Higher sample rate's difference is more audible.
https://heaps.io/samples/sound.html

**Comment by ncannasse** [comment]
Any idea how to fix this ?
I have delayed NATIVE_FREQ init here fe160e9ff657d2bfa7d5c059b619a9942eb42cc4 but it seems playing sound with different rate than device should throw an error atm : 
https://github.com/HeapsIO/heaps/blob/master/hxd/snd/openal/Emulator.hx#L487

**Comment by Yanrishatum** [comment]
@RollinBarrel Please recheck with latest Heaps, as JS target now uses new audio driver that hooks to WebAudio directly and most likely fixes this issue (Samples on heaps.io are NOT updated, please compile from source).

**Comment by RollinBarrel** [comment]
Yup, works fine now!
