### ISSUE TITLE
h2d.Graphics.beginTileFill() bug?

### ISSUE THREAD

**Issue by infidel-** [HeapsIO/heaps#581]
![test](https://user-images.githubusercontent.com/4912662/55276531-13e60500-530e-11e9-87f0-1dd1a375482e.png)

I have this image split into tiles with:
```
        var tile = hxd.Res.test.toTile();
        var arr = tile.gridFlatten(64, 64);
        var gr = new h2d.Graphics(obj);
```

If I output a single tile with this:
```
        gr.drawTile(0, 0, arr[1]);     
```
I get this image (correct):
![2019-03-30_1702_001](https://user-images.githubusercontent.com/4912662/55276530-13e60500-530e-11e9-9977-3ed3dd97b3f4.png)

But If I tile fill the graphics like this:
```
        gr.beginTileFill(0, 0, 1, 1, arr[1]);
        gr.drawRect(0, 0, 512, 512);
        gr.endFill();
```
I get this:
![2019-03-30_1702](https://user-images.githubusercontent.com/4912662/55276529-13e60500-530e-11e9-84b0-34dbd277622e.png)

I would expect it to be a grid of IIs pasted but instead I get a single copy of a part of tilemap (why a single copy?). But I guess since the child tile uses the same texture it doesn't happen. If it's the expected behavior then how do I load a tilemap so that tile fill would work correctly?

Only tested in javascript.

Full code:
[test_sub.zip](https://github.com/HeapsIO/heaps/files/3025475/test_sub.zip)

**Comment by ncannasse** [comment]
Yes graphics does not split the tile into parts and does not wrap the texture either.
You might want to look into h2d.TileGroup instead that does what you want.

**Comment by infidel-** [comment]
I'd say this behavior needs to be explained in the API docs.
Thanks, I've used TileGroup in a different case but it did not occur to me to use it in this case, where I'm drawing window borders using tile parts once during the app init phase.
