### ISSUE TITLE
h2d.Interactive native cursor bug

### ISSUE THREAD

**Issue by infidel-** [HeapsIO/heaps#582]
h2d.Interactive does not respect hiding of native cursor. When the cursor is on top of it, finger cursor appears and then after the mouse cursor leaves the interactive it changes to pointer and becomes permanently visible. Probably JS specific.

The easiest way to reproduce is to put ```hxd.System.setNativeCursor(Hide);``` at the top of the Interactive2D.hx init() Heaps example. 

The cursor is invisible at first (actually half of the time it's visible and you need to click the canvas to hide it, probably another bug). When you move it over the Haxe logo, the finger appears and when you move the cursor away from the logo, the finger changes to the pointer and stays visible.

**Comment by ncannasse** [comment]
By default h2d.Interactive has its cursor set to Button, you can set it to Hide instead.
@Yanrishatum maybe we should have a way to define the "default" cursor on SceneEvents so we could set it to null instead.

**Comment by infidel-** [comment]
1) Setting it to Hide hides the finger when the mouse is over it but still leaves the bug - the default cursor appears when the mouse leaves the interactive. And calling setNativeCursor(Hide) in onOut does nothing.
2) Even if the default behavior is correct for the finger, the cursor should still disappear after the mouse leaves interactive.

**Comment by Yanrishatum** [comment]
From what I can see this is a non-bug.
Basically, you shouldn't call `setNativeCursor` externally unless you override `setCursor` method. `SceneEvents` handles shown cursor automatically and sets corresponding cursor based on overed Interactives. 
However I do agree that SceneEvents need a default cursor variable to which it refers when there are no Interactives under mouse cursor, hence allowing showcasing cursor other than Default. 
Are you able to reproduce said cursor behavior without calling `setNativeCursor`? As for now, you can achieve same effect by setting `hxd.System.setCursor` to something like that:
```haxe
function(cur:Cursor):Void
{
  System.setNativeCursor(cur == Default ? Hide : cur);
}
```

**Comment by infidel-** [comment]
Well, that's kinda hard to find out without any documentation. The way you suggest works correctly, I can hide native cursor completely. How do I convert Tile to BitmapData? Or how do I load a png image into a CustomCursor?

**Comment by ncannasse** [comment]
I think we would need some documentation page regarding cursor management.
Also, having a way to change "defaultCursor" (currently Default) on whole sceneEvents would help, as it's the cursor being reset to when no interactive is active.

**Comment by infidel-** [comment]
@ncannasse @Yanrishatum So is there a way to load PNG file into a native cursor?

**Comment by Yanrishatum** [comment]
Yes. There is `hxd.Cursor.Custom` enum that you can use to set custom cursor data. 
`new CustomCursor(frames, speed, offsetX, offsetY)` where:
* `frames` is an `Array<hxd.BitmapData>`
* `speed` is the framerate of animation
* `offsetX` and `offsetY` is visual cursor offset, in case center part of cursor image is not at the top-left corner.

**Comment by infidel-** [comment]
I found that but I'm having trouble getting BitmapData from Tile, how do I do that? The tutorials create BitmapData from scratch.

**Comment by Yanrishatum** [comment]
If you would inspect how `Image` resource operates, you'd notice that apart from `toTile`, there also `toBitmap` and other methods. And if you somehow created Tile without involving Image, Pixels or BitmapData - here is stupid roundabout CPU->GPU->CPU method of extraction: 
```haxe
var b = new hxd.BitmapData(tile.iwidth, tile.iheight);
b.setPixels(tile.getTexture().capturePixels(h2d.col.IBounds.fromValues(tile.ix, tile.iy, tile.iwidth, tile.iheight)));
```
However if you ever use this, I'm not responsible for damages nor guarantee if it would even work.

**Comment by infidel-** [comment]
Thanks for pointing out the toImage(), I somehow missed it.
