### ISSUE TITLE
OpenGL/WebGL getError() can take a long time to complete

### ISSUE THREAD

**Issue by chfoo** [HeapsIO/heaps#583]
For the HTML5/JS output on my application, I noticed that I can't get a constant 60 FPS. I ran Chrome's profiler and found WebGL's `getError()` (called by `allocVertexes()`) was being called on every frame which can take up to 20ms to complete on my hardware. 

Best practice guides say to avoid calls to `getError()`/`glGetError()` on release builds because it can severely impact performance. Could there be an option or define to disable/enable the call to `getError()`?

**Comment by ncannasse** [comment]
Ouch... 20ms is indeed big.
Is there any other way to detect that we have reached the max amount of video memory ? If we can't perform any call to getError then I'm not sure how we're supposed to detect that things are going wrong here.

**Comment by chfoo** [comment]
I'm not finding clear answers, but it seems like it's not part of the spec. It appears that `OUT_OF_MEMORY` might not even be returned because the browser's WebGL implementation does automatic swapping of resources or preventing browser fingerprinting. Instead the WebGL context is lost whenever the browser detects it needs to free up resources for that page.

Is detecting errors in this case absolutely required by Heaps? I think that if the programmer wants to disable `getError()`, then it should be the programmer's responsibility to proactively ensure errors don't happen. They should be able to manage resources themselves (calling `dispose()` when needed for example) and to test to make sure it works before disabling it.
