### ISSUE TITLE
Random gray screen on load in Chrome/Javascript

### ISSUE THREAD

**Issue by infidel-** [HeapsIO/heaps#584]
I'm getting gray screen on page reload randomly and it seems to happen whenever this message appears in the console:

`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu`

I've tried to make NativeChannel.getContext() to always return null and it seems to fix this.

**Comment by ncannasse** [comment]
I think this is related to chrome restriction on sounds, see here:
https://github.com/HeapsIO/heaps/blob/master/hxd/snd/NativeChannel.hx#L106
I'm not sure how to fix this properly...

**Comment by infidel-** [comment]
As far as I can tell, the first getContext() call happens from here:
https://github.com/HeapsIO/heaps/blob/master/hxd/snd/openal/Emulator.hx#L177

I think that this needs to happen in some "sound.init()" call instead that has be called by the developer manually (you can hint about the problem in the console or in audio tutorial or in the "sound.init()" API documentation). This way if the project does not use sound (like mine currently), it will not trigger this bug and when it does, at least some info will be easily available. Another thing is that in this case it's up to the developer how to implement the correct sound initialization using any of the alternatives described in the Google documentation: onclick event listener, unmute button or whatever else.
