### ISSUE TITLE
[JS] Browser's zoom breaks s2d's viewport

### ISSUE THREAD

**Issue by RollinBarrel** [HeapsIO/heaps#593]
On (most?) desktop browsers, if you zoom in/out (like using CTRL and +/-) on page, it changes visible area of s2d instead of zooming it, unless you have used a ```s2d.setFixedSize(w, h)```. Also, a bunch of mobile browsers break it even without zooming
It's easily noticeable in https://yanrishatum.itch.io/edgy-fantasy-battle-deluxe - go ingame, then zoom in/out to break UI

It's not a bug, more like unexpected behaivor - since most people never use zooming, there's a lot of games with this issue, so i think that engine should call ```s2d.setFixedSize(window.w, window.h)``` internally on load, or at least people should be warned of the problem somewhere in the docs

**Comment by ncannasse** [comment]
I think we did actually do something regarding this, which is to take into account current pixel ratio to give the "screen" resolution to Heaps instead of the "unscaled" one.

**Comment by RollinBarrel** [comment]
After quick search i couldn't find anything like that
Just to confirm: this issue is still present in latest git version

**Comment by ncannasse** [comment]
I think that was intended to have the zoom disabled, because on some Windows there's a zoom by default for font display and you don't want it to affect your Canvas. But I can see how that causes some problem, so I'll allow to disable it.
