### ISSUE TITLE
[Proposal] Use full extension chain for Convert

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#607]
Currently, `Convert` match only with actual file extensions. While it does the job just fine, at times there is a need for differentiating between same file extensions.
Let me provide an example:
Project contains multiple `json` files, which are named under `<file>.<type>.json` and for each type there's a need for custom Convert. Obviously, making a monster-convert that checks file path and determines what to do is easy, but then there some json files that should not be converted and as far as I'm aware there's no way for Convert to say "Ok, this file should not be converted", hence ability to assign extension chain will be pretty useful. 
On top of that, `Resource` already uses that approach when it comes to `Res` resolving via `Config.extensions`. 
And another real example: We used png files to provide a hit-test mask which had it's own Resource as well as Convert which would process image and generate bitmask of it. Because Convert did not allowed to use `file.hitmask.png` to match, we had to rename actual extension, which was a bit of a pain in the ass, because a lot of graphics editors (namely - Photoshop) are too stupid to read file headers, refusing to open the file just because extension is unknown.

So, proposal:
1. Add `fullExtension` to `hxd.fs.FileEntry` which would return extension chain instead of only last one. (e.g. for file `my.fancy.extended.file` it would return `fancy.extended.file` versus `FileEntry.extension` - `file`)
2. Set convert to use this variable first, and then as fallback to using only actual extension if none matched.

This would preserve old behavior as well as add consistency between Resource and Convert extension handling.
(Honestly, there's more I'd like to say about Convert, but that's out of the scope of this proposal, I'll get to it one day :) )

**Comment by ncannasse** [comment]
Proposed change looks good to me!

Le sam. 4 mai 2019 00:42, Pavel Alexandrov <notifications@github.com> a
écrit :

**Comment by ncannasse** [comment]
Given the recent changes in convert, I guess this is no longer needed because you can have rules for actual custom regexp, not necessarily extension
