### ISSUE TITLE
Listener added in Main#init called before Key listener

### ISSUE THREAD

**Issue by moreginger** [HeapsIO/heaps#615]
The following sample doesn't detect when space is pressed:

```
class Main extends hxd.App {
	static function main() {
		new Main();
	}

	override private function init() {
		super.init();
		Window.getInstance().addEventTarget((x:Event) -> {
			switch (x.kind) {
				case EKeyDown:
				  if (Key.isPressed(Key.SPACE)) {
						trace('SPACE');
					}
					else {
						trace('OTHER');
					}
				case _:
			}
		});
	}
}
```

This is because `Main#init` is called before `Key#initialize` and therefore the listener in `Key` that sets up the record of which key was pressed is not in the correct state when the first listener is called. Is there a way we can make this foolproof?

It's not straightforward since `Key` can apparently (re)initialize at any time - though I see no call in the heaps source, and it looks like the `Timer#skip` call would also have to move.

**Comment by ncannasse** [comment]
This is not standard usage, if you want to check the key you should use x.keyCode == Key.SPACE
Also, it's most likely you should use s2d.addEventListener instead of Window addEventTarget
