### ISSUE TITLE
[Proposal] Implement s2d cameras

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#622]
First paragraph is premise as usual, propsal afterwards.
I know, I know, it's already was discussed before, and Cannasse was adamantly against the idea of using camera transform inside shaders, and insisted that having it as root object tree is the way to go. I still disagree and still insist that it's a stupid idea. Yet my solution back then was not a proper solution and I admit it. This is basically a take 2 on that matter, that is more researched and will be based on #595 .

Proposal: Introduce GPU-side 2D camera transformation by changing `viewport` variable to `viewportA` / `viewportB` matrix.
* Instead of #595 calculating offsets and scaling relative to screen, Scene will contain `a`, `d`, `tx` and `ty` transform variables that would convert scene coordinate space to -1...1 screen space. (`b` and `c` are omitted, because they are always `0`)
* Base2d shader will apply `dot(viewportA)` / `dot(viewportB)` matrix instead of `(pos.xy + viewport.xy) * viewport.zw`. It does increase calculation cost slightly, however.
* In `RenderContext`: `curX`, `curY`, `curWidth` and `curHeight` will be replaced by `viewportMatrix` (either as separate variables or `h2d.col.Matrix` instance).
* `RenderContext.drawTile` will always apply viewport matrix and determine if tile is inside the screen by -1...1 results. It is more costly than current approach, however.
That also will solve issue present in #595 that causes Tiles being clipped out, if they are outside of virtual scene viewport, but still inside window visible area.

Now onto implementing a better camera system. I think of two primary paths to take:
1. Add `h2d.Scene.camera` variable, which would dictate additional viewport changes apart from scene viewport.
   * By default camera is either `null` or one that does not perform any extra modifications resulting in backward compatibility of how currently s2d operates.
   * This approach will make it consistent between s2d and s3d, as both scenes will contain a camera which can be manipulated.
   * Downside: Harder to setup multiple cameras (use case: split-screens, picture-in-picture)
   * Downside: Makes it more problematic to implement something like top-most UI and scrolling gameplay area.
2. Rework `h2d.Camera` as a container for one or multiple Camera instances.
   * Camera transforms applied only if actual Camera instance is involved.
   * Closer to how Camera works now, except does not invalidate entire goddamn object tree positions.
   * No downsides from above.

I lean towards second approach. I still hope to implement capability to have multiple cameras (ones that do not require duplicating object tree), but it's most likely something that will be available via API and not as easy to set up premade class. (Or make those premade classes as not part of stock Heaps. They are very situational, and not everyone needs multiple cameras, however just one camera that just works is important.)
As for camera API:
`RenderContext.setCamera(cam)` and `RenderContext.resetCamera()` that would affect viewport matrix. Simple, but there isn't much to add, really.
Modifications also will affect `pushTarget` and `popTarget`, as they set the shader viewport.
Also I will need to test how well it handles filters, as I'm not sure how it would handle it.

Summary of downsides:
* More costly `RenderContext.drawTile`
* Slightly more costly vertex shader for s2d.
* Breaks compatibility with current `h2d.Camera` in any case.

Upsides:
* Coherent and actually usable camera system.
* Setting up multiple cameras is actually possible without duplicating entire object tree.
* Moving camera does not invalidate positions of entire object tree residing in camera.
* Possible to perform complex transformations with rendered content via camera at no cost increase.
* `RenderContext.drawTile` won't have clipping "bug" as described in #595 
* People finally will stop complaining about camera in Discord chat :) 
* I will stress it again: Moving camera won't trigger position invalidation in object tree. And should't in the first place.

I already have a dirty WIP based on PR mentioned 4 times already, which implements the changes before adding camera transform into equation and so far it works well.
RFC, I guess?

**Comment by ncannasse** [comment]
I'm fine with the proposed changes and the fact that it's correctly integrated into the shader transform.

Regarding Camera API, we can either have a specific class in the hierarchy (like h2d.Viewport) that will allow to set multiple cameras, each which its own render zone. Or use directly Scene for that, although I think one might want to have Viewport inside Viewport one day (?)

**Comment by Yanrishatum** [comment]
I'm more inclined to have `h2d.Camera` which can contain one or many `h2d.Viewport` instances. That way viewports will remain completely optional to use and won't interfere with regular rendering in case s2d will be used solely for UI in 3D games.
As for Viewport inside Viewport - I think it's better to disallow adding them to anything but as a child of Scene, as to not overcomplicate the logic.
At the moment, my current WIP implementation looks like that:
* `h2d.Camera` is a container to `h2d.Viewport`. I decided to not implement multiple viewports for now, as that's something that can be implemented later, plus it's rather case-to-case feature.
* `h2d.Viewport` is x/y/scale/rotation transform container that output a matrix mapping to `-1...1` screen space with parent Scene scaleMode applied as to not do it every frame if camera does not move.
* `h2d.RenderContext.pop/pushTarget` are slightly reworked to use same approach as Engine with linked list stack (`TargetTmp`). Also removed `restore` argument on `popTarget`. Sweeping code base I haven't found it used anywhere and not entirely sure why it's even here, because popTarget supposed to restore previous render state, and if passed false, clipper and viewport won't get restored, however render-zone will?
* RenderContext clipper now maps onto -1...1 to check if Tile should rendered or not, resolving issue present in #595 

There's one thing that slipped my attention - Interactives. With proposed implementation, Interactives hitbox areas won't be affected by camera transformations (only by Scene viewport config dictated by scaleMode), which is counter-intuitive to what user expects.
I see next solutions:
* Add a `camera` reference to Interactive, which, when present, will apply it's viewport transformation when checking for hit-test. There is a downside to it, however - this transformation have to be applied each time Interactive is tested. Viewport also will have to hold both screen-relative (-1...1 mapping) and viewport-relative transformations (so Interactives positions will get transformed accordingly)
* Disallow adding Interactives to Cameras.
* Usual "not my problem" path: Just leave it as is and warn user to not use Interactives with viewports.

**Comment by ncannasse** [comment]
I'm curious what are the exact camera/viewport relationship and variables here. It seems strange to be to have to create both a Camera and a Viewport. Would not that be more easy to have only a Camera instance that also define a viewport ?

The problem I can see is that Camera should be allowed on any Object given you might want to have the following:

```
s2d
 | - game world
     |- camera1 (left player)
     |- camera2 (right player)
 | - game ui (common)
```

Another option would be to add Camera support on `h2d.Layers` only, so we can set a camera to operate on a single or a range of layers. It would not be a h2d Object, more like:

```haxe
var cam = new h2d.Camera(layers);
cam.startLayer = 0;
cam.layerCount = 3;
trace(layers.cameras.length);
```

**Comment by Yanrishatum** [comment]
Viewport is transform descriptor, while Camera is a container. E.g.:
```
s2d
 | - camera
 |   | - camera.viewports = [player1, player2]
 |   | - game world
 | - game ui 
```
And by default creating a camera also creates a viewport within it. One camera ultimately can service multiple viewports.
As for having objects that render exclusively on specific viewports - something like `h2d.ViewportObject` which would just return if if it's rendered by viewports it's not supposed to render on. For example, player-specific in-world effects.

If Layers will have cameras, then it'll cause problem with layers within layers, and it would be easier to just restrict it to Scene, since it's already based on Layers. But now that I think about it, it is more robust than how my approach was. I need to think on it more, before giving opinion.

And another thing popping up: If we going to allow masking of viewport, `h2d.Mask` should start regarding already present renderZone, as currently it completely overrides it.

**Comment by zommerfelds** [comment]
Hi all, I just tried to use `h2d.Camera` but it's not working for my case (or I'm not understanding how to use it). The issue is that I would like to specify a zoom value, but if I use `scaleX`/`scaleY`, it scales from the top left. So I'm not able to say "center camera at point X/Y with zoom level S".

In the included Camera2D sample you can observe that the anchor doesn't affect scaling behavior. Could you tell me if this is working as intended? I will have to implement my own mapping function or an extra `h2d.Object` for scaling in the center.

**Comment by zommerfelds** [comment]
Just noticed https://github.com/HeapsIO/heaps/pull/698. I think it will solve my issues.
> Allows for scaling and rotation. (with origin being anchor)
