### ISSUE TITLE
[Feature Request] Support for GPU Path Rendering

### ISSUE THREAD

**Issue by dimumurray** [HeapsIO/heaps#630]
As per [heaps.io discourse topic](https://community.heaps.io/t/future-support-for-gpu-path-rendering-vector-graphics/310): 

> According to an old thread (titled: "**[Is it possible to smooth coarse graphics?](https://community.heaps.io/t/is-it-possible-to-smooth-coarse-graphics/109)**") the current work-around to achieve anti-aliasing for vector graphics is to treat it as a texture; drawing it at twice the intended scale and then shrinking it by 50%. 
> 
> Not really a fan of that technique. Apparently, there is the option of using the GPU to render smooth/anti-aliased vector graphics directly, which promises to offer better fidelity. 
> 
> Found a few papers on the topic that makes the approach seem viable:
> 1. [Massively-Parallel Vector Graphics](http://w3.impa.br/~diego/projects/GanEtAl14/)
> 2. [ Efficient GPU Path Rendering Using Scanline Rasterization](http://kunzhou.net/zjugaps/pathrendering/)
> 
> Are there any plans to support/implement GPU based path rendering in Heaps at some point in the (preferably near) future?

**Comment by ncannasse** [comment]
Sorry but we don't accept such time costly feature requests atm ;)
