### ISSUE TITLE
Haxe compile.xml: Assertion Failed

### ISSUE THREAD

**Issue by briguyjm** [HeapsIO/heaps#631]
I am using HashLink v1.9 (built from the GitHub v1.9 source code release) and the 4.0 rc1 Haxe binary downloaded from the Haxe website. When compiling the hello world tutorial for Heaps, I get the following error:

```
haxe compile.xml
File "_build/src/context/common.ml", line 429, characters 21-27: Assertion failed
```
compiling with the Haxe version that is included with Ubuntu, I get no errors, but can't run the hello.hl file because the version of haxe is too old. This is the error I get when trying to run the hl file:
```
hl hello.hl
Found version 1 while HL 1.9 supports up to 5
Unsupported bytecode version
```

Is there any way to get Haxe 4.0 rc 1 to compile the file? I have the download folder in my home directory with a symlink to my `~/bin` folder.

**Comment by ncannasse** [comment]
Haxe 4.0 RC1 is too old, you should use RC2 or (very soon to be released) RC3.

**Comment by briguyjm** [comment]
Using RC3 I get this error:
```
File "_build/src/compiler/main.ml", line 272, characters 172-178: Assertion failed
```

**Comment by ncannasse** [comment]
Are you using the RC3 haxe std library as well?
