### ISSUE TITLE
Idempotency of Object.setTransform

### ISSUE THREAD

**Issue by Yann-P** [HeapsIO/heaps#635]
I was playing around with matrix transforms in s3d.scene.object using the [setTransform](https://github.com/HeapsIO/heaps/blob/master/h3d/scene/Object.hx#L772) function.

I noticed that if I called it two times in a row with the same matrix, the scale wasn't consistent.
I noticed that[ it resets the scale of the input matrix](https://github.com/HeapsIO/heaps/blob/master/h3d/scene/Object.hx#L780), for the purpose of extracting the rotation into a quaternion.

To avoid side effects on the input matrix a clone should be made. Or if this is intentional it should be documented

**Comment by ncannasse** [comment]
Right, it should be fixed. I think @thretaller added it ?

Le mar. 2 juil. 2019 06:53, Yann Pellegrini <notifications@github.com> a
écrit :

**Comment by trethaller** [comment]
Yes the modification of the input matrix is not great, I'll correct it

**Comment by trethaller** [comment]
fixed by https://github.com/HeapsIO/heaps/commit/e267469ca3be7fc77a2df0d5c8f68e0226c067bb
