### ISSUE TITLE
FBXs from Houdini produce errors

### ISSUE THREAD

**Issue by melMass** [HeapsIO/heaps#641]
Hi,

Whatever FBX version I input I have the following error:
- A simple mesh with normals works
- A skinned character produce the following error:
```ruby
'mikktspace' n’est pas reconnu en tant que commande interne
 Uncaught exception Failed to called 'mikktspace' executable required to generate tangent data. Please ensure it's in your PATH
```
- A simple mesh with Cd:
```ruby
heaps/1,6,1/hxd/fmt/fbx/Data.hx:35 
characters 5-10 : Uncaught exception LayerElementColor does not have ColorIndex (ColorIndex not found)
```

EDIT: So after trying a few other cases I can confirm those statements. It seems that mikktspace needs to be compiled to C which is not done while installing heaps with either haxelib git or haxelib install.
Can you elaborate on how to build Mikktspace ?

**Comment by ncannasse** [comment]
In order to correctly process the normals in tangent space, you need either to run the fbx-to-hmd convert from hashlink or to get the mikktspace tool. It can be built from heaps/tools/mikktspace or downloaded from https://github.com/HeapsIO/heaps-tools/releases

**Comment by ncannasse** [comment]
(the commit should close the LayerElementColor error as well)

**Comment by melMass** [comment]
Funny enough on Mac Mikktspace does not seems to be required (for the same fbx)
