### ISSUE TITLE
How to prepare envmaps ?

### ISSUE THREAD

**Issue by melMass** [HeapsIO/heaps#642]
Hi,

When I use cmft cli to generate cubemaps from latlong (**posx,negx,posy,negy,posz,negz**), there is an orientation issue, at first I thought it was the order in which I assigned the planes, but no matter what the problem **persist**. It's then that I realized the sample cubemap was different and some of it's planes where rotated.

How do you generate such a cubemap ?
And is it possible to solve this simply in the shader ?

Also how can the `renderer.exposure` affect the envmap aswel ?

Thanks
![cmft_issue](https://user-images.githubusercontent.com/7041726/61081848-8ba4ef00-a428-11e9-820a-f1f0370d1464.png)

**Comment by melMass** [comment]
For the envmap I discovered those flags. This is the combinaison required by the default heaps env shader:

### Latlong to Cubemap
```bash
cmft --input env.hdr --filter none --negZrotate180 --posXrotate270 --negXrotate90 --outputNum 1 --output0 out_env --output0params tga,bgr8,facelist;

```

**Comment by melMass** [comment]
This is solved with the command I posted earlier but I'd love to know how to affect the Env Shader... I would like to be able to rotate it which I think is also related to shaders

**Comment by ncannasse** [comment]
Sorry for the late answer. For env maps you can either have a cube map or a 2x1 "projected" texture that will be rendered to a cubemap. ATM we don't allow envmap rotation but that's something we are considering adding.
