### ISSUE TITLE
Why is MP3 support disabled by default in HL?

### ISSUE THREAD

**Issue by infidel-** [HeapsIO/heaps#643]
I'm speaking about this:

https://github.com/HeapsIO/heaps/blob/f3f5d20818c8dc0f9c53807c4ef36a4edb8dcc19/hxd/res/Config.hx#L73

It's not documented anywhere and I don't see any discussion related to this.

**Comment by Yanrishatum** [comment]
See https://github.com/HeapsIO/heaps/pull/514#issuecomment-450833562 for reasoning behind disabling mp3 file listing in Res for HL. tl;dr: Support is not exhaustive (external library, which seem to have some issues decoding some of the files according to discord chat), and ogg/wav is preferred over mp3. This flag primarily for cases when using ogg/wav is not convenient for workflow. Regarding documentation - yes, it isn't documented, as pretty much all other flags of Heaps. I didn't had time to do a PR to wiki to add the page that at least tries to document those.

**Comment by infidel-** [comment]
Hmm, okay, thanks. What kind of issues specifically do I have to look out for? I'm also thinking that MP3 is more convenient instead of having separate OGG tracks for HL.

**Comment by Yanrishatum** [comment]
HL implementation uses [minimp3](https://github.com/lieff/minimp3) library, and from what I've seen have issues when working with non-44100 files. I'm not sure if it's minimp3 fault or Heaps implementation however.

**Comment by infidel-** [comment]
Okay, thanks for clarification, thankfully, I only use 44.1k files.
