### ISSUE TITLE
js.lib.Uint16Array should be js.lib.Float32Array

### ISSUE THREAD

**Issue by miriti** [HeapsIO/heaps#648]
I'm trying to compile the "HelloWorld" example and getting error:

```/home/michael/haxelib/heaps/1,6,1/h3d/impl/GlDriver.hx:1136: characters 38-107 : js.lib.Uint16Array should be js.lib.Float32Array```

May it be the case that I'm doing something wrongly? 

Environment:
Haxe Compiler 4.0.0-rc.3

**Comment by Yanrishatum** [comment]
It was already fixed in #646. It due to RC3 having some breaking changes in JS TypedArray externs implementation.

**Comment by Yanrishatum** [comment]
No longer relevant, can be closed. @miriti
