### ISSUE TITLE
Input normal characters in h2d.TextInput not working on JS target

### ISSUE THREAD

**Issue by gordonshamway23** [HeapsIO/heaps#656]
Hello everyone,

today i found some problems with h2d.TextInput when compiling to Javascript target. I started several samples of heaps containing text inputs and was not able to input normal characters. Using backspace and left and right keys are working. I tested it in chrome and firefox (most recent version) and also with the latest heaps version as well as with the last release of heaps (1.6.1 i think). The problem seems not to be related with heaps. So i debugged a little and maybe found the reason. 
The keypress event is not fired in hxd.Window.js.hx:

```haxe
	function onKeyPress(e:js.html.KeyboardEvent) {
		...
                //actually never called :( 
                // and therefore no ETextInput event is generated
	}
```

The listener is registered in the constructor in hxd.Window.js.hx:
```haxe
              element.addEventListener("keypress", onKeyPress);
```

According to the docs of CanvasElement "keypress" events are deprecated:
[https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event](url)

Looks like the event is no longer working in newest browers, even if it's only deprecated, not removed. The docs suggesting using keydown and beforeinput events to replace keypress functionality. I am working on a fix and will propose a PR soon.

Have a nice day.

**Comment by ncannasse** [comment]
As far as I know, keypress events are still correctly supported on canvas with latest browsers. There is no current alternative to keypress as it will handle all shift/alt/ctrl modifiers to translate the key into a proper keyboard-specific character.

If you have no keypress event being fired on the canvas, it means it must be focused first (click on it). Eventually add it a tabindex="0"

**Comment by gordonshamway23** [comment]
Ok, i tested a little more and was not able to get the keypress events correctly working. Neither the tabindex="0" attribute on the canvas element nor clicking the canvas (which i obviously must have done when focusing the TextInput) does help. But i was able to find the actual problem. Calling preventDefault in the keydown eventhandler does prevent the keypress event to fire.

```haxe
	function onKeyDown(e:js.html.KeyboardEvent) {
		var ev = new Event(EKeyDown, mouseX, mouseY);
		ev.keyCode = e.keyCode;
		event(ev);
		if( !propagateKeyEvents ) {
			e.preventDefault(); //this line is actual preventing onKeyPress() 
                                                      // eventhandler being called
			e.stopPropagation();
		}
	}
```

I started a discussion on stackoverflow to confirm that this is intended behavior, and it seems it is.
Please see: 
[https://stackoverflow.com/questions/57400729/does-preventdefault-in-keydown-event-prevent-a-following-keypress-event](url)
In the answer the following doc is referenced:
[https://www.w3.org/TR/uievents/#keydown](url)
There you can see that a default action of the keydown event is the keypress event, which mean that calling preventDefault() in the onKeyDown() handler actually prevents keypress events from happening. 

So i would say e.preventDefault() should actually be removed. What do you think?

I could also set propagateKeyEvents indirectly to true, by giving the canvas element a globalEvents="1" attribute, but i don't want to. I think that stopPropagation() is actually very useful to not let the event bubble up and eventually run the risk that the browser is handling the key event.
