### ISSUE TITLE
Text drop shadow seems to be missing a setter

### ISSUE THREAD

**Issue by back2dos** [HeapsIO/heaps#659]
The write access to [h2d.Text::dropShadow](https://github.com/HeapsIO/heaps/blob/8220d5636e39406330bad482acbf25d002527749/h2d/Text.hx#L17) is `default`, while it probably should have a setter with a `rebuild()` in it. Is this a simple omission, or is it by design?

**Comment by Yanrishatum** [comment]
No it shouldn't. Because `dropShadow` have nothing to do with invalidation of glyph cache. It only affects their rendering, e.g. renders them second time. See `draw` method: https://github.com/HeapsIO/heaps/blob/8220d5636e39406330bad482acbf25d002527749/h2d/Text.hx#L123-L137

**Comment by back2dos** [comment]
Ok, fair enough, thanks ;)
