### ISSUE TITLE
compile mikktspace on osx

### ISSUE THREAD

**Issue by varadig** [HeapsIO/heaps#669]
Can someone help me to compile mikktspace on a proper way, with gcc?
I tried to rewrite to gcc from [build_msvc.bat](https://github.com/HeapsIO/heaps/blob/5a814afef7263556a105ef373527df7773d26363/tools/mikktspace/build_msvc.bat), but I don't know (and don't find) where to point the %HASHLINK% and the %HASHLINK_BIN% env variable.

Maybe an osx(unix) build script would be good

**Comment by varadig** [comment]
Thanks @ncannasse !

here is the script... maybe someone else is need to:


[build_gcc.sh.zip](https://github.com/HeapsIO/heaps/files/3609048/build_gcc.sh.zip)

**Comment by peteshand** [comment]
So what was the solution here? I'm facing the same issue:
/bin/sh: mikktspace: command not found

@varadig What dir are you running build_gcc.sh in?

**Comment by ncannasse** [comment]
It's  heaps sources tools/mikktspace

**Comment by peteshand** [comment]
Hey. Thanks for the quick reply.

Yeah that's the location I've used, however I got the following error
```
clang: error: no such file or directory: 'out/main.c'
```
Is there any documentation on this? 
Would it be possible to have this built into heaps rather than having to build from source? or would there be licencing issues.

**Comment by ncannasse** [comment]
You first need to run haxe mikktspace.hxml -D no-compilation
Having this built into heaps would require porting the C code into Haxe.

**Comment by ncannasse** [comment]
I have added a Makefile that should work for OSX/Linux. Requires hashlink installed, please try.

**Comment by peteshand** [comment]
Cool, thanks for the info. I'll give it a go tomorrow morning.

**Comment by peteshand** [comment]
Thanks, oh yes.. now that you've pointed out that I need to run mikktspace.hxml it's seems like an obvious oversight on my behalf. All works once I add this step.

I had a few issues with the Makefile.. I've submitted to pull request with some fixes.

Yes porting the C code would be a pain.
