### ISSUE TITLE
[Request] Callback on x,y changes on h2d.Object

### ISSUE THREAD

**Issue by zapparo** [HeapsIO/heaps#674]
Something like this
`	function set_x(v) {
		posChanged = true;
		onXChange(v);
		return x = v;
	}`
`	function set_y(v) {
		posChanged = true;
		onYChange(v);
		return y = v;
	}`

I've tried this idea of having an external sprite batch that has elements that behave like they are children of different objects but I need to know when the object changed position so it can sync the elements it "contains".

**Comment by Yanrishatum** [comment]
Adding function call for each coordinate change defeats the whole purpose of just marking position as dirty and would eat into performance. It's quite questionable feature. 
If you need to do such thing, you need to override `calcAbsPos`, which calculates absolute matrix transformation of an Object and called only if `posChanged = true` during `sync` phase. Here you can do whatever you want with callbacks. Additionally, in your idea, in case of objects changing position more than once per frame and not only in one axis will result in a bunch of callback calls, while in reality you only need to sync those once per frame.

**Comment by zapparo** [comment]
@Yanrishatum thanks! that works really well, I missed calcAbsPos was trying to use syncPos but that doesn't get called every frame.
