### ISSUE TITLE
onResize event is not received by Window.hl.hx sometimes (hlsdl)

### ISSUE THREAD

**Issue by Fl0xer** [HeapsIO/heaps#679]
We have the issue in a Northgard game, in hlsdl. Only ingame, it works fine in the menus.

**Comment by ncannasse** [comment]
Strangly, the Window.hl.hx does not receive the Resize event at all

**Comment by jefvel** [comment]
I think this has been fixed here https://github.com/HaxeFoundation/hashlink/commit/1d7bab2505685b2232f822c58abe5518f643e8b1
