### ISSUE TITLE
[RFC] Remove legacy Lime backend

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#682]
Lime backend was abandoned long ago, but Heaps contains substantial amount of code that refers to it, potentially confusing people that it actually does support it. Quick sweep over history showcases that last commit that refers to lime was all the way back in the beginning of 2017. 
I propose removing that legacy code outright (as well as nme/openfl parts), since there are no plans on maintaining it anyway.

**Comment by ncannasse** [comment]
Sure
