### ISSUE TITLE
hxd.snd.Channel.pause is not actually pausing the sound

### ISSUE THREAD

**Issue by deepnight** [HeapsIO/heaps#691]
Demo: https://github.com/deepnight/lab/blob/musicPause/src/Main.hx
Git: https://github.com/deepnight/lab/tree/musicPause

Pressing SPACE pauses the music, but if you press SPACE 2 or 3 times, the music actually starts again at a different point and you can hear sound glitches.

On JS target, it's worse, because the music loops on the first 1s as soon as the pause goes false.

**Comment by Yanrishatum** [comment]
Could you check if JS issue persist with #685 also?
I suspect on JS there's a bug in seeking somewhere that causes it to fill just first second in the buffer. Does it reproduce with mp3 only, or with ogg as well (using `stb_ogg_sound` library)?

**Comment by deepnight** [comment]
I couldn't get the @Yanrishatum heaps version to build on my haxe version (v4 RC5).

 - **HL SDL + Ogg**: same issue, when I resume a paused music, it jumps a little bit further everytime. I also get a few audio glitches sometime when pausing/resuming..
 - **HL DirectX + Ogg**: same as SDL
 - **HL SDL/DirectX + MP3**: for some obscure reason, hxd.Res cannot import a MP3 file: 
  `var myMusic = hxd.Res.music; // where music is an MP3 file`
  Compiler error:
  `Class<hxd.Res> has no field music`
 - **HL SDL/DirectX + WAV**: same as SDL
 - **JS + MP3**: resuming the music goes into a short loop (ie. the music starts to play, then loops infinitely on the first few milliseconds)
 - **JS + Ogg**: no music at all, I just get the following error in console: `RangeError: offset is outside the bounds of the DataView` (see stack in Firefox console below)

![image](https://user-images.githubusercontent.com/1671695/67101746-80e5bd00-f1c2-11e9-8bb7-acdb01c66858.png)

**Comment by deepnight** [comment]
Fun fact: if instead of pausing my music, I just put the volume to 0, then getting it back to 1 when resuming, I get the same sound glitch.

By the way, I'm using:
 - Haxe 4.0.0-rc.5+4a745347f
 - heaps (repo version: https://github.com/HeapsIO/heaps)
 - hlopenal 1.5.0
 - hlsdl 1.10.0
 - hldx 1.10.0

**Comment by Yanrishatum** [comment]
To enable mp3 files in Res - add `-D heaps_enable_hl_mp3`. Also current version may sound very broken, and fixes are in my PR (which you for some reason could not build). Ogg on JS is same - fixed in my PR. Hm. Does #683 builds for you? It does not include WebAudio for JS, but at least fixes issue I mentioned above.

(Also maybe show error which Haxe gives on trying to build my PR? ;) )

**Comment by deepnight** [comment]
I managed to merge your #685 branch into my local heaps repo (synced with latest heaps.io version).

 - **HL + Ogg**: same as above: pausing/resuming moves the playback cursor further every time
 - **JS + Mp3**: pause now works fine, but you can hear subtle sound glitches every time you pause/resume (not a big deal). The music also starts with some delay: on Firefox it skips the first few seconds, and on Chrome, the music starts at the beginning, but with some delay.

**Comment by ncannasse** [comment]
Music decoding in browser is a mess, because you can't get immediately the
data, I think we fixed this by waiting for the data to be ready before
actually starting the channel, but I haven't checked JS sound support for
some time (haven't done LDs recently :D )

**Comment by deepnight** [comment]
> haven't done LDs recently
That's part of the issue, I think 🤔 :trollface:

**Comment by ncannasse** [comment]
The actual issue is JS being shitty at sound API :) But yes, I don't have much time to focus on JS sound support as I don't use it at work (not like 3D rendering for instance). Hopefully it seems @Yanrishatum is much more involved.

**Comment by deepnight** [comment]
Anyway, the issue is the same with HL target.
You can test it here: https://github.com/deepnight/lab/tree/musicPause
The redist folders are HL and JS builds

**Comment by Yanrishatum** [comment]
I mean, that's why I have all those PRs that at least try to make sound more bearable. :) And why I gave up on fixing hack job or AL emulation and just made custom WebAudio. ;) It's not good, but way better.
Also Deepnight, if you use Discord, jump in to #heaps channel (iirc there's a link in readme?), we would appreciate more people with good knowledge of engine. ;) I'm going to check out your test case with my branches and see if I can do something about it.

**Comment by Yanrishatum** [comment]
Half-fixed the issue. It should be fine on HL now with #693 
Reason was rather simple:
1. `Manager.releaseSource` calls `driver.stopSource`, which should reset `sampleOffset` to 0, so when it started - there won't be any skips. 
2. Then it calls `driver.unqueueBuffers` on each queued buffer. 
3. `Driver.unqueueBuffer` increments `sampleOffset` - cause of sounds skips.

Solution - added `source.playing` check.
Alternative solution probably would be to reset sampleOffset to 0 when doing `Driver.playSource`. Gonna check, if works - would be better solution, as it avoids extra check when unqueuing.

**Comment by deepnight** [comment]
❤️

**Comment by Yanrishatum** [comment]
Please recheck with #711 I tested it locally and it seemed to fix pausing issue on JS. (If it's fixed, this issue can be closed after merge)

**Comment by deepnight** [comment]
It seems to be fixed for me, I updated my libs to support latest update (https://github.com/deepnight/deepnightLibs).
Thank you!
