### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by Wolfman13** [HeapsIO/heaps#704]
I'm running Linux Ubuntu 19.10. Haxe: 4.0.0+ef18b627e.
I tried running HelloHashLink example but when I run the example I end up with this error:

` ERROR : Error: Dynamic Linking Error: /lib/x86_64-linux-gnu/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference`

`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/ffi/lib/dynamic_library.js line 74 column 11`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/ffi/lib/dynamic_library.js line 70 column 31`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/ffi/lib/library.js line 45 column 12`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/adapter.js line 9946 column 27`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/adapter.js line 429 column 10`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/adapter.js line 153 column 29`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/vscode-debugadapter/lib/debugSession.js line 342 column 22`
`Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/vscode-debugadapter/lib/protocol.js line 97 column 38`
`Called from inStream.on (/home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/vscode-debugadapter/lib/protocol.js line 18 column 44)`
`Called from events.js line 182 column 13`

**Comment by Wolfman13** [comment]
I downgraded to Linux Ubuntu 18.04 LTS, still get the same bug:
`ERROR : Error: Dynamic Linking Error: /lib/x86_64-linux-gnu/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/ffi/lib/dynamic_library.js line 74 column 11
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/ffi/lib/dynamic_library.js line 70 column 31
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/ffi/lib/library.js line 45 column 12
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/adapter.js line 9946 column 27
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/adapter.js line 429 column 10
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/adapter.js line 153 column 29
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/vscode-debugadapter/lib/debugSession.js line 342 column 22
Called from /home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/vscode-debugadapter/lib/protocol.js line 97 column 38
Called from inStream.on (/home/jeanjacques/.vscode/extensions/haxefoundation.haxe-hl-0.8.0/node_modules/vscode-debugadapter/lib/protocol.js line 18 column 44)
Called from events.js line 182 column 13`

**Comment by Wolfman13** [comment]
I tested and I can still build the code to a .hl file and then run that file using my terminal I just can't do the F5 setup like how it was suggested in the tutorial

**Comment by Yanrishatum** [comment]
From errors you posted it's clearly an issue between hashlink debugger extension and your OS. I'm pretty sure that if you'll try to launch HL debugger with non-heaps hl app you'd get same result.
Please refer to correct repo: https://github.com/vshaxe/hashlink-debugger/issues

**Comment by Wolfman13** [comment]
Thank you, I shall do so

**Comment by Wolfman13** [comment]
The problem was with the fact that I had the snap version of VSCode installed. Solution was found here: [https://github.com/vshaxe/hashlink-debugger/issues/48](url)
