### ISSUE TITLE
Request/PR: Macro to disable Window resizing.

### ISSUE THREAD

**Issue by Pauldg7** [HeapsIO/heaps#715]
I'd like to start by saying I looked for a feature request template, but couldn't find one. If there is one and I'm blind I would love to correct this request.

What: Add a macro "windowFixed" that would disable SDL and DirectX (DX) window resizing.

How: [Hashlink pr 211](https://github.com/HaxeFoundation/hashlink/pull/211) added the ability to customize SDL/DX flags at creation of the window. Heaps right now is just using the default SDL/DX flags which include a window resizable flag. By adding a macro I can take the default flags and add or remove the resizable flag if the macro exists. 

Why: I'm often testing and developing on a single 2K monitor, often with out intending to I can accidentally resize the window ever so slightly and it makes the game look strange.

Who: Besides me, I've noticed a couple people ask the same question if you can disable window resizing. I've also seen a question on the forums (I think it has been deleted), and there was second [pr put in to add a windowFixed macro](https://github.com/HeapsIO/heaps/pull/696).

Pull Request: 
https://github.com/HeapsIO/heaps/pull/678
I've come up with a solution that works for me, but could use some feedback to make sure it is up to standards.

**Comment by ncannasse** [comment]
Thanks!
