### ISSUE TITLE
[RFC] Default Text.letterSpacing to 0

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#720]
Currently it's at 1px, and was justified by legacy font format, e.g. Littera fonts, which do not provide advance values. Actually decent format (BMF) provides advance of the glyph, removing the need in that offset and actually said offset starts to create problems, as it creates spacing where there should be none. As a result working with newer and preferred font formats (especially after fontgen tool implementation) it is a hindrance, as that value have to be adjusted for every single text instance.
Proposal:
* Set `Text.letterSpacing` to 0.
* To preserve spacing for Littera fonts - add 1 pixel to advance during parsing of glyphs.
* Because of that, bfnt cache in .tmp should be deleted for littera fonts to receive proper pixel advances.

Now more free-worded background reasoning.
Every single goddamn time I have to either keep in mind that spacing is 1 by default and reset it to 0 each time I create text instances or make `Util.text` method that wraps this operation. That is annoying as hell and was annoying ever since implementation of adequate BMF format support. That inferior garbage format should not create issues for people who use intended ways to generate fonts. I asked Threthaller if that variable is relied on being 1 by default, and it looks like no, apart from providing spacing for littera fonts.

**Comment by ncannasse** [comment]
TBH that does not sound like a very pragmatic decision. I understand that the letterSpacing = 1 by default is inherited from old implementation but changing that will most likely break all applications that either set letterSpacing or forget to delete their .tmp

@trethaller any insight ?

**Comment by Yanrishatum** [comment]
I don't propose remove the variable outright, only default it to 0, so it won't affect apps that manually set it.
And for tmp, I actually can suggest a solution. Right now tmp cache uses file timestamp and file md5 to check if it should be rebuilt. I'd propose adding another check - convert version. As in:
Converts would now have `version` variable that would report the most recent version of the convert and which is incremented each time convert would update and invalidate old cache (for example new format version without keeping old format compatibility - just rebuild the cache)
If versions mismatch, it converts files regardless of hash and timestamp. With this, if changes like that occur that affect converted files, it would be easier to mitigate them, as Heaps would automatically invalidate those instead of having people remember to delete tmp.
As a bonus i'd throw in `-D no-cache` flag that disables cache outright and always forces rebuilding of files. It's useful when writing custom convert, with input file not changing, but format still being in development, as you don't have to delete file in tmp each time.

**Comment by trethaller** [comment]
I think projects relying on letterSpacing=1 can subclass Text and easily preserve the previous behavior once and for all.

As for cache invalidation, the new spacing=0 will most likely be easy to spot so I don't think people would "miss it", I think the bigger problem is to communicate to users that deleting .tmp will fix it. Maybe include a note in the commit log ? They'll probably end-up asking @Yanrishatum on Discord. 

It's not the first time we've had format changes requiring deletion of .tmp, so having a version number allowing this is probably a good long term thing.

As for a `-D no-cache`, I guess it would apply to all files and only be practical on very small samples using only the very files which format you are currently debugging ?

**Comment by Yanrishatum** [comment]
Well, if we can just skip the involvement of user when doing this change - it's better do so.

Well, `no-cache` would apply to everything (as name implies, but now that I think about it - better name would `no-res-cache`?), and it's purpose is exactly for cases of implementing new/updating existing Converts, or debugging stuff like "why the heck model exports wrong and I'm tired of deleting hmd file each time" ;)

**Comment by ncannasse** [comment]
Ok for letterSpacing change PR using converts version.

@trethaller you are now volunteer to handle transition on Darksburg and Northgard ;)

**Comment by kLabz** [comment]
Is this being done? I actually use a Text subclass that does `letterSpacing = 0` (and some other minor things) to avoid this additional space.

**Comment by ncannasse** [comment]
I agree we can change text implementation so letterSpacing is 0 by default.

**Comment by Yanrishatum** [comment]
This is pending since december: https://github.com/HeapsIO/heaps/pull/727
