### ISSUE TITLE
Realloc h3d.mat.Texture.fromColor() with hover

### ISSUE THREAD

**Issue by D0pu** [HeapsIO/heaps#723]
When the MemoryManager cleans a texture created by Texture.fromColor() and this texture is not visible just after the clean, this texture is not displayed anymore.

I am using Domkit, I have a flow with one background A by default and one background B when it is hover. If the MemoryManager cleans the texture B, the background B is not visible anymore. If the MemoryManager cleans the texture A, the background A is still visible.

**Reproduction :**
- Create a flow with two backgrounds switching thanks to hover
- Hover once the flow
- Force to clean **all** textures
- Re-hover the flow

**Comment by ncannasse** [comment]
I could not reproduce with standalone example but I think I understand what's going on : realloc calls clear which switch current target, but there might be some cases like if we have set a render zone that the clear will simply no work.
