### ISSUE TITLE
HtmlText issue

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#725]
With the following text, `"40% chance qu'elles soient <font color="#EEEEEE"><b>désorientées</b></font>."` and the appropriate font/maxWidth, the text field display that:

![image](https://user-images.githubusercontent.com/1022912/69817209-67408800-11fa-11ea-86d5-955072b8f924.png)

Whereas it should have a space before `désorientées` and not allow the break between the word and the final `.`

**Comment by ncannasse** [comment]
Ping @Yanrishatum

**Comment by Yanrishatum** [comment]
Does it reproduce with #553? It should regard trailing spaces and word-wrapping have to account for such cases. PR's technically ready, but I haven't had time to test this PR for bugs, so I haven't pinged you regarding it, plus #703 can invalidate pretty much all work done in it, as the core method of operation of Text would change.

**Comment by Yanrishatum** [comment]
Update: It is indeed fixed in my PR, but I also found another bug that makes word-wrapping on last word broken.

**Comment by ncannasse** [comment]
Tell me if you are planning to work on things there or else I'll look into fixing this particular issue, but better avoiding doing twice the work.

**Comment by Yanrishatum** [comment]
Should be resolved by HtmlText PR
