### ISSUE TITLE
Working with premultiplied alpha

### ISSUE THREAD

**Issue by lbergman** [HeapsIO/heaps#726]
When loading png files with alpha premultiplied, alpha blended areas will look dark.

Both Pixels and Textures has an AlphaPremultiplied flag, but it is only set and unset, and never checked it seems like.

Using this shader we get an identical result comparing a image saved in TexturePacker with default 'Clear transparent pixels' when saving with PMA instead:
`color.rgb /= mix(1.0, pow(color.a, 2.2), ceil(color.a));`

With an uncompressed texture one can set GL.UNPACK_PREMULTIPLY_ALPHA_WEBGL instead, but it seems it doesn't work with compressed textures and only exists for WebGL, so no help for other targets or when using basis :(

I guess one needs to ensure that a flagged texture automatically apply a shader to correct, but not that confident in finding the best way to handle that in heaps, hence making an issue instead of an MR in the hopes of some advice :)

**Comment by ncannasse** [comment]
Yes AlphaPremultiplied is a leftover from Flash BitmapData which had this restriction. I think it should be entirely removed as it's very hard to handle it correctly in shaders, and no platform today would benefit from using it.

**Comment by lbergman** [comment]
Thanks, the reason I need it is for using PVRTC on iOS, which only seems to work with PMA. 

I will keep looking at a way to handle it since we really like using basis textures to improve download times and memory usage.

**Comment by lbergman** [comment]
Decided to give up on basis on iOS, indeed to much of a headache to deal with PMA, so closing this.
