### ISSUE TITLE
Buffer leak in snd.Manager

### ISSUE THREAD

**Issue by trethaller** [HeapsIO/heaps#729]
When `start` or `end` arguments are passed to `snd.Manager.getSoundBuffer`, there is a risk of leak as we override the entry in `soundBufferMap`. This is verified by `soundBufferCount` increasing without limit, while `soundBufferMap`/`soundBufferKeys` keep a constant size.

**Comment by ncannasse** [comment]
Blamed on @D0pu de132252b4a49650925d6538ef5446b39ee8fe65 ;)

**Comment by ncannasse** [comment]
I have a working fix but I'm not satisfied with the API so I want to discuss it tomorrow morning for a change that will fix this more properly.

**Comment by ncannasse** [comment]
Was fixed
