### ISSUE TITLE
Window and fullscreen revision

### ISSUE THREAD

**Issue by jefvel** [HeapsIO/heaps#730]
Related comments https://github.com/HeapsIO/heaps/pull/721#issuecomment-560089506

There should be a way to change the window title during runtime, instead of only being able to set it using the `windowTitle` define.

Currently it is only possible to switch between borderless fullscreen and windowed mode. It would however be good to be able to switch between exclusive fullscreen and windowed fullscreen.

For that, should there be a new function in `Window` called `setWindowMode` or similar, or should the `setFullscreen` function take a second, optional parameter `fullscreenMode` that defaults to `Borderless`?

**Comment by Yanrishatum** [comment]
For title: I agree that it should be exposed in Window instance as a property.
For fullscreen modes:
I would go with `public var windowMode(default, set):WindowMode` with adding `@:deprecated` to old fullscreen bool switch. Major point is that JS only have "borderless" fullscreen (and Flash if it's still relevant), while both HL targets allow both exclusive and borderless modes. In that case both modes would result in the same behavior - just fullscreen.

**Comment by jefvel** [comment]
added those things here: https://github.com/HeapsIO/heaps/pull/732
