### ISSUE TITLE
Change Tile FlipX and FlipY to Bools instead of functions

### ISSUE THREAD

**Issue by jefvel** [HeapsIO/heaps#736]
Currently the `Tile` class contains the functions `FlipX` and `FlipY` for flipping the tile. How it works now makes it a bit tricky to check if the tile has been flipped, for example making a 2d sprite face left or right depending on its velocity.

It would be more convenient if the functions were boolean properties instead.

**Comment by ncannasse** [comment]
As long as changing it also updates the underlying UV properties I think it's ok

**Comment by Yanrishatum** [comment]
I'm not sure making them properties is a good idea. 2 new fields on each Tile instance with questionable gain. I always thought of Tile as a primitive that holds the size/UV information on a texture. Flipping is something that most of the time is not required and how it works right now makes sense - one call flips the UV. When you need to know if it was flipped or now is case-specific, and most likely you can just store that `flipped` variable in user code. (Also for platformers - it's not always even need vertical flip, only horizontal)

**Comment by ncannasse** [comment]
We could detect flipping based on u1 < u2

Le jeu. 12 déc. 2019 à 04:04, Pavel Alexandrov <notifications@github.com> a
écrit :

**Comment by Yanrishatum** [comment]
Then no objections. But I'd still keep the flip toggle methods available.
