### ISSUE TITLE
PBR Normal Map & Specular Map crash on OSX

### ISSUE THREAD

**Issue by melMass** [HeapsIO/heaps#737]
Hi,

Whenever I try to use normal map on **OSX** in PBR in both **Hide**, where it simply fills neither the normal map or specular map slots of the material upon file selection, and also in **a standalone heaps project**:
```haxe
var tex = hxd.Res.asphalt_diffuse.toTexture();
var mat = h3d.mat.Material.create(tex);
mat.normalMap = hxd.Res.asphalt_normal.toTexture();
```

Is this a known issue? Do you know if I can use another shader to support PBR?

Thanks

M

**Comment by ncannasse** [comment]
What crash do you get ?

Le jeu. 12 déc. 2019 à 06:49, Mel Massadian <notifications@github.com> a
écrit :

**Comment by melMass** [comment]
When using HL and heaps it's simply locks upon start and never runs.
In hide if I manually edit the .prefab in a text editor and set `normalMap` prop it throws:
![image](https://user-images.githubusercontent.com/7041726/70755016-06a46580-1d39-11ea-99f6-64bde2cfdb45.png)

**Comment by ncannasse** [comment]
You need a tangent in your model primitive in order to apply a normal map.

Le jeu. 12 déc. 2019 à 23:42, Mel Massadian <notifications@github.com> a
écrit :

**Comment by melMass** [comment]
Thanks, how do you go about generating your tangents for your hide assets ?

**Comment by ncannasse** [comment]
Tangents are part of geometry they need to be exported with your 3d editor
into fbx

Le ven. 13 déc. 2019 à 07:28, Mel Massadian <notifications@github.com> a
écrit :

**Comment by melMass** [comment]
Oh ok, I will try from an existing fbx.
I was using generated geometry in both cases (adding a box in my Hide's prefab, and making a mesh from code in the HL one)

Thanls

**Comment by melMass** [comment]
I've tried quite a few things and I can't fix the error.

Can you tell me how you generate those tangents in your DCC?
My model has UVs & Normals, I have access to Maya, Houdini, Blender or C4D but if you use something else it will still help.

**Comment by ncannasse** [comment]
How do you add your model to your scene and what error do you get now ?

**Comment by melMass** [comment]
In hide, the UI does not allow me to add the normal map, it does ask for a file but does not fill the normalMap prop. If I edit the prefab to explicitly set the normal map it crashes with the popup I screenshot in my third post.

in Heaps:


```haxe
class Element {
 public var obj:Object;
 public var material:h3d.mat.Material;
 public var interaction:Interactive;
 public var cache:h3d.prim.ModelCache;
 public var pbrValues:h3d.shader.pbr.PropsValues;

 public function new(fbx:hxd.res.Model) {
		cache = new h3d.prim.ModelCache();
		obj = cache.loadModel(fbx);
                pbrValues = new h3d.shader.pbr.PropsValues(0.3, 0.3);

		material = obj.getMaterials()[0];
                material.mainPass.addShader(pbrValues);
		material.color = theme.GEO_COL;
		material.shadows = true;
		material.mainPass.enableLights = true;
  }
}

```

And here is the sample fbx out of houdini:
[shader_cloth.fbx.zip](https://github.com/HeapsIO/heaps/files/3963893/shader_cloth.fbx.zip)

**Comment by ncannasse** [comment]
I think the problem comes from HMD optimization : we only build tangent data if the model has a normal map texture applied in the FBX itself. That's because we need to use Mikktspace either as commandline or as library to correctly build the tangents which is an expensive process.

This can be changed by forcing genTangents=true in hxd.fmt.fbx.HMDOut.
