### ISSUE TITLE
h3d VideoTexture

### ISSUE THREAD

**Issue by varadig** [HeapsIO/heaps#750]
I looking the best solution for my future app, where I need to use videotexture.
Heaps.io 3d is support videotexture or if it doesn't there is a future plane to support it?

**Comment by ncannasse** [comment]
On which platform do you need it ? Desktop? browser? Mobile?

Le lun. 13 janv. 2020 à 04:38, Gabor Varadi <notifications@github.com> a
écrit :

**Comment by varadig** [comment]
First of all desktop, but in the future I plane to make html5 version

**Comment by ncannasse** [comment]
For desktop we have h2d.Video on HashLink but it's based on FFMpeg and is experimental. On HTML5 it's implemented as well so should be working. Haven't had the time to try it yet.

**Comment by varadig** [comment]
Ok, and I can Interoperate 2d and 3d layer?

**Comment by varadig** [comment]
So the plane is, port my application to haxe from air:
https://www.youtube.com/watch?v=U3xpYRnO7No
There is an option to add video as background to scene, and put 3d object at the top of it.
 
So if there is just 2D video, the ide is:

2d context (for background video)
3d context (for 3d props)
2d context (for the ui)

**Comment by varadig** [comment]
Ohh ok, it isn't possible:

https://haxe.org/videos/conferences/haxe-summit-us-2018/making-games-with-heaps-io-nicolas-cannasse.html

thanks @ncannasse

**Comment by ncannasse** [comment]
It's actually possible to have several layers 2d/3d/2d see hxd.App
implementation that does create by default a s3d+s2d

Le jeu. 16 janv. 2020 à 06:47, Gabor Varadi <notifications@github.com> a
écrit :
