### ISSUE TITLE
Object's scale and/or positioning is off

### ISSUE THREAD

**Issue by RayMPerry** [HeapsIO/heaps#755]
I just started a new project with Heaps on MacOS 10.15.1 and I've run into some unexpected behavior.

This is all of the code I've written for the project:
```haxe
package;

class SCCGame extends hxd.App {
  override function init() {
    var defaultFont = hxd.res.DefaultFont.get();
    var textField = new h2d.Text(defaultFont);
    textField.text = "Here we go again.";
    textField.x = 0;
    textField.y = 0;

    s2d.addChild(textField);
  }

  override function update(dt: Float) {
    if (hxd.Key.isDown(hxd.Key.Q)) hxd.System.exit();
  }

  public static function main() {
    hxd.Res.initEmbed();
    new SCCGame();
  }
}
```

When first starting the game, I end up with a screen like [this](https://imgur.com/YzIedCf).
After moving or resizing the window, I end up with [a screen I expect](https://imgur.com/PYdBAIG).

Would you happen to know the cause of this issue? Did I just miss a setting somewhere?

Thanks in advance.

**Comment by RayMPerry** [comment]
Possibly related to https://github.com/HeapsIO/heaps/issues/739.

**Comment by McPepper** [comment]
Same issue here

**Comment by AustinEast** [comment]
Check out [this comment]( https://github.com/HeapsIO/heaps/issues/589#issuecomment-594700883), it may help!
