### ISSUE TITLE
Retina + Hashlink. Game is so small!

### ISSUE THREAD

**Issue by daimeng** [HeapsIO/heaps#767]
Not an urgent issue, I'm using HTML output for now. I searched the words retina and osx, not much came up, so I'm creating a topic.

I'm guessing retina doesn't seem to play well with Hashlink version. Game runs very very tiny lol.
Is this known? Or am I just not missing some compile setting?

It looks fine when I run it on windows.

**Comment by Yanrishatum** [comment]
Duplicate of #589
