### ISSUE TITLE
API documentation is outdated

### ISSUE THREAD

**Issue by jstolarek** [HeapsIO/heaps#771]
It looks like [API documentation](https://heaps.io/api/) is outdated to some extent. [h2d.Scene](https://heaps.io/api/h2d/Scene.html) documentation describes `zoom` as a method for setting the zoom scale. But using `s2d.zoom = 4;` in code produces a warning:

```
Main.hx:14: characters 9-19 : Warning : zoom is deprecated, use scaleMode = Zoom(v) instead
```
Indeed, using `s2d.scaleMode = Zoom(4);` instead removes the warning, but `scaleMode` is not mentioned anywhere in the documentation.

**Comment by smallcoderofme** [comment]
![image](https://user-images.githubusercontent.com/18281729/87370124-b6ce9b00-c5b4-11ea-8f83-1ed04aae811a.png)

**Comment by Yanrishatum** [comment]
The API docs are extremely outdated, and not many people willing to write them.
Currently, there's a crowdsourced project on covering engine with documentation (by me), with h2d docs being first part: https://github.com/HeapsIO/heaps/pull/842
I also hosted updated API docs on my server while I work on them.

**Comment by ncannasse** [comment]
In progress, soon merged ;)
