### ISSUE TITLE
Connecting Xbox One gamepad causes DualShock 4 to disconnect

### ISSUE THREAD

**Issue by sigma0x** [HeapsIO/heaps#773]
I'm trying to read inputs from multiple gamepads, keeping List of Pads, and removing Pads from List if Pad.connected is false.

If i launch an app while both gamepads (Xbox One and DualShock 4) are connected, there is absolutely no issue, and everything behaves as expected, but if i try to connect Xbox One controller at runtime while DualShock4 is connected, DS4 disconnects.

i use hashlink with hlsdl.

    function onGamepadConnected(gp : Pad) {
        gamepads.add(gp);   
    }

and in update

        for (gp in gamepads) {
            if (!gp.connected) {
                gamepads.remove(gp);
            }
            else {
                //reading input
            }
        }

**Comment by ncannasse** [comment]
Could you trace what info you get from low level ? (hxd.Pad.onEvent , hlsdl section)
If SDL indeed sends event about DS4 being disconnected, then it's a SDL problem not an HashLink one.

**Comment by sigma0x** [comment]
> 
> 
> Could you trace what info you get from low level ? (hxd.Pad.onEvent , hlsdl section)
> If SDL indeed sends event about DS4 being disconnected, then it's a SDL problem not an HashLink one.

i am really sorry to take the time out of your day, Nicolas.

SDL doesn't send event about DS4 being disconnected, but it is somehow confused between them.

i added 
trace (p.name, "added");
in "case GControllerAdded"
and
trace(p.name, "removed");
in "GControllerRemoved"

and when i connect an Xbox One controller after a DualShock, debug console in VSCode outputs
hxd/Pad.hx:468: PS4 Controller, added
even though Xbox One controller is connected

i'm sorry if i didn't understand you correctly, i'm really new to programming. Should i close the issue?

**Comment by ncannasse** [comment]
Can you trace `e.controller` as well ?  if both pads returns the same index then that's on SDL side.

**Comment by sigma0x** [comment]
> 
> 
> Can you trace `e.controller` as well ? if both pads returns the same index then that's on SDL side.

yes they do return the same index.
