### ISSUE TITLE
HxSL DCE on pure calls

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps#778]
When having a shader that does something like:

```haxe
var a = mix(color,color,f);
saturate(a);
```

We should make sure DCE removes `saturate(a)` useless call, and also give an error/warning in HxSL checker.

**Comment by Yanrishatum** [comment]
DCE should check if said function is actually useless, because they can write to the variables that affect output (see sample). If DCE would mindlessly remove any functions that are just called - it may break shaders. In the sample - instead of dark-red, checker would be white.
```haxe
class Issue778 extends hxd.App
{

	static function main() { new Issue778(); }

	override function init() {
		var btm = new h2d.Bitmap(h2d.Tile.fromTexture(h3d.mat.Texture.genChecker(64)), s2d);
		btm.addShader(new DCEShader());
	}

}

class DCEShader extends hxsl.Shader {

	static var SRC = {

		var textureColor:Vec4;

		function saturate(a:Float) {
			textureColor.r *= a;
			textureColor.g = 0.;
			textureColor.b = 0.;
		}

		function fragment() {
			var a:Float = textureColor.a * .5;
			saturate(a);
		}

	}
}
```
