### ISSUE TITLE
Unweighted vertices warp to 0,0,0 if bone exists (Blender FBX)

### ISSUE THREAD

**Issue by RollinBarrel** [HeapsIO/heaps#780]
FBX is exported by Blender 2.82
As long as object has at least one Bone attached to it, vertices that aren't weighted with their Vertex Group linked to a Bone seem to warp to 0,0,0

![v](https://user-images.githubusercontent.com/7990120/78454218-5ff52380-769f-11ea-8009-26820742cf04.gif)
Export Settings:

![b](https://user-images.githubusercontent.com/7990120/78455207-9766ce80-76a5-11ea-867c-9e4dfb7ffe7e.png)

In HIDE:
![v](https://user-images.githubusercontent.com/7990120/78454275-bb271600-769f-11ea-821c-16e35e3cd085.gif)

FBX:
[cube.zip](https://github.com/HeapsIO/heaps/files/4431855/cube.zip)

**Comment by ncannasse** [comment]
I don't think we handle unweighted vertices at all, as it requires an additional pseudo-bone which is always identity. Is it an important feature?

**Comment by RollinBarrel** [comment]
Not really, it's easy to workaround
Just that it was confusing while i was figuring it out 😂

**Comment by ncannasse** [comment]
Will close for now then ;)
