### ISSUE TITLE
DomKit samples do not appear to work

### ISSUE THREAD

**Issue by laughsuggestion** [HeapsIO/heaps#781]
I am trying to use this sample:
https://github.com/HeapsIO/heaps/blob/master/samples/Domkit.hx

I build and get errors inside the domkit source code:
`C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:414: characters 20-37 : Current class does not have a super
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:245: lines 245-392 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.ObjectComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:245: lines 245-392 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:245: character 1 : h2d.domkit.ObjectComp should be h2d.Object
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:245: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.ObjectComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:245: lines 245-392 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.DrawableComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:395: lines 395-407 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:395: character 1 : h2d.domkit.DrawableComp should be h2d.Drawable
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:395: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.DrawableComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:395: lines 395-407 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.TextComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:435: lines 435-457 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:435: character 1 : h2d.domkit.TextComp should be h2d.Text
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:435: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.TextComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:435: lines 435-457 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.HtmlTextComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:460: lines 460-466 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:460: character 1 : h2d.domkit.HtmlTextComp should be h2d.HtmlText
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:460: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.HtmlTextComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:460: lines 460-466 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.InputComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:650: lines 650-682 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:650: character 1 : h2d.domkit.InputComp should be h2d.TextInput
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:650: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.InputComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:650: lines 650-682 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.MaskComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:410: lines 410-417 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:410: character 1 : h2d.domkit.MaskComp should be h2d.Mask
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:410: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.MaskComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:410: lines 410-417 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.FlowComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:470: lines 470-647 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:470: character 1 : h2d.domkit.FlowComp should be h2d.Flow
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:470: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.FlowComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:470: lines 470-647 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:201: characters 65-68 : h2d.domkit.BitmapComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:420: lines 420-432 : Defined in this class
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:420: character 1 : h2d.domkit.BitmapComp should be h2d.Bitmap
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:420: character 1 : For function argument 'value'
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:204: characters 12-15 : h2d.domkit.BitmapComp has no field dom
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:420: lines 420-432 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:420: lines 420-432 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:470: lines 470-647 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:410: lines 410-417 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:650: lines 650-682 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:460: lines 460-466 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:435: lines 435-457 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:395: lines 395-407 : Defined in this class
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Constraint check failure for create.BaseT
C:\HaxeToolkit\haxe\lib\domkit/git/domkit/Macros.hx:203: characters 13-37 : Unknown<0> should be domkit.Model<Unknown<0>>
C:\HaxeToolkit\haxe\lib\heaps/1,7,0/h2d/domkit/BaseComponents.hx:245: lines 245-392 : Defined in this class`

**Comment by Yanrishatum** [comment]
Your error log showcases that you are using outdated version of Heaps (e.g. from Haxelib). Retest with git version.

**Comment by laughsuggestion** [comment]
@Yanrishatum can you point to where I can find that in this log? I'd like to see what you see so I can fish on my own! Also will update from git! Thank you :)
