### ISSUE TITLE
PakFileSystem + Custom Convert issue

### ISSUE THREAD

**Issue by qkdreyer** [HeapsIO/heaps#787]
I'm having issue while generating a pak resource file using hashlink and a custom convert.

`props.json`
```json
{
  "fs.convert": {
    "^.*(zombie\\d).*\\.png$" : "png"
  }
}
```

```sh
haxe -hl build/src/pak.hl -L heaps -main hxd.fmt.pak.Build -p src -lib image --macro converters.ResizeConvert.init()

hxd/fs/Convert.hx:60: register,[fbx],hmd,hxd.fs.ConvertFBX2HMD
hxd/fs/Convert.hx:60: register,[wav],mp3,hxd.fs.ConvertWAV2MP3
hxd/fs/Convert.hx:60: register,[wav],ogg,hxd.fs.ConvertWAV2OGG
hxd/fs/Convert.hx:60: register,[tga],png,hxd.fs.ConvertTGA2PNG
hxd/fs/Convert.hx:60: register,[fnt],bfnt,hxd.fs.ConvertFNT2BFNT
hxd/fs/Convert.hx:60: register,[png,tga,jpg,jpeg],dds,hxd.fs.CompressIMG
hxd/fs/Convert.hx:60: register,null,dummy,hxd.fs.DummyConvert
hxd/fs/Convert.hx:60: register,null,remove,hxd.fs.DummyConvert
src/converters/ResizeConvert.hx:25: Instanciating ResizeConvert
hxd/fs/Convert.hx:60: register,[png],png,converters.ResizeConvert
```

```sh
hl build/src/pak.hl -out build/src/res

hxd/fs/Convert.hx:60: register, [fbx], hmd, hxd.fs.ConvertFBX2HMD
hxd/fs/Convert.hx:60: register, [wav], mp3, hxd.fs.ConvertWAV2MP3
hxd/fs/Convert.hx:60: register, [wav], ogg, hxd.fs.ConvertWAV2OGG
hxd/fs/Convert.hx:60: register, [tga], png, hxd.fs.ConvertTGA2PNG
hxd/fs/Convert.hx:60: register, [fnt], bfnt, hxd.fs.ConvertFNT2BFNT
hxd/fs/Convert.hx:60: register, [png,tga,jpg,jpeg], dds, hxd.fs.CompressIMG
hxd/fs/Convert.hx:60: register, null, dummy, hxd.fs.DummyConvert
hxd/fs/Convert.hx:60: register, null, remove, hxd.fs.DummyConvert
<root>
zombie1
zombie1/Idle
No converter is registered that can convert zombie1/Idle/idle0018.png to png
Called from hxd.fs.FileConverter.runConvert (hxd/fs/FileConverter.hx line 233)
Called from hxd.fs.FileConverter.run (hxd/fs/FileConverter.hx line 214)
Called from hxd.fs.LocalFileSystem.open (hxd/fs/LocalFileSystem.hx line 269)
Called from hxd.fs.LocalFileSystem.get (hxd/fs/LocalFileSystem.hx line 289)
Called from hxd.fmt.pak.Build.buildRec (hxd/fmt/pak/Build.hx line 50)
Called from hxd.fmt.pak.Build.buildRec (hxd/fmt/pak/Build.hx line 41)
Called from hxd.fmt.pak.Build.buildRec (hxd/fmt/pak/Build.hx line 41)
Called from hxd.fmt.pak.Build.buildRec (hxd/fmt/pak/Build.hx line 41)
Called from hxd.fmt.pak.Build.makePak (hxd/fmt/pak/Build.hx line 131)
Called from hxd.fmt.pak.$Build.main (hxd/fmt/pak/Build.hx line 216)
```

**Comment by ncannasse** [comment]
Thats seems about right, you're just doing png-to-png here. What are you trying to do ?

**Comment by qkdreyer** [comment]
My ResizeConverter is indeed transforming png to png but resizing them in its convert method.

It’s working fine using HL/JIT but it’s not being loaded while creating the pak file, hence the error message 😞

**Comment by ncannasse** [comment]
Make sure you compile your custom convert with your hl and add @:keep to
the class of you are using -dce full

Le ven. 10 avr. 2020 à 20:11, Quentin Dreyer <notifications@github.com> a
écrit :

**Comment by qkdreyer** [comment]
Not using any `-dce` and parent `Convert` class is already  having `@:keepSub`

**Comment by Yanrishatum** [comment]
This is most likely happens because external Converts do not resolve their statics, even if they are present in output. Just having `static var _ = Convert.register(...)` does not guarantee that `__init__` of that convert would be called at same time as other Converts, hence why it's not working with pak, but does with completion server and app. I'm not sure how to resolve it, honestly.
I.e. what happens during completion server/regular runtime:
1. Default Converts registered
2. Custom Convert is referenced somewhere, causing it to resolve `__init__`.
3. FS access files and uses correct list of Converts.

While on pak builder:
1. Default Converts registered
2. Custom Convert is NOT registered, because there is no reference to it that would cause `__init__` call.
3. FS access files to compile pak file with only default Converts.

My suggestion is to try making your own pak builder `main()` class that would ensure that all your converts are initialized, and then call the pak builder main. E.g. something like that:
```haxe
class MyPakBuilder {
  static function main() @:privateAccess {
    converters.ResizeConvert._; // Ensure that it's being resolved.
    hxd.fmt.pak.Build.main(); // Back to main entry-point.
  }
}
```

**Comment by ncannasse** [comment]
When creating pak don't forget to compile your convert with it (listing the class as part of the commandline arguments), it should be enough.

**Comment by qkdreyer** [comment]
Sorry about this late reply~

@Yanrishatum I also thought your suggestion would work but sadly this is the deps tree of my converter  :
- [image](https://lib.haxe.org/p/image/)
  - [asys](https://lib.haxe.org/p/asys/)
    - [tink_io](https://lib.haxe.org/p/tink_io/)
      - [tink_chunks](https://lib.haxe.org/p/tink_chunk/)
    - [tink_streams](https://lib.haxe.org/p/tink_streams/)
  - [tink_core](https://lib.haxe.org/p/tink_core/)

and when hooking into `hxd.fmt.pak.Build.main` and calling my converter directly, I'm getting this weird error :

```sh
haxe -hl build/src/pak.hl -L heaps -main pak.Build -p src -lib heaps -lib image
Error: Extern type not supported : tink.core._Promise.Nonsense
```

N.B. Appending or not `--macro 'converters.ResizeConvert.init()'` doesn't change anything

@ncannasse Appending `src/Converters/ResizeConvert.hx` produce the exact same previous error

**Comment by Yanrishatum** [comment]
Could you provide reproducible sample project? (As well as which library versions are used)
In case you need pak for HTML5 output, you can try my [manifest-fs](https://github.com/Yanrishatum/heeps/#manifest-fs) for the meantime. Main note about sample - loader should be in `init`, since `loadAssets` isn't running render loop just yet.

**Comment by qkdreyer** [comment]
@Yanrishatum https://github.com/qkdreyer/heaps-tink_core_nonsense

**Comment by paulherman** [comment]
A quick hack is to move the custom converters into the library code (.../hxd/fs/Convert.hx) since it's available locally. That seems to mitigate the issue.

**Comment by Yanrishatum** [comment]
This is a bug in Tink library, and was fixed on git already: https://github.com/haxetink/tink_core/commit/2842feef30b27bef4dea59ac6c1e1a58e83ecd3d
Hence unrelated to Heaps, but requirement to ensure that Convert is initialized is still here, so you do need to include file in hxml. If you plan to have a lot of them, I'd suggest just doing the following:
```haxe
class ConvertReg {
  static var convA = Convert.register(new ConvertA());
  static var convB = Convert.register(new ConvertB());
}
```
And in hxml:
```
# regular code
ConvertReg.hx
```

**Comment by qkdreyer** [comment]
https://github.com/haxetink/tink_core/releases/tag/1.26.0
