### ISSUE TITLE
Fbx from unity seem not support by heaps?

### ISSUE THREAD

**Issue by sonygod** [HeapsIO/heaps#789]
fbx from unity seem not support by heaps?

I'm trying to export fbx  model and animation from unity use unity's fbx  exporter tool

but it's seem heaps .not support!

![image](https://user-images.githubusercontent.com/748320/79111512-39c23880-7daf-11ea-9336-c46749a3da68.png)

when heaps convert fbx to hmd ,it's seem have some issue..

here is fbx files with texture.

[fbx.zip](https://github.com/HeapsIO/heaps/files/4468471/fbx.zip)

    import h3d.scene.*;
    import h3d.scene.fwd.*;

    class Skin extends hxd.App {

	var cache : h3d.prim.ModelCache;

	override function init() {
		cache = new h3d.prim.ModelCache();

		var obj = cache.loadModel(hxd.Res.Fish1);
		obj.scale(0.1);
		s3d.addChild(obj);
		s3d.camera.pos.set( -3, -5, 3);
		s3d.camera.target.z += 1;

		obj.playAnimation(cache.loadAnimation(hxd.Res.Fish1));

		// add lights and setup materials
		var dir = new DirLight(new h3d.Vector( -1, 3, -10), s3d);
		for( m in obj.getMaterials() ) {
			var t = m.mainPass.getShader(h3d.shader.Texture);
			if( t != null ) t.killAlpha = true;
			m.mainPass.culling = None;
		//	m.getPass("shadow").culling = None;
		}
		s3d.lightSystem.ambientLight.set(0.4, 0.4, 0.4);

		var shadow = s3d.renderer.getPass(h3d.pass.DefaultShadowMap);
		shadow.power = 20;
		shadow.color.setColor(0x301030);
		dir.enableSpecular = true;

		new h3d.scene.CameraController(s3d).loadFromCamera();
	}

	static function main() {
		hxd.Res.initEmbed();
		new Skin();
	}

    }

**Comment by NewKrok** [comment]
https://community.heaps.io/t/fbx-from-unity-seem-not-support-by-heaps/538/2

**Comment by ncannasse** [comment]
Works correctly and animation plays in HIDE
![image](https://user-images.githubusercontent.com/1022912/94360485-d2bee480-00ad-11eb-85b6-d59b16882fbd.png)
