### ISSUE TITLE
In PBR example cant cast fwd  to pbr Renderer 

### ISSUE THREAD

**Issue by arqlz** [HeapsIO/heaps#799]
This is the code

cast(s3d.renderer, h3d.scene.pbr.Renderer);

witch result on a Exception "Can't cast h3d.scene.fwd.Renderer to h3d.scene.pbr...."

**Comment by arqlz** [comment]
This worked;
```
function new() {
        **h3d.mat.MaterialSetup.current = new h3d.mat.PbrMaterialSetup();** // before super
        super();
    }
```

**Comment by ncannasse** [comment]
This is correct, I think just the samples are not up to date on the website.
