### ISSUE TITLE
Error: must use 'class' tag to refer to type 'Dynamic' in this scope

### ISSUE THREAD

**Issue by lukehayes** [HeapsIO/heaps#802]
I'm trying to compile a simple Haxe class using Heaps into C++ but I am getting this error message:

`
Error: ./src/hxd/impl/_Allocator/BufferFlags_Impl_.cpp:49:65: error: must use 'class' tag to refer to type 'Dynamic' in this scope
bool BufferFlags_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, hx::PropertyAccess inCallProp)
                                                                ^
                                                                class
./src/hxd/impl/_Allocator/BufferFlags_Impl_.cpp:32:28: note: class 'Dynamic' is hidden by a non-type declaration of 'Dynamic' here
int BufferFlags_Impl__obj::Dynamic;
                           ^
1 error generated.
Error: Build failed`

Here is the source code I am using:

    import h2d.Font;
    import h2d.Text;
    import hxd.App;

     class Game extends hxd.App {

         override function init() {

             var font : h2d.Font = hxd.res.DefaultFont.get();
             var tf = new h2d.Text(font);
             tf.text = "Hello World\nHeaps is great!";
             tf.textAlign = Center;
             tf.textColor = 0x5FEEa1;

             // add to any parent, in this case we append to root
             s2d.addChild(tf);
         }

         static function main() {
             new Game();
       }
     }

When building the project on my machine its using g++. I wanted to check if it compiler specific - Is there a way to change the default compiler?

**Comment by ncannasse** [comment]
Heaps does not support hxcpp target, you need to use HL/C for native compilation.
