### ISSUE TITLE
hxd.Rand.srand() returns a negative random value

### ISSUE THREAD

**Issue by haddock7** [HeapsIO/heaps#805]
STR:
```haxe
var random = new Rand(0);
trace(random.srand(500));
```
It outputs -469.62126511442 (tested with hashlink on Windows 64 bits).

The issue comes from an overflow with this.seed. The fix is easy: replace int() by uint() at Rand.hx:59

(I don't have the rights to create a pull request for this fix).

**Comment by ncannasse** [comment]
stand() is for signed random so it returns between -value and +value.

**Comment by haddock7** [comment]
Thanks Nicolas for the explanation.
It's not very important, but should the function rand() be consistant with srand() and have the same parameter scale?
