### ISSUE TITLE
HXSL Mat2 type is not supported

### ISSUE THREAD

**Issue by 0xA3** [HeapsIO/heaps#810]
Im trying to create a 2D rotation matix. The GLSL code is
```
mat2 rotate2d(float _angle){
    return mat2(cos(_angle),-sin(_angle),
                sin(_angle),cos(_angle));
}
```
In HXSL this would be
```
function rotate2d( angle:Float ):Mat2 {
	return 	mat2(cos(angle),-sin(angle),
                	sin(angle),cos(angle)); 
}
```
I get the error message
```Unsupported type Mat2```

It would be cool to be able to work with this type and it shouldn't be too hard to implement. (I hope)

**Comment by ncannasse** [comment]
Sure, please use a Mat3 for now, I'll look into it when possible.

**Comment by 0xA3** [comment]
After I got some excellent suggestions from Yanrishatum with Issue #811 I decided I can add Mat2 type myself.
I'll create a pull request
