### ISSUE TITLE
HXSL Cannot multiply Mat3 and Vec3

### ISSUE THREAD

**Issue by 0xA3** [HeapsIO/heaps#811]
I tried using mat3 for Rotation
First I'm not sure if I use the correct way to create a Mat3 Variable in the shader code.
In GLSL its like so: mat3 with 6 parameters.
```
mat3 rotate2d(float _angle){
    return mat3(cos(_angle),-sin(_angle),0,
                sin(_angle),cos(_angle),0,
               0,0,1);
}
```
Which would be like so in hxsl
```
function rotate2d_2( angle:Float ):Mat3 {
	return 	mat3(
		cos(angle), -sin(angle), 0,
		sin(angle), cos(angle), 0,
		0, 0, 1 );
}
```
The compiler says ```Cannot apply mat3 to these parameters```

When I create mat3 with 3 vectors, it seems to work. Is it correct? I checked the heaps sourcecode but coudn't find one that creates a mat3.
```
function rotate2d_2( angle:Float ):Mat3 {
	return 	mat3(
		vec3( cos(angle), -sin(angle), 0 ),
		vec3( sin(angle), cos(angle), 0 ),
		vec3( 0, 0, 1 ));
}
```
In fragment() method call I the function and multiply a vec3.
```
var st3 = rotate2d_2( sin( time ) * PI ) * vec3( st, 1 );
```
The compiler returns the Error ```Cannot multiply Mat3 and Vec3```.

This is [sourcecode in GLSL](https://www.shadertoy.com/view/tdfBWN) that does this.
This is my [haxe sourcecode](https://github.com/0xA3/haxe-examples/blob/master/hxsl/book_of_shaders_examples/20_rotation/src/Main.hx)

Thanks

**Comment by Yanrishatum** [comment]
Let's address it one at a time:
HXSL does not implement matrix initialization with anything other than passing another 3x4/3x3 matrix or 3 vectors. If you can guarantee that constructing 3x3 matrix such way would work in both GLSL and HLSL (i.e. DirectX), you can try to add this to `hxsl.Checker.specialToGlobal`, by adding following to `case Mat3:` check at line 1009:
```haxe
			case [TFloat, TFloat, TFloat, TFloat, TFloat, TFloat, TFloat, TFloat, TFloat]: type = TMat3;
```
This should enable ability to construct mat3/float3x3 by passing entire matrix directly.

Same goes for `Mat3 * Vec3` multiplication, if you can guarantee it works for both GLSL and HXSL, you can allow it in `hxsl.Checker.typeBinop` at line 1117:
```haxe
			case [OpMult, TMat3, TVec(3,VFloat)]:
				vec3;
```

**Comment by 0xA3** [comment]
This works beautifully for compiling to GLSL but not for HLSL
The mat3 initialisation causes the error
```
Shader compilation error 
<< mat3(cos(angle), -sin(angle), 0., sin(angle), cos(angle), 0., 0., 0., 1.) >>: error X3013: 'mat3': no matching 9 parameter function		
```
and the Mat3 * Vec3 error is
```
Shader compilation error 
<< val0() * float3(st, 1.) >>: error X3020: type mismatch
```
Both errors deep inside the DirectXDriver
```
h3d.impl.DirectXDriver.compileShader (d:\Projekte\Haxe\haxelib_dev\heaps\h3d\impl\DirectXDriver.hx:742)
h3d.impl.DirectXDriver.selectShader (d:\Projekte\Haxe\haxelib_dev\heaps\h3d\impl\DirectXDriver.hx:907)
h3d.Engine.selectShader (d:\Projekte\Haxe\haxelib_dev\heaps\h3d\Engine.hx:112)
```
So maybe in DirectX it's just done differently.

**Comment by Yanrishatum** [comment]
Ok, it seems more work on HlslOut needs to be done.
First, in `hxsl.HlslOut.addExpr`, when declaring helper methods for `Mat3`, add method that takes full mat3 declaration:
```haxe
				decl("float3x3 mat3( float3 c00, float3 c01, float3 c02, float3 c10, float3 c11, float c12, float3 c20, float3 c21, float3 c22 ) { float3x3 m = { c00, c01, c02, c10, c11, c12, c20, c21, c22 }; return m; }");
```
Line 319
Then alter the multiplication case on 405 to allow mat * vec:
```haxe
			case [OpMult, TVec(_), TMat3 | TMat4] | [OpMult, TMat3 | TMat4, TVec(_)]:
```
As a precaution: I didn't test it, so syntax and general implementation may be incorrect, so I expect some common sense and understanding that correct implementation may be slightly different. I just point out places that have to be altered in order to get those features in.

**Comment by 0xA3** [comment]
Yes it worked. Great! Thank You!
I also created a [pull request](https://github.com/HeapsIO/heaps/pull/812)
