### ISSUE TITLE
[RFC] Browser-powered OGG support

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#813]
So, Apple not going to budge for years to come, so I would like to propose implementing ogg decoding trough browser capabilities, allowing to free up time dedicated to decoding ogg trough `stb_ogg_sound`. For all I know, Safari can go f itself :)

## Implementation
* I plan to retain `stb_ogg_sound` support, but leave it as an optional fallback solution, not the primary one. It won't be required to play ogg on HTML5, but mandatory for it to work on Safari.
* Default approach will be changed to use same method mp3 does - leave everything to AudioContext.
* I'm not yet sure how to proceed with initial parsing of ogg file to get basic metadata (sample count/bitrate/etc). Lazy solution is to still require `stb_ogg_sound`, but that would defeat purpose of implementing native deocder to a degree. Alternative solution is to implement micro-decoder for vorbis format that is focused on getting only required metadata. Comments?

Additional thoughts: If we go with micro-decoder, I think mp3 needs to get same attention as well, because right now it processes whole mp3 to get metadata, while it can be optimized a lot in that regard.

**Comment by rcstuber** [comment]
Maybe helpful, maybe not:

https://github.com/AnthumChris/opus-stream-decoder

https://github.com/AnthumChris/fetch-stream-audio/blob/master/README.md

**Comment by ncannasse** [comment]
Micro decoder can work, I think the format is quite easy to deal with.

**Comment by ncannasse** [comment]
Nothing activable here atm, closing :)
