### ISSUE TITLE
TextInput : support for standard shortcuts

### ISSUE THREAD

**Issue by Fl0xer** [HeapsIO/heaps#819]
- Ctrl + A : select all
- Ctrl + arrow : navigate word by word
- Enter : skip a line when allowed and when it will be handled
- Escape : remove focus from the text input (for now, it's Enter)

**Comment by kLabz** [comment]
I started working on this before seeing this issue. For CTRL+A there is #823. I'll see for ENTER and ESC.

As for CTRL+Arrow, I have something locally that navigates per word but is limited to "real" spaces (handles multiple spaces). What rules should we follow for defining a word? Should we separate by:
* One or more space (implemented locally)
* Any whitespace character
* Any non-alphanumeric character
* Any non-[alphanumeric character, including `_` and accents (and some other ascii symbols?)]

**Comment by ncannasse** [comment]
Spaces as defined by hxd.CharSet seems good enough.

**Comment by kLabz** [comment]
Got it, will do that tonight.
