### ISSUE TITLE
HXSL - matrix array access

### ISSUE THREAD

**Issue by jefvel** [HeapsIO/heaps#831]
I've tried looking for it, but I can't seem to find anything about how to access individual values by column+row in matrices. Is it possible?

**Comment by ncannasse** [comment]
I don't think it's possible atm, this could be added but requires a bit of support at various hxsl stages (Checker, then GLSL/HLSL code generators)

**Comment by jefvel** [comment]
Alright! I took a quick look and managed to get something working, by adding this in Checker.hx:
```
line 620
			case TMat4:
				type = TArray(TFloat, SizeDecl.SConst(4));
				TExprDef.TArray(e1, e2);
```

After that I can access matrix values like `mat[0][0]`.

It seems to go `matrix[column][row]` in GLSL and `matrix[row][column]` in HLSL though. 

Should something like `TMatrixArrayAccess(w, h)` be added, and then use that in the GLSL HLSL code generators?

**Comment by ncannasse** [comment]
No need for new set, we can instead replace array accesses to matrixes in
hlsl generator with something else. Column major is correct.

**Comment by ncannasse** [comment]
I've added matrix[x] that allows to get a vector for the column major (on both GL and DX). Atm since we don't allow [0] on vertex you will need to do  matrix[0].x instead of matrix[0][0]
