### ISSUE TITLE
DCE causes toString() methods to be discarded

### ISSUE THREAD

**Issue by deepnight** [HeapsIO/heaps#834]
If there's no direct reference to a class toString() method, it's discarded by DCE, forcing you to add @:keep in front of all of them.

**Comment by ncannasse** [comment]
This is not heaps related, please open an issue on Haxe repo 😉

Le ven. 5 juin 2020 à 14:59, Sébastien Bénard <notifications@github.com> a
écrit :

**Comment by deepnight** [comment]
Done: https://github.com/HaxeFoundation/haxe/issues/9541
