### ISSUE TITLE
[RFC] Multi-Texture support for h2d batched renderers

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#838]
The one-texture-per-batcher limitation always was annoying to deal with, since while in release version it provides benefits of batching all the elements in one draw-call taking from single atlas, during development it's sub-optimal, since depending on workflow those classes can become unusable due to artists using lots of different images instead of one atlas, and for quick iterations - rebuilding atlas after any little change is the last thing you'd want to do.
Hence I would propose introducing support for multiple textures in following classes: `Graphics`, `SpriteBatch` and `TileGroup`.

## Implementation
I already did an experimental implementation in Heeps: https://github.com/Yanrishatum/heeps/blob/master/ch2/BatchDrawer.hx#L397-L471
In essence, everything still resides in a singular buffer, but on top of Content, there will be a BatchState instance, that would hold information unique to specific batch sequence (Starting offset, tile and triangle count), which are then rendered with multiple draw-calls. Those batch instances are pooled as to minimize the allocation count.
Compared to experimental implementation I don't plan to introduce multiple textures in one draw-call as I did in Heeps, so one BatchState going to be restricted to one Texture.
As a side note: If texture switched, it makes new state regardless if that texture was used in previous states. This is for obvious reason of render ordering. Also experimental implementation is restricted to quads, which is not compatible with regular TileGroup and Graphics, hence proper implementation would use different counters.

## Drawbacks
* Optimization aspect is gone to a degree and heavily depends on how those classes are utilized.
  * Should not affect performance if used the old-fashioned way.
* Slight overhead and memory footprint between Content and Object.
* Causes multiple `beginDrawObject` calls.
  * Can be mitigated by introducing `RenderContext.drawBatchStates(object, states)` or another way to skip some of `beginDrawObject` setup and just switch textures around.

## Positives
* Ability to use multiple textures in batches in exchange for more drawcalls
* Faster iteration time, since having singular atlas is no longer mandatory.
* It's possible to later compile all images to singular atlas and get benefits of less drawcalls on release, but faster iteration time during development.
* Also in case when content doesn't fit one atlas, it will be possible to use multiple atlases.

## Extra notes
* Other approach is to use atlas that builds at runtime, and again, I have an experimental implementation: https://github.com/Yanrishatum/heeps/blob/master/cherry/RuntimeAtlas.hx
* Multi-texture support will allow to start implementation of #453, bringing full support of bmf format.
* Also will allow to simplify HtmlText a lot, since it'll be possible to cram everything into single Content instance instead of awkward objects added to instance. (And draw count will remain the same, but less unnecessary overhead of multiple objects)

## Things to discuss
* Should unused BatchState instances be stored in global pool or individual pools?
* Should used states be held in Content or Object? I'm leaning towards Content, as to allow direct usage of Content methods and not bother with forgetting to increase counters or change to new state.
* Should RenderContext be aware of batchstates and allow simplified state switch? I'd say yes.

@ncannasse :)

**Comment by ncannasse** [comment]
Actually... https://github.com/HeapsIO/heaps/commit/51d14f44194a0435ecd93d1488b391b6c328b599 ;)

**Comment by Yanrishatum** [comment]
Just to make sure (since digging trough HXSL for majority is rather arduous endeavor): Does it define multiple uniforms or uses texture arrays of target language? Because if later, it has a big drawback: Textures has to be of same size (at least for [GLSL](https://www.khronos.org/opengl/wiki/Array_Texture)).

**Comment by ncannasse** [comment]
Yes it's multiple uniforms. Please note that texture arrays will only simplify your implementation and allow unlimited texture count. You will still need to do a "for" in the MultiTexture shader, as textures[index] will not work :'(

Another option for auto atlas is to use BigTexture, that will manage the altas creation for you. There's a tradeoff to be made between BigTexture size and count, but that can be setup in BatchShader. Also, since all BigTexture have same size, you can create a TextureArray of them so the shader does a simple fetch on it (no for).

**Comment by ncannasse** [comment]
So I guess you could update your BatchDrawer with a single state (much more efficient - and no need for a separate class then), and you should optimize the index resolution so that using BatchDrawer with a single texture does not perform any lookup (`if( tex == lastTexture ) return lastIndex;` works for many scenarios) 

I guess this would then work as a default replacement for TileGroup, maybe by changing its constructor:
- if you pass a Tile, it will be single-texture group (as now)
- if you don't pass a Tile, it will be multi-texture group (adds index in vertex data, track textures)

**Comment by Yanrishatum** [comment]
> Please note that texture arrays will only simplify your implementation and allow unlimited texture count

Well, it would simplify implementation in Heeps (I really need to rename it, since it got way bigger than I expected it to be).
However, I propose mainly the BatchState class that enables 2d batches to use multiple textures.
Also I'm not sure if MultiTexture has place along primary library, especially since amount of texture uniforms is limited, and usage of it requires introducing texture index in the buffer.
And as I just mentioned: Not unlimited ;) It's limited by `GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS` on GLSL at least.

> auto atlas is to use BigTexture

I considered using BigTexture, but I don't recall why exactly I decided against using it.

> BatchDrawer

This one is not part of the RFC ;) It's was an experiment of a hybrid between SpriteBatch and TileGroup. Same as TileGroup in terms of not spamming buffer uploads and no extra instances per element, but also allow editing pre-existing tiles by addressing them by index.
