### ISSUE TITLE
HTML5 + Retina

### ISSUE THREAD

**Issue by kevinresol** [HeapsIO/heaps#840]
On html5, GlDriver sets canvas' rendered pixels to the multiplied dimension: 
e.g. `document.body.clientWidth * window.devicePixelRatio`
on my macbook it is `1440 * 2 = 2880`

https://github.com/HeapsIO/heaps/blob/7302fabae61e5620d15ff79de27fa01a72f128ed/h3d/impl/GlDriver.hx#L778-L779

But rendered objects don't seem to scale accordingly.
e.g. `graphics.drawRect(0, 0, 1440, 100);` a rect that fills half of the screen when devicePixelRatio is 2:
<img width="1552" alt="Screenshot 2020-06-21 at 5 41 50 PM" src="https://user-images.githubusercontent.com/1103788/85221465-8b59f580-b3e6-11ea-8983-4334ebad4cb7.png">

but the same rect will fill the entire screen when devicePixelRatio is 1:
![Screenshot 2020-06-21 at 5 43 52 PM](https://user-images.githubusercontent.com/1103788/85221505-ce1bcd80-b3e6-11ea-9a16-8a888d5b7a0a.png)

**Comment by ncannasse** [comment]
I think this is intended. The idea is that the Retina screen really offers that much resolution, and it's up to your application to deal with various screen sizes. I guess you would get the same with 4K display on Windows.

**Comment by kevinresol** [comment]
But it is inconsistent with hl

**Comment by kevinresol** [comment]
Anyway I don't think this is the convention. For example in iOS development, iphone has 2x (retina) and even 3x, 4x (super-retina). Suppose a "2x" phone has 720 physical pixels, in software we will code it as 360px. Same for a "3x" phone with 1080 physical pixels. All layout code would be the same, with 360 software pixels. The only difference is that iOS will choose a different image to render, e.g. `foo.png`, `foo@2x.png`, `foo@3x.png`.

**Comment by nanjizal** [comment]
I've only experimented on Kha with this problem as OpenFL provides pixel scaling by default.  This is experimental code I have used to help with this problem, I am not happy about it's current format but in maybe useful for anyone finding this thread, if you dislike the code please don't critic just post something more suitable, cheers.

https://github.com/nanjizal/htmlHelper/blob/master/src/htmlHelper/canvas/AutoSize.hx

**Comment by ncannasse** [comment]
> But it is inconsistent with hl

Not if/when HL supports Retina display.
You can resize the back buffer and the 2d scene using engine.resize(w,h) if you want to handle this, but this should be done manually.
