### ISSUE TITLE
Filter Groups binding

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#845]
While writing docs to `h2d.filter.Group` I've noticed a bug with their allocation: If Group was already bound (Added to allocated Object), subsequently added filters won't receive the `bind` call.

I.e.:
1. Group was added to Object -> `bind()` call
2. Group calls `bind` on all already added filters
3. User adds new filter to the group
4. Expected: filters gets `bind` call immediately. Not happens in reality.

I can just note this behavior in docs or do a separate PR that would introduce an extra array of bound objects to Group and ensure that all filters will receive bind/unbind properly.
Same issue touches removing filter from Group - they won't receive `unbind` call.

**Comment by ncannasse** [comment]
We should specify in the doc that the filters array should not be modified after being passed to group constructor.
