### ISSUE TITLE
Dawn, a WebGPU implementation

### ISSUE THREAD

**Issue by longde123** [HeapsIO/heaps#848]
This is not an isses

https://github.com/boberfly/dawn

I have a question, Is there a plan to bind a backend？ 

Dawn, a WebGPU implementation
Dawn (formerly NXT) is an open-source and cross-platform implementation of the work-in-progress WebGPU standard. It exposes a C/C++ API that maps almost one-to-one to the WebGPU IDL and can be managed as part of a larger system such as a Web browser.

Dawn provides several WebGPU building blocks:

WebGPU C/C++ headers that applications and other building blocks use.
The main C header for the WebGPU API.
Definition of a structure of all function pointers for this specific Dawn version (called "proctable").
A C++ wrapper for the C header.
A "native" implementation of WebGPU using platforms' GPU APIs:
D3D12 on Windows 10
Metal on OSX (and eventually iOS)
Vulkan on Windows, Linux (eventually ChromeOS, Android and Fuchsia too)
OpenGL as best effort where available
A client-server implementation of WebGPU for applications that are in a sandbox without access to native drivers
A Dawn proc-table backend implementation of WebGPU for applications what want to be able to switch at runtime between native or client-server mode.

**Comment by ncannasse** [comment]
I've been slightly following webgpu progress. But I'm waiting for it to be implemented in Chrome and available in nwjs to develop a driver for it.
