### ISSUE TITLE
-D js-es=6 error.

### ISSUE THREAD

**Issue by sonygod** [HeapsIO/heaps#855]
haxe: nightly  build 

heaps:git 

        C:\HaxeToolkit\haxe\lib\heaps/git/h3d/impl/LogDriver.hx:202: characters 4-49 : Don't know how to cast hl.types.ArrayBytes_hl_F32 to hl.types.ArrayDyn

**Comment by ncannasse** [comment]
It means you're trying to do this cast which is not correct.

**Comment by sonygod** [comment]
@ncannasse  ,but compiler won't tell which file or which line cause to cast. I search all my code,there is nothing cast code.

**Comment by ncannasse** [comment]
Ah right it's part of Heaps sources.
Sadly, I can't reproduce when compiling with Git haxe+heaps:

haxe -hl test.hl -lib heaps -dce no h3d.impl.LogDriver

**Comment by sonygod** [comment]
You have to add  -D js-es=6

**Comment by ncannasse** [comment]
That's unrelated, since it's supposed to only occur in HL compilation.

**Comment by sonygod** [comment]
Js target instead of hl version

**Comment by sonygod** [comment]
it's haxe  error instead of heaps .
