### ISSUE TITLE
Cannot create a texture from a thread

### ISSUE THREAD

**Issue by GlassySundew** [HeapsIO/heaps#858]
Simply creating a texture from colyseus example(https://github.com/colyseus/colyseus-hx/tree/master/example/openfl) gives an error for hashlink sdl target, reproduced bug:
[test.zip](https://github.com/HeapsIO/heaps/files/4922150/test.zip)

**Comment by GlassySundew** [comment]
well, actually a more simple example is:
`sys.thread.Thread.create(() -> {
			new h3d.mat.Texture(1, 1);
		});`

**Comment by ncannasse** [comment]
I don't think you're allowed to use either opengl or DirectX APIs from
multiple threads.

Le mer. 15 juil. 2020 à 02:18, GlassySundew <notifications@github.com> a
écrit :

**Comment by GlassySundew** [comment]
Wrapping code with a 0 ms Timer solved the issue
