### ISSUE TITLE
hxd._FloatBuffer.InnerData should be haxe.ds._Vector.VectorData<Unknown<0>>

### ISSUE THREAD

**Issue by legiorange** [HeapsIO/heaps#865]
Code Here

`class Main extends hxd.App {
    override function init() {
        var tf = new h2d.Text(hxd.res.DefaultFont.get(), s2d);
        tf.text = "Hello World !";
    }
    static function main() {
        new Main();
    }
}`

 `-cp src
-D analyzer-optimize
-lib heaps
# -lib hlsdl
-main Main
--interp
`

D:\ProgramLang\haxe\haxe\lib\heaps/1,8,0/hxd/fmt/hmd/Library.hx:245: characters 43-63 : hxd._FloatBuffer.InnerData should be haxe.ds._Vector.VectorData<Unknown<0>>
D:\ProgramLang\haxe\haxe\lib\heaps/1,8,0/hxd/fmt/hmd/Library.hx:245: characters 43-63 : For function argument 'data'
The terminal process "D:\ProgramLang\haxe\haxe\haxe.exe '--connect', '6000', 'build.hxml'" terminated with exit code: 1.

I don't know why,
i change 
```
-js hello.js
# --interp
--debug

```
Is sloved, but I dont understand why.

**Comment by ncannasse** [comment]
You can't --interp with hlsdl, as it's a system library

**Comment by BransonGitomeh** [comment]
Hey i'm having a similar error trying to use haxe-cs. 

```haxe
class Main extends hxd.App {
    override function init() {
        var tf = new h2d.Text(hxd.res.DefaultFont.get(), s2d);
        tf.text = "Hello World !";
    }
    static function main() {
        new Main();
    }
}
```

```build-c#.hxml
-lib heaps
-cp src
-main Main
-cs bin/xbox/cs
```

```shell
➜  haxe c# haxe build-c\#.hxml
/usr/share/haxe/lib/heaps/1,8,0/hxd/fmt/hmd/Library.hx:245: characters 43-63 : hxd._FloatBuffer.InnerData should be haxe.ds._Vector.VectorData<Unknown<0>>
/usr/share/haxe/lib/heaps/1,8,0/hxd/fmt/hmd/Library.hx:245: characters 43-63 : For function argument 'data'
```

this js one works
```js
-lib heaps
-cp src
-main Main
-js bin/web/main.js
```

the error points to  https://github.com/HeapsIO/heaps/blob/master/hxd/fmt/hmd/Library.hx#L245
```haxe
				}
				buf.indexes[i] = rid - 1;
			}
			#if neko
			buf.vertexes = haxe.ds.Vector.fromArrayCopy(vertexes.getNative());
			#else
			buf.vertexes = haxe.ds.Vector.fromData(vertexes.getNative());
			#end
		}
```

thanks, please help?

**Comment by ncannasse** [comment]
Heaps does not support C# , only JS and HashLink

**Comment by BransonGitomeh** [comment]
ok how do i deploy hashlink to xbox for tests? i thought im supposed to go through UWP and deploy using vs-community remote deploy.

**Comment by BransonGitomeh** [comment]
also, any way in the heaps code we can add that check? `if not js or in hashlink -> error saying compilation target is not supported in heaps. `
