### ISSUE TITLE
Misleading name of `startDrag`

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#872]
As title says, `startDrag` is a bit misleading, since proper name would be `captureEvents`. When seeing current name, people just assume that they would start the drag operation and receive the mouse movement events, which is not true, as all input events are now delegated to the callback, hence the more proper name - `captureEvents`.
Essentially what I propose:
1. Rename the `startDrag` method to `captureEvents`, and `stopDrag` to `stopCapture` respectively.
2. Leave old start/stop methods with a deprecation notice.
This way, it won't cause a breaking change, but will mitigate the misleading naming of the method. And will add an ample amount of time for people to fix it, because deprecation warnings are annoying ;)

As a side note: In the h2d API docs I will call it as "capture input events", not as "drag and drop operation".

**Comment by ncannasse** [comment]
I agree that startDrag is not 100% correct, but I'm curious whereas you would use this feature for something else than drag n drop ? Because it's been designed exactly for this usage in mind so I think it works well this way.

**Comment by ncannasse** [comment]
But maybe startCapture/stopCapture works too.

**Comment by Yanrishatum** [comment]
While I agree that it's not really used for anything else, main issue that people don't expect to receive anything else except for mouse events, but in reality they get everything. What spurred me to open issue in the first place (I was aware of the misleading name for a while, but didn't really bothered with it) is simply because there was a person in discord chat that got glitches precisely because he did not expect keyboard events being sent as well. 

And it still can be used to target capturing other events such as keyboard as well. For example when you don't really have Interactive that takes focus, but by some action you need to stop the mouse interactivity and redirect everything to something that is controlled via keyboard, until condition is met.

**Comment by ncannasse** [comment]
Ok for startCapture/stopCapture then.
