### ISSUE TITLE
hxd.res.Embed using deprecated code

### ISSUE THREAD

**Issue by nevergarden** [HeapsIO/heaps#893]
Everytime compiling game to JavaScript Haxe complains about deprecated code:
`haxelib/heaps/git/hxd/res/Embed.hx:107: characters 3-9 : Warning : __js__ is deprecated, use js.Syntax.code instead`

https://github.com/HeapsIO/heaps/blob/271f4f6cbd3488afbe29cd9fb8a33feb0434b027/hxd/res/Embed.hx#L107

Fixing it would be matter of one minute.

**Comment by Sacramentix** [comment]
i will fix it

**Comment by nevergarden** [comment]
@Sacramentix already fixed waiting for approval.

**Comment by Sacramentix** [comment]
Your pull request break the support for haxe version < 4 you should use a conditionnal compilation block like in hxd/net/BinaryLoader.hx line 51

**Comment by nevergarden** [comment]
> Your pull request break the support for haxe version < 4 you should use a conditionnal compilation block like in hxd/net/BinaryLoader.hx line 51

👍🏿 gonna fix that...
