### ISSUE TITLE
Comments in hxml

### ISSUE THREAD

**Issue by JerryGreen** [HeapsIO/heaps#900]
I've just tried to go through hello world tutorial: https://heaps.io/documentation/hello-world.html, but at the step:

"Now, by hitting F5, the project will compile and run."

It seems there's some issues with the config:

```hxml
-cp src			# Tells haxe where to search for your code files
-lib heaps		# Tells haxe to import the heaps library
-js hello.js		# Tells haxe to compile to javascript in the project directory
-main Main		# Tells haxe that Main.hx is your entry point
-debug			# Tells haxe to run in debug mode
```

Because I've got some weird error:

```
Error: Could not process argument Main			# Tells haxe that Main.hx is your entry point
Package name must start with a lowercase letter
```

Though tutorial asks me to use "Main" with a uppercase M, it breaks, but ok... After changing it to lowercase (both configuration and file itself), then I'm now getting this:

```
Error: Could not process argument main			# Tells haxe that Main.hx is your entry point
Invalid character: \t
```

After deleting all the comments, it now asks for the uppercase back (but now it thinks it's class, not a package):

```
Class name must start with an uppercase letter
```

Additionally, I'd mention that it has some weird highlighting (even though Haxe Extension Pack is installed, and VSCode is restarted):

![image](https://user-images.githubusercontent.com/13215662/96594849-7f366400-1304-11eb-8d8e-2451a1150423.png)

Now, I ended up with the same file but without comments:

```hxml
-cp src
-lib heaps
-js hello.js
-main Main
-debug
```

And it seems that comments are not supported there in the first place???? Maybe add support for comments? :(

Or at least remove this clutter from the tutorial since it's invalid anyway :)

**Comment by ncannasse** [comment]
Thanks, it's been fixed here https://github.com/HeapsIO/heaps-doc/pull/48 and the website is in the progress of being updated.
