### ISSUE TITLE
How do I pack a Heaps game into executables?

### ISSUE THREAD

**Issue by JerryGreen** [HeapsIO/heaps#901]
How do I pack a project into an executable like `.exe` file for windows, and `.app` for macos? I haven't found related info in [Heaps documentation](https://heaps.io/documentation). P.S. it seems I'm not the only one wondering: https://community.heaps.io/t/exporting-to-exe-format/333.

I have found some info in [Haxe & HashLink docs](https://haxe.org/manual/target-hl-c-compilation.html) about compiling into `HashLink/C` though, and I was able to do this:

```bash
haxe --main Main --hl out/main.c
```

But after this, to compile it into executables, I needed to use gcc:

```bash
gcc -O3 -o hello -std=c++ -I out out/main.c -lhl [-L/path/to/required/hdll]
```

And I wasn't been able to do it, and I have several different problems with it:

### 1. What's `-lhl`, for starters?
I haven't found any info about it. So I gave it a try without this property (probably not the best idea, but at least I'll try)

### 2. `-std=c++` seems to be a mistake here, because we're compiling c, not c++, huh?
<blockquote><pre>
gcc: error: unrecognized command-line option ‘-std=c++’; did you mean ‘-std=c++03’?
</pre></blockquote>

So I've used `-std=c11` instead.

### 3. And eventually I ended up into:

<blockquote><pre>$ gcc -O3 -o bin/main -std=c11 -I out out/main.c
out/main.c:3:10: fatal error: hlc.h: No such file or directory
    3 | #include <hlc.h>
      |          ^~~~~~~
compilation terminated.
</pre>

![image](https://user-images.githubusercontent.com/13215662/97120442-d25f4b00-1738-11eb-9f6a-916fdce6be34.png)
</blockquote>

Are there some working examples of how to properly pack a game into executables? Or do you have some advice or something?

**Comment by rcstuber** [comment]
Compiling the generated C sources is just using the standard gcc (or any other C/C++) compiler, so you should best look at it's man pages for the meaning of those flags. So `-l` means "link the program agains library X", so `-lhl` means link agains HL (Hashlink) static library. So the compiler needs to find that library, which brings us to `-L` which sets a library search path to the Hashlink dll (or .so or .a if on Linux or Mac) so add the full path behind that flag. So now what's missing is the headers. The `-I` path points to the location of the headers, they are lying somewhere with the hashlink sources. Now things should work out.

**Comment by JerryGreen** [comment]
@rcstuber ok I found where those `.hdll` are placed, to properly use `-lhl` flag, but I now face a different error though:

```bash
Jerry@Jerry-PC MINGW64 ~/projects/heaps-examples/heaps-game (master)
$ ./compile.sh
In file included from C:/HaxeToolkit/hl-1.11.0-win/include/hlc.h:26,
                 from out/main.c:3:
C:/HaxeToolkit/hl-1.11.0-win/include/hl.h:243:11: fatal error: uchar.h: No such file or directory
  243 | # include <uchar.h>
      |           ^~~~~~~~~
compilation terminated.
```

With more details there under this little guide (thx for the link btw):

https://gist.github.com/Yanrishatum/d69ed72e368e35b18cbfca726d81279a#gistcomment-3505110

**Comment by ConstNW** [comment]
@JerryGreen look at deepnight's [Part 3 – Distributing a Haxe project](https://deepnight.net/tutorial/distributing-a-haxe-project/)

**Comment by JerryGreen** [comment]
@ConstNW "Part 3 – Distributing a Haxe project" article is quite useful, thanks for the link! I'm looking into his tutorials/examples right now, - they all seem very cool. Though for the compiling step he uses `redistHelper`, which (unfortunately) doesn't compile a straight windows application, but instead it compiles some weird executable console wrapper which then runs the game.

But from guide posted above, another good sir (@nyash) posted some steps of how to resolve that:

https://gist.github.com/Yanrishatum/d69ed72e368e35b18cbfca726d81279a#gistcomment-3506706

And now I'm completely satisfied with the end result. Thanks for all the links, again!
