### ISSUE TITLE
Could not found way to formatted `markup` macro code when use domkit.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [HeapsIO/heaps#907]
According to [haxe-formatter/issues/624](https://github.com/HaxeCheckstyle/haxe-formatter/issues/624) , the conclusion is `formatter doesn't support inline markup.`.
I think that is very regrettable, have you some suggestion about it? for example what formatter you used for develop the examples in `domkit`, or is there any way to formatted our code with markup syntax?

**Comment by ncannasse** [comment]
There is no alternative atm. The solution is to add support for inline
markup to haxeformater. See
https://github.com/HaxeCheckstyle/haxe-formatter/issues/523

Le sam. 7 nov. 2020 à 05:22, Water Zheng <notifications@github.com> a
écrit :

**Comment by rcstuber** [comment]
The poor workaround is to turn the formatter off before the code block and on afterwards, so it doesn't break the markup.


// @formatter:off
...

// @formatter:on

**Comment by zhengxiaoyao0716** [comment]
Could we use some metadata like `@:noFormat` to auto turn the formatter off on the domkit macros?

**Comment by AlexHaxe** [comment]
quick update: I've recently added support for inline markup to haxeparser. which by extension means current versions of formatter and checkstyle and future versions of vshaxe / languageserver(*) should be able to handle files with inline markup. 

(*) release date maybe soonish

**Comment by AlexHaxe** [comment]
version 2.25.0 of vshaxe is out. hopefully there is no need for workarounds anymore.
