### ISSUE TITLE
Error compiling generated cpp in linux 

### ISSUE THREAD

**Issue by Joilnen** [HeapsIO/heaps#919]
- src/hxd/snd/openal/Device.cpp 
 - src/h3d/Camera.cpp 
Error: In file included from ./src/__boot__.cpp:305:
include/hxd/impl/_Allocator/BufferFlags_Impl_.h:56:14: error: declaration of ‘int hxd::impl::_Allocator::BufferFlags_Impl__obj::Dynamic’ changes meaning of ‘Dynamic’ [-fpermissive]
   56 |   static int Dynamic;
      |              ^~~~~~~
In file included from /home/joilnen/.haxe/hxcpp/4,1,15/include/hxcpp.h:352:
/home/joilnen/.haxe/hxcpp/4,1,15/include/Dynamic.h:14:37: note: ‘Dynamic’ declared here as ‘class Dynamic’
   14 | class HXCPP_EXTERN_CLASS_ATTRIBUTES Dynamic : public hx::ObjectPtr<hx::Object>
      |                                     ^~~~~~~
Error: Build failed

**Comment by ncannasse** [comment]
Why are you mixing Hashlink and Hxcpp ? ;)

**Comment by Joilnen** [comment]
haxelib list
format: [3.5.0]
heaps: [1.8.0]
hxcpp: [4.1.15]

**Comment by Yanrishatum** [comment]
He meant that Heaps does not have an HXCPP backend, only ones supported are HashLink(+HL/C) and HTML5 (technically Flash too, but it's dead), with HL being either SDL, DirectX or console backends.

**Comment by Sacramentix** [comment]
You should also always use git version of heaps, haxelib version is very old
