### ISSUE TITLE
Document Camera

### ISSUE THREAD

**Issue by joereynolds** [HeapsIO/heaps#924]
Hi,

I'm trying to implement a scrolling camera and am finding the docs severely lacking in how to use it. 
Can we have a TL;DR on its usage?

I followed a few of the PRs for making the cameras but that didn't clear anything up.

Here are the docs I've read:
https://heaps.io/documentation/scenes.html
https://heaps.io/api/h2d/Camera.html

Happy to raise a PR for the docs if I can get this camera explained to me

**Comment by Yanrishatum** [comment]
heaps.io is extremely outdated and should not be used, because _someone_ not bothering to update the website.

For more up-to-date API see this: http://wb.yanrishatum.ru/heaps/api
And for the manual, see wiki: https://github.com/HeapsIO/heaps/wiki
Camera is documented in the code.

**Comment by joereynolds** [comment]
Great thanks
