### ISSUE TITLE
Unable to compile and run "Hello Hashlink"  example

### ISSUE THREAD

**Issue by le-michael** [HeapsIO/heaps#929]
Running `haxe .\compile.hxml`  for the "Hello Hashlink" example on heaps.io gives the following error:

```
C:/HaxeToolkit/haxlib/heaps/git/h3d/impl/GlDriver.hx:959: characters 30-48 : Class<sdl.GL> has no field TEXTURE_BASE_LEVEL
C:/HaxeToolkit/haxlib/heaps/git/h3d/impl/GlDriver.hx:960: characters 30-47 : Class<sdl.GL> has no field TEXTURE_MAX_LEVEL
C:/HaxeToolkit/haxlib/heaps/git/h3d/impl/GlDriver.hx:1199: characters 8-31 : Class<sdl.GL> has no field 
compressedTexSubImage3D (Suggestions: compressedTexImage3D, compressedTexImage2D)
C:/HaxeToolkit/haxlib/heaps/git/h3d/impl/GlDriver.hx:1205: characters 8-21 : Class<sdl.GL> has no field texSubImage3D (Suggestion: texImage3D) 
```

I was able to fix this by setting the `hlsdl` lib to have the latest changes on the hashlink repo https://github.com/HaxeFoundation/hashlink/tree/master/libs/sdl

However, now when I run `hl`  version `1.11.0`  in cmd i get the following error:
```
src\module.c(352) : FATAL ERROR : Failed to load library ?sdl.hdll 
```

Updating `hl` from version `1.11.0` to  `1.12.0` gives the following error
```
C:\HaxeToolkit\hashlink\src\module.c(362) : FATAL ERROR : Failed to load library sdl.hdll  
```

I am running Haxe version `4.2.0`

**Comment by le-michael** [comment]
Reverting Haxe back to version `4.1.5` and hl version `1.11.0` fixed this issue.

**Comment by trethaller** [comment]
My bad, I have introduced a dependency to unreleased additions to hlsdl. I have reverted the changes until a new release is available.
