### ISSUE TITLE
Detect touch screen

### ISSUE THREAD

**Issue by zommerfelds** [HeapsIO/heaps#943]
Not sure if this should be a Haxe issue or Heaps. I can't seem to detect if my device has a touch screen or not. This would be useful to handle ERelease events differently for a long press.

I tried `js.Browser.window.ontouchstart` but that seems to always be `null`.

I tried using `hxd.Event.touchId` but that seems to be `0`, even if it's not a touch screen.

I'd be happy to update documentation if there is a solution.

**Comment by ncannasse** [comment]
I think we have `hxd.System.getValue(IsTouch)` for that.

**Comment by zommerfelds** [comment]
Thank you Nicolas! I created a tiny PR to add this to a sample: https://github.com/HeapsIO/heaps/pull/944
