### ISSUE TITLE
Failed loading openal.hdll

### ISSUE THREAD

**Issue by andrewdylanvianaamorim2** [HeapsIO/heaps#945]
when i  try to run with hashlink i recive the fallowing message:  FATAL ERROR : Failed to load library openal.hdll

**code used to test: **

**Main.hx**
`class Main extends hxd.App {

    override function init() {

       	super.init();

    }

    static function main() {

        new Main();

    }

}
`
**file used to build:**

**build.hxml**
`
-lib heaps
-lib hlsdl
-main Main
-hl main

`

**infos**

os: Linux Mint 20.1
hashlink: 1.12.0
haxe:4.2.1
heaps: 1.91 (but i tested with haxelib git heaps https://github.com/HeapsIO/heaps.git on 24/03/2021 and problem persisted)
ps: i get my dependecies with ''sudo apt install libsdl2-*dev libopenal-dev"

**Comment by ncannasse** [comment]
Most likely a problem with your openal dependencies, look at `ldd openal.hdll`
