### ISSUE TITLE
make opengl 2 version available 

### ISSUE THREAD

**Issue by harshetmaruff** [HeapsIO/heaps#951]
Hi creators, i ran the cpp build and it says it would support on opengl3. but, the features can be made in webgl2 why not opengl 2

**Comment by ncannasse** [comment]
We don't support hxcpp platform

**Comment by ncannasse** [comment]
And in case you're talking about HashLink C code, webgl2 is opengl ES2 which includes features of opengl 3

**Comment by harshetmaruff** [comment]
> And in case you're talking about HashLink C code, webgl2 is opengl ES2 which includes features of opengl 3

yes yes webgl 2 has the features of opengl3, i saw in heaps where user doesnt have webgl 2 it switches back to webgl 1, can you make like that hashlink C code

**Comment by rcstuber** [comment]
Desktop OpenGL 2.0 is from 2004, that's stone age!

**Comment by harshetmaruff** [comment]
> Desktop OpenGL 2.0 is from 2004, that's stone age!

What can i do ?? my computer doesnt support i opengl3
