### ISSUE TITLE
Billboard sample in HXSL

### ISSUE THREAD

**Issue by rcstuber** [HeapsIO/heaps#952]
I am struggling to get a simple billboard (quad always facing camera) working with HXSL. The `modelView` matrix is – other than expected – not containing the actual view transformations, they seem to be in `camera.view`. Also how would one access single Matrix elements in the shader to reset the rotations?
An example would be much appreciated :)

Thanks!

**Comment by trethaller** [comment]
As a side note, the naming of `modelView` is very confusing, it should be renamed to `model` or `world` or something that doesn't have "view".
