### ISSUE TITLE
Heaps's PBR example makes AMD drivers crash

### ISSUE THREAD

**Issue by gabrielesilinic** [HeapsIO/heaps#954]
i installed the latest AMD drivers but doesn't seem to solve the issue, the PBR example makes everything crash when in browser and also when compiled with the hashlink VM as target, i'm not sure if i should bother the Heaps.io devs but just to be sure about them being aware of this problem i opened the issue anyway

some infos about my PC:
```
Software Version - 2021.0310.1434.26222
Driver Version - 20.50.03.01-210310a-365275C-RadeonSoftwareAdrenalin2020
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01486
OpenGL® Version - 26.20.11000.148202
AMD Audio Driver Version - 10.0.1.18
Vulkan™ Driver Version - 2.0.179
Vulkan™ API Version - 1.2.170
Windows Version - Windows 10 (64 bit)

GPU - AMD Radeon(TM) R5 Graphics - Primary/Integrated
VRAM - 1024 MB - DDR4 1066 MHz
Graphics Card Manufacturer - Powered by AMD
Graphics Chipset - AMD Radeon(TM) R5 Graphics
Device ID - 98E4
Vendor ID - 1002
SubSystem ID - 39F9
SubSystem Vendor ID - 17AA
Revision ID - DA
Bus Type - PCI
Current Bus Settings - PCI
BIOS Version - 015.049.000.016
BIOS Part Number - 113-C91400-007
BIOS Date - 2016/09/13 06:04
Usable Memory Size - 1024 MB
Memory Type - DDR4
Memory Clock - 1066 MHz
Core Clock - 847 MHz
Total Memory Bandwidth - 17 GByte/s
Memory Bit Rate - 2.13 Gbps
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
OpenGL® API Version - 4.6
OpenCL™ API Version - 2.0

CPU - AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G - 2 Cores
RAM - 8 GB
```
as i said i don't even know if i should just wait for the AMD driver devs to fix the problem
if someone knows a solution (es a safe version where the drivers don't crash) it would be nice if you tell me about this solution

<sup>(P.S. my english "sounds" a little broken sometimes, i'm sorry i tried my best)</sup>

**Comment by ncannasse** [comment]
What kind of crash do you get ?

**Comment by gabrielesilinic** [comment]
there isn't a precise error, it just crashes, when in browser the browser turns black when is the hashlink vm version the window just opens makes the drivers crash and then closes

here the recording of the crash:

https://user-images.githubusercontent.com/51238829/115301207-2fc0db80-a161-11eb-8354-d63b043211b2.mp4


if there is any helpful log file i can find just tell me where i find it

**Comment by ncannasse** [comment]
Uhm that's indeed a driver crash, not much we can do about it I think :'( did you try to report it ?

**Comment by gabrielesilinic** [comment]
> Uhm that's indeed a driver crash, not much we can do about it I think :'( did you try to report it ?

Yes, i tried, i'll wait, i might try to downgrade to see if i can fix something
