### ISSUE TITLE
HXLS texture array setup crash

### ISSUE THREAD

**Issue by rcstuber** [HeapsIO/heaps#958]
I hit some occasions where `hxls.RuntimeShaderData`'s `textures` field holds a texture array (`TArray` of `TSampler2D`) instead of a single texture. What `ShaderManager.getParamValue()` returns however will be cast to `h3d.mat.Texture` and a runtime crash occurs at this line: https://github.com/HeapsIO/heaps/blob/6540964671e5ae88bd2f50dabe4ec9ea0786c99e/h3d/pass/Default.hx#L77

Exception message is: ``Can't cast hl.types.ArrayObj to h3d.mat.Texture``

Not sure if this is due to misconfiguration of the shader or an actual bug?!

**Comment by ncannasse** [comment]
Could you give a reproducible sample ?

**Comment by rcstuber** [comment]
I am still trying to reproduce it in a simple sample setup with no success. I run into it in my game's complex shader setup, but have yet to figure out what the cause is to condense it. I will keep the issue open for a little longer if that's ok.
