### ISSUE TITLE
Blank screen when displaying text under hashlink but not under html/js

### ISSUE THREAD

**Issue by crimsonalucard** [HeapsIO/heaps#973]
The code in the repo here has the issue:
https://github.com/crimsonalucard/haxe_helloworld
run the following to reproduce:
```
git clone https://github.com/crimsonalucard/haxe_helloworld.git`
cd haxe_helloworld
haxe compil.hxml
hl hashlink/hello.hl
```
`index.html` works fine and displays the text and font correctly.

also running this under linux.

**Comment by ncannasse** [comment]
Runtime font drawing is not supported in HashLink, please use Bitmap generated fonts instead.
