### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by CrazyFlasher** [HeapsIO/heaps#986]
Sample on the site resizes fine:
https://heaps.io/samples/base2D/

However if I build from source, I get weird results:
![image](https://user-images.githubusercontent.com/1607138/125069006-d660ac80-e0be-11eb-9ab0-b05d5cf0134d.png)

**Comment by CrazyFlasher** [comment]
![image](https://user-images.githubusercontent.com/1607138/125076306-6d7e3200-e0c8-11eb-8425-3821a183751d.png)
for some reason, onResize is not called.
I've debugged sample here https://heaps.io/samples/base2D/ and onResize executes during stage resize

**Comment by CrazyFlasher** [comment]
I guess I found a commit "Remove useless listener and timer" db3ddc34385e132344c7e3f242ae114f061c0554 :)
![image](https://user-images.githubusercontent.com/1607138/125076364-7ec73e80-e0c8-11eb-838a-66c76cabdca9.png)
Looks like timer did the trick

**Comment by CrazyFlasher** [comment]
https://github.com/HeapsIO/heaps/pull/987

**Comment by ncannasse** [comment]
ping @trethaller

**Comment by trethaller** [comment]
IIRC we mostly had issues with the Timer, not so much the resize callback, so I've merged you PR and will see if anything breaks on our end
