### ISSUE TITLE
Flow fillWidth/fillHeight should take only the reamining space into account 

### ISSUE THREAD

**Issue by trethaller** [HeapsIO/heaps#994]
Currently fillWitdth takes the entire space available from the parent (constraintWidth). This only works when only 1 child is present, so we currently don't support this simple case of a parent with 2 children, one with a fixed width, another with flexible fillWidth:

```
[        parent         ]
[ <- fill -> ][  fixed  ]
```

The current behavior is:
```
[        parent         ]
[      <- fill ->       ][  fixed  ]
```

Which clearly feels like a bug. We could upgrade the current fill behavior:
- We take into account the available space, (constraintWidth minus all children widths) split it among "filling" children.
- When only 1 "filling" child is present, the behavior is the same as now

**Comment by rcstuber** [comment]
While you are at this, relative widths (i.e. take up 30% of parent's width) and heights would be awesome. It's really tedious to work only with static values :-/

**Comment by trethaller** [comment]
I've made a first attempt at this with https://github.com/HeapsIO/heaps/commit/a1f06059b87d7a9ed9074516d3c9e9dfd0588e78
It feels like it should really be linked to fill-width, because it currently never makes any sense to use fill-width without this right now.

**Comment by trethaller** [comment]
One limitation of the commit above is that flex only works when a constraint exists (so a fixed-size) is set. This is also a current limitation of fill-width, which doesn't allow, for example to "take as much horizontal space as my siblings take" in a vertical flow, which is often very useful. 
For this we would need to mark the filling children as not affecting the size of their parent, to avoid cyclic dependencies. 
Maybe flow could automatically constraint specifically its flex children using the current remaining space, regardless of whether it is currently constrained.

**Comment by trethaller** [comment]
This has finally been resolved with autoSize property of flow children c4ec47395a236bffe889ae49a6b4c7be4ea50d10. 
There is currently nothing automatically linking the usage of fillWidth with autoSize, so fillWidth alone on flows (without autoSize) only makes sense when there are no siblings in a horizontal parent flow and vice versa.
