### ISSUE TITLE
Haxe Timers execute an additional callback after being stopped from another thread in Haxe 4.2.3 + Hashlink

### ISSUE THREAD

**Issue by Cleod9** [HeapsIO/heaps#995]
We encountered an issue in Heaps 1.9.1 where Timers were being executed an additional tick after being stopped within the thread of another timer. (It seems like this is another side effect of the [threading changes in Haxe 4.2.x](https://github.com/HeapsIO/heaps/pull/932)?). See below for a simple reproducible use case:

```haxe
package;

/**
 * Demonstrates threading bug with timers in Haxe 4.2.3 / Hashlink 1.11.0 (confirmed reproducible in nightly as of 2021.08.05)
 */
class Main extends hxd.App {
  // Create two timers
  var timer1:haxe.Timer;
  var timer2:haxe.Timer;

  // Countdown before triggering the bug
  var count = 0;
  var stopped:Bool = false;

  override function init() {

    timer1 = new haxe.Timer(1);
    timer1.run = () -> {
      // Simply print "hello world" repeatedly
      trace('hello world! ' + count);

      if (stopped) {
        trace("I ran one more time even though i was stopped?");
      }
    };

    timer2 = new haxe.Timer(1);
    timer2.run = () -> {
      // Count up to 120 (~2 seconds) before stopping both timers
      count++;
      if (count == 120) {
        // Stop the first timer
        timer1.stop();
        stopped = true;
        // Observe timer1.run still executes one more time, printing an additional trace statement
        // Expected behavior: Because both timers were stopped, timer1 should not attempt to execute run() again

        // timer1.run = null; // Uncomment this for a fun crash :)
      }
    };
  }

  static function main() {
    new Main();
  }
}
```
The expected behavior if two timers are running and one stops the other is for the other timer's callback to never be executed again. (Note that this is also reproducible in the latest Haxe Nightly)

**Comment by ncannasse** [comment]
This is a Haxe issue not a heaps one. Please submit to haxe GitHub.

**Comment by Cleod9** [comment]
> 
> 
> This is a Haxe issue not a heaps one. Please submit to haxe GitHub.

@ncannasse I should have clarified this issue does not occur in vanilla Hashlink, only with Heaps (i.e. extending hxd.App) . In my investigation there seems to be some relation to this recent change:
https://github.com/HeapsIO/heaps/pull/932/files#diff-c0fa4e889efa97012174175edcce85cc359792651eb5e7435d2f0c0ed26dec0aR152
Before I open up another issue, are you certain this is a Haxe issue?

**Comment by ncannasse** [comment]
Ping @Yanrishatum

**Comment by ncannasse** [comment]
I can no longer reproduce with latest Haxe GIT, we reported and fixed several haxe.Timer issues recently there.
