### ISSUE TITLE
[Info] Vulkan Support

### ISSUE THREAD

**Issue by onehundredfeet** [HeapsIO/heaps#998]
Hi Folks,

I was wondering if there was any way to use Vulkan as the rendering backend with heaps? 

Cheers,
Ryan.

**Comment by ncannasse** [comment]
Not atm, there's a wip vulkan support for hashlink but it's far from being done.
https://github.com/haxeFoundation/hashlink/tree/vulkan
https://github.com/HeapsIO/heaps/tree/vulkan
